// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.api;

public interface AcceptTosResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AcceptTosResponse)
    com.google.protobuf.MessageLiteOrBuilder {
}
