// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.api;

public interface AvailabilityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Availability)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int32 restriction = 5;</code>
   */
  boolean hasRestriction();
  /**
   * <code>optional int32 restriction = 5;</code>
   */
  int getRestriction();

  /**
   * <code>optional int32 offerType = 6;</code>
   */
  boolean hasOfferType();
  /**
   * <code>optional int32 offerType = 6;</code>
   */
  int getOfferType();

  /**
   * <code>optional .Rule rule = 7;</code>
   */
  boolean hasRule();
  /**
   * <code>optional .Rule rule = 7;</code>
   */
  com.github.yeriomin.playstore.api.Rule getRule();

  /**
   * <code>repeated group PerDeviceAvailabilityRestriction = 9 { ... }</code>
   */
  java.util.List<com.github.yeriomin.playstore.api.Availability.PerDeviceAvailabilityRestriction> 
      getPerDeviceAvailabilityRestrictionList();
  /**
   * <code>repeated group PerDeviceAvailabilityRestriction = 9 { ... }</code>
   */
  com.github.yeriomin.playstore.api.Availability.PerDeviceAvailabilityRestriction getPerDeviceAvailabilityRestriction(int index);
  /**
   * <code>repeated group PerDeviceAvailabilityRestriction = 9 { ... }</code>
   */
  int getPerDeviceAvailabilityRestrictionCount();

  /**
   * <code>optional bool availableIfOwned = 13;</code>
   */
  boolean hasAvailableIfOwned();
  /**
   * <code>optional bool availableIfOwned = 13;</code>
   */
  boolean getAvailableIfOwned();

  /**
   * <code>repeated .Install install = 14;</code>
   */
  java.util.List<com.github.yeriomin.playstore.api.Install> 
      getInstallList();
  /**
   * <code>repeated .Install install = 14;</code>
   */
  com.github.yeriomin.playstore.api.Install getInstall(int index);
  /**
   * <code>repeated .Install install = 14;</code>
   */
  int getInstallCount();

  /**
   * <code>optional .FilterEvaluationInfo filterInfo = 16;</code>
   */
  boolean hasFilterInfo();
  /**
   * <code>optional .FilterEvaluationInfo filterInfo = 16;</code>
   */
  com.github.yeriomin.playstore.api.FilterEvaluationInfo getFilterInfo();

  /**
   * <code>optional .OwnershipInfo ownershipInfo = 17;</code>
   */
  boolean hasOwnershipInfo();
  /**
   * <code>optional .OwnershipInfo ownershipInfo = 17;</code>
   */
  com.github.yeriomin.playstore.api.OwnershipInfo getOwnershipInfo();
}
