// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.api;

/**
 * Protobuf type {@code PackageInfo}
 */
public  final class PackageInfo extends
    com.google.protobuf.GeneratedMessageLite<
        PackageInfo, PackageInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:PackageInfo)
    PackageInfoOrBuilder {
  private PackageInfo() {
    pkgName_ = "";
  }
  private int bitField0_;
  public static final int PKGNAME_FIELD_NUMBER = 1;
  private java.lang.String pkgName_;
  /**
   * <code>optional string pkgName = 1;</code>
   */
  public boolean hasPkgName() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string pkgName = 1;</code>
   */
  public java.lang.String getPkgName() {
    return pkgName_;
  }
  /**
   * <code>optional string pkgName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPkgNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(pkgName_);
  }
  /**
   * <code>optional string pkgName = 1;</code>
   */
  private void setPkgName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    pkgName_ = value;
  }
  /**
   * <code>optional string pkgName = 1;</code>
   */
  private void clearPkgName() {
    bitField0_ = (bitField0_ & ~0x00000001);
    pkgName_ = getDefaultInstance().getPkgName();
  }
  /**
   * <code>optional string pkgName = 1;</code>
   */
  private void setPkgNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    pkgName_ = value.toStringUtf8();
  }

  public static final int VERSIONCODE_FIELD_NUMBER = 2;
  private int versionCode_;
  /**
   * <code>optional int32 versionCode = 2;</code>
   */
  public boolean hasVersionCode() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int32 versionCode = 2;</code>
   */
  public int getVersionCode() {
    return versionCode_;
  }
  /**
   * <code>optional int32 versionCode = 2;</code>
   */
  private void setVersionCode(int value) {
    bitField0_ |= 0x00000002;
    versionCode_ = value;
  }
  /**
   * <code>optional int32 versionCode = 2;</code>
   */
  private void clearVersionCode() {
    bitField0_ = (bitField0_ & ~0x00000002);
    versionCode_ = 0;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeString(1, getPkgName());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, versionCode_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getPkgName());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, versionCode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static com.github.yeriomin.playstore.api.PackageInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstore.api.PackageInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.api.PackageInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstore.api.PackageInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.api.PackageInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.api.PackageInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.api.PackageInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.api.PackageInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.api.PackageInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.api.PackageInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.yeriomin.playstore.api.PackageInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code PackageInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.github.yeriomin.playstore.api.PackageInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:PackageInfo)
      com.github.yeriomin.playstore.api.PackageInfoOrBuilder {
    // Construct using com.github.yeriomin.playstoreapi.PackageInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string pkgName = 1;</code>
     */
    public boolean hasPkgName() {
      return instance.hasPkgName();
    }
    /**
     * <code>optional string pkgName = 1;</code>
     */
    public java.lang.String getPkgName() {
      return instance.getPkgName();
    }
    /**
     * <code>optional string pkgName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPkgNameBytes() {
      return instance.getPkgNameBytes();
    }
    /**
     * <code>optional string pkgName = 1;</code>
     */
    public Builder setPkgName(
        java.lang.String value) {
      copyOnWrite();
      instance.setPkgName(value);
      return this;
    }
    /**
     * <code>optional string pkgName = 1;</code>
     */
    public Builder clearPkgName() {
      copyOnWrite();
      instance.clearPkgName();
      return this;
    }
    /**
     * <code>optional string pkgName = 1;</code>
     */
    public Builder setPkgNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPkgNameBytes(value);
      return this;
    }

    /**
     * <code>optional int32 versionCode = 2;</code>
     */
    public boolean hasVersionCode() {
      return instance.hasVersionCode();
    }
    /**
     * <code>optional int32 versionCode = 2;</code>
     */
    public int getVersionCode() {
      return instance.getVersionCode();
    }
    /**
     * <code>optional int32 versionCode = 2;</code>
     */
    public Builder setVersionCode(int value) {
      copyOnWrite();
      instance.setVersionCode(value);
      return this;
    }
    /**
     * <code>optional int32 versionCode = 2;</code>
     */
    public Builder clearVersionCode() {
      copyOnWrite();
      instance.clearVersionCode();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PackageInfo)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.github.yeriomin.playstore.api.PackageInfo();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.github.yeriomin.playstore.api.PackageInfo other = (com.github.yeriomin.playstore.api.PackageInfo) arg1;
        pkgName_ = visitor.visitString(
            hasPkgName(), pkgName_,
            other.hasPkgName(), other.pkgName_);
        versionCode_ = visitor.visitInt(
            hasVersionCode(), versionCode_,
            other.hasVersionCode(), other.versionCode_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readString();
                bitField0_ |= 0x00000001;
                pkgName_ = s;
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                versionCode_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.github.yeriomin.playstore.api.PackageInfo.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:PackageInfo)
  private static final com.github.yeriomin.playstore.api.PackageInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PackageInfo();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.github.yeriomin.playstore.api.PackageInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PackageInfo> PARSER;

  public static com.google.protobuf.Parser<PackageInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

