// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.api;

/**
 * Protobuf type {@code Payload}
 */
public  final class Payload extends
    com.google.protobuf.GeneratedMessageLite<
        Payload, Payload.Builder> implements
    // @@protoc_insertion_point(message_implements:Payload)
    PayloadOrBuilder {
  private Payload() {
    logResponse_ = "";
    flagContentResponse_ = "";
  }
  private int bitField0_;
  public static final int LISTRESPONSE_FIELD_NUMBER = 1;
  private com.github.yeriomin.playstore.api.ListResponse listResponse_;
  /**
   * <code>optional .ListResponse listResponse = 1;</code>
   */
  public boolean hasListResponse() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional .ListResponse listResponse = 1;</code>
   */
  public com.github.yeriomin.playstore.api.ListResponse getListResponse() {
    return listResponse_ == null ? com.github.yeriomin.playstore.api.ListResponse.getDefaultInstance() : listResponse_;
  }
  /**
   * <code>optional .ListResponse listResponse = 1;</code>
   */
  private void setListResponse(com.github.yeriomin.playstore.api.ListResponse value) {
    if (value == null) {
      throw new NullPointerException();
    }
    listResponse_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>optional .ListResponse listResponse = 1;</code>
   */
  private void setListResponse(
      com.github.yeriomin.playstore.api.ListResponse.Builder builderForValue) {
    listResponse_ = builderForValue.build();
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .ListResponse listResponse = 1;</code>
   */
  private void mergeListResponse(com.github.yeriomin.playstore.api.ListResponse value) {
    if (listResponse_ != null &&
        listResponse_ != com.github.yeriomin.playstore.api.ListResponse.getDefaultInstance()) {
      listResponse_ =
        com.github.yeriomin.playstore.api.ListResponse.newBuilder(listResponse_).mergeFrom(value).buildPartial();
    } else {
      listResponse_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .ListResponse listResponse = 1;</code>
   */
  private void clearListResponse() {  listResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int DETAILSRESPONSE_FIELD_NUMBER = 2;
  private com.github.yeriomin.playstore.api.DetailsResponse detailsResponse_;
  /**
   * <code>optional .DetailsResponse detailsResponse = 2;</code>
   */
  public boolean hasDetailsResponse() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .DetailsResponse detailsResponse = 2;</code>
   */
  public com.github.yeriomin.playstore.api.DetailsResponse getDetailsResponse() {
    return detailsResponse_ == null ? com.github.yeriomin.playstore.api.DetailsResponse.getDefaultInstance() : detailsResponse_;
  }
  /**
   * <code>optional .DetailsResponse detailsResponse = 2;</code>
   */
  private void setDetailsResponse(com.github.yeriomin.playstore.api.DetailsResponse value) {
    if (value == null) {
      throw new NullPointerException();
    }
    detailsResponse_ = value;
    bitField0_ |= 0x00000002;
    }
  /**
   * <code>optional .DetailsResponse detailsResponse = 2;</code>
   */
  private void setDetailsResponse(
      com.github.yeriomin.playstore.api.DetailsResponse.Builder builderForValue) {
    detailsResponse_ = builderForValue.build();
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>optional .DetailsResponse detailsResponse = 2;</code>
   */
  private void mergeDetailsResponse(com.github.yeriomin.playstore.api.DetailsResponse value) {
    if (detailsResponse_ != null &&
        detailsResponse_ != com.github.yeriomin.playstore.api.DetailsResponse.getDefaultInstance()) {
      detailsResponse_ =
        com.github.yeriomin.playstore.api.DetailsResponse.newBuilder(detailsResponse_).mergeFrom(value).buildPartial();
    } else {
      detailsResponse_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>optional .DetailsResponse detailsResponse = 2;</code>
   */
  private void clearDetailsResponse() {  detailsResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static final int REVIEWRESPONSE_FIELD_NUMBER = 3;
  private com.github.yeriomin.playstore.api.ReviewResponse reviewResponse_;
  /**
   * <code>optional .ReviewResponse reviewResponse = 3;</code>
   */
  public boolean hasReviewResponse() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional .ReviewResponse reviewResponse = 3;</code>
   */
  public com.github.yeriomin.playstore.api.ReviewResponse getReviewResponse() {
    return reviewResponse_ == null ? com.github.yeriomin.playstore.api.ReviewResponse.getDefaultInstance() : reviewResponse_;
  }
  /**
   * <code>optional .ReviewResponse reviewResponse = 3;</code>
   */
  private void setReviewResponse(com.github.yeriomin.playstore.api.ReviewResponse value) {
    if (value == null) {
      throw new NullPointerException();
    }
    reviewResponse_ = value;
    bitField0_ |= 0x00000004;
    }
  /**
   * <code>optional .ReviewResponse reviewResponse = 3;</code>
   */
  private void setReviewResponse(
      com.github.yeriomin.playstore.api.ReviewResponse.Builder builderForValue) {
    reviewResponse_ = builderForValue.build();
    bitField0_ |= 0x00000004;
  }
  /**
   * <code>optional .ReviewResponse reviewResponse = 3;</code>
   */
  private void mergeReviewResponse(com.github.yeriomin.playstore.api.ReviewResponse value) {
    if (reviewResponse_ != null &&
        reviewResponse_ != com.github.yeriomin.playstore.api.ReviewResponse.getDefaultInstance()) {
      reviewResponse_ =
        com.github.yeriomin.playstore.api.ReviewResponse.newBuilder(reviewResponse_).mergeFrom(value).buildPartial();
    } else {
      reviewResponse_ = value;
    }
    bitField0_ |= 0x00000004;
  }
  /**
   * <code>optional .ReviewResponse reviewResponse = 3;</code>
   */
  private void clearReviewResponse() {  reviewResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00000004);
  }

  public static final int BUYRESPONSE_FIELD_NUMBER = 4;
  private com.github.yeriomin.playstore.api.BuyResponse buyResponse_;
  /**
   * <code>optional .BuyResponse buyResponse = 4;</code>
   */
  public boolean hasBuyResponse() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional .BuyResponse buyResponse = 4;</code>
   */
  public com.github.yeriomin.playstore.api.BuyResponse getBuyResponse() {
    return buyResponse_ == null ? com.github.yeriomin.playstore.api.BuyResponse.getDefaultInstance() : buyResponse_;
  }
  /**
   * <code>optional .BuyResponse buyResponse = 4;</code>
   */
  private void setBuyResponse(com.github.yeriomin.playstore.api.BuyResponse value) {
    if (value == null) {
      throw new NullPointerException();
    }
    buyResponse_ = value;
    bitField0_ |= 0x00000008;
    }
  /**
   * <code>optional .BuyResponse buyResponse = 4;</code>
   */
  private void setBuyResponse(
      com.github.yeriomin.playstore.api.BuyResponse.Builder builderForValue) {
    buyResponse_ = builderForValue.build();
    bitField0_ |= 0x00000008;
  }
  /**
   * <code>optional .BuyResponse buyResponse = 4;</code>
   */
  private void mergeBuyResponse(com.github.yeriomin.playstore.api.BuyResponse value) {
    if (buyResponse_ != null &&
        buyResponse_ != com.github.yeriomin.playstore.api.BuyResponse.getDefaultInstance()) {
      buyResponse_ =
        com.github.yeriomin.playstore.api.BuyResponse.newBuilder(buyResponse_).mergeFrom(value).buildPartial();
    } else {
      buyResponse_ = value;
    }
    bitField0_ |= 0x00000008;
  }
  /**
   * <code>optional .BuyResponse buyResponse = 4;</code>
   */
  private void clearBuyResponse() {  buyResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00000008);
  }

  public static final int SEARCHRESPONSE_FIELD_NUMBER = 5;
  private com.github.yeriomin.playstore.api.SearchResponse searchResponse_;
  /**
   * <code>optional .SearchResponse searchResponse = 5;</code>
   */
  public boolean hasSearchResponse() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional .SearchResponse searchResponse = 5;</code>
   */
  public com.github.yeriomin.playstore.api.SearchResponse getSearchResponse() {
    return searchResponse_ == null ? com.github.yeriomin.playstore.api.SearchResponse.getDefaultInstance() : searchResponse_;
  }
  /**
   * <code>optional .SearchResponse searchResponse = 5;</code>
   */
  private void setSearchResponse(com.github.yeriomin.playstore.api.SearchResponse value) {
    if (value == null) {
      throw new NullPointerException();
    }
    searchResponse_ = value;
    bitField0_ |= 0x00000010;
    }
  /**
   * <code>optional .SearchResponse searchResponse = 5;</code>
   */
  private void setSearchResponse(
      com.github.yeriomin.playstore.api.SearchResponse.Builder builderForValue) {
    searchResponse_ = builderForValue.build();
    bitField0_ |= 0x00000010;
  }
  /**
   * <code>optional .SearchResponse searchResponse = 5;</code>
   */
  private void mergeSearchResponse(com.github.yeriomin.playstore.api.SearchResponse value) {
    if (searchResponse_ != null &&
        searchResponse_ != com.github.yeriomin.playstore.api.SearchResponse.getDefaultInstance()) {
      searchResponse_ =
        com.github.yeriomin.playstore.api.SearchResponse.newBuilder(searchResponse_).mergeFrom(value).buildPartial();
    } else {
      searchResponse_ = value;
    }
    bitField0_ |= 0x00000010;
  }
  /**
   * <code>optional .SearchResponse searchResponse = 5;</code>
   */
  private void clearSearchResponse() {  searchResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00000010);
  }

  public static final int TOCRESPONSE_FIELD_NUMBER = 6;
  private com.github.yeriomin.playstore.api.TocResponse tocResponse_;
  /**
   * <code>optional .TocResponse tocResponse = 6;</code>
   */
  public boolean hasTocResponse() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional .TocResponse tocResponse = 6;</code>
   */
  public com.github.yeriomin.playstore.api.TocResponse getTocResponse() {
    return tocResponse_ == null ? com.github.yeriomin.playstore.api.TocResponse.getDefaultInstance() : tocResponse_;
  }
  /**
   * <code>optional .TocResponse tocResponse = 6;</code>
   */
  private void setTocResponse(com.github.yeriomin.playstore.api.TocResponse value) {
    if (value == null) {
      throw new NullPointerException();
    }
    tocResponse_ = value;
    bitField0_ |= 0x00000020;
    }
  /**
   * <code>optional .TocResponse tocResponse = 6;</code>
   */
  private void setTocResponse(
      com.github.yeriomin.playstore.api.TocResponse.Builder builderForValue) {
    tocResponse_ = builderForValue.build();
    bitField0_ |= 0x00000020;
  }
  /**
   * <code>optional .TocResponse tocResponse = 6;</code>
   */
  private void mergeTocResponse(com.github.yeriomin.playstore.api.TocResponse value) {
    if (tocResponse_ != null &&
        tocResponse_ != com.github.yeriomin.playstore.api.TocResponse.getDefaultInstance()) {
      tocResponse_ =
        com.github.yeriomin.playstore.api.TocResponse.newBuilder(tocResponse_).mergeFrom(value).buildPartial();
    } else {
      tocResponse_ = value;
    }
    bitField0_ |= 0x00000020;
  }
  /**
   * <code>optional .TocResponse tocResponse = 6;</code>
   */
  private void clearTocResponse() {  tocResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00000020);
  }

  public static final int BROWSERESPONSE_FIELD_NUMBER = 7;
  private com.github.yeriomin.playstore.api.BrowseResponse browseResponse_;
  /**
   * <code>optional .BrowseResponse browseResponse = 7;</code>
   */
  public boolean hasBrowseResponse() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional .BrowseResponse browseResponse = 7;</code>
   */
  public com.github.yeriomin.playstore.api.BrowseResponse getBrowseResponse() {
    return browseResponse_ == null ? com.github.yeriomin.playstore.api.BrowseResponse.getDefaultInstance() : browseResponse_;
  }
  /**
   * <code>optional .BrowseResponse browseResponse = 7;</code>
   */
  private void setBrowseResponse(com.github.yeriomin.playstore.api.BrowseResponse value) {
    if (value == null) {
      throw new NullPointerException();
    }
    browseResponse_ = value;
    bitField0_ |= 0x00000040;
    }
  /**
   * <code>optional .BrowseResponse browseResponse = 7;</code>
   */
  private void setBrowseResponse(
      com.github.yeriomin.playstore.api.BrowseResponse.Builder builderForValue) {
    browseResponse_ = builderForValue.build();
    bitField0_ |= 0x00000040;
  }
  /**
   * <code>optional .BrowseResponse browseResponse = 7;</code>
   */
  private void mergeBrowseResponse(com.github.yeriomin.playstore.api.BrowseResponse value) {
    if (browseResponse_ != null &&
        browseResponse_ != com.github.yeriomin.playstore.api.BrowseResponse.getDefaultInstance()) {
      browseResponse_ =
        com.github.yeriomin.playstore.api.BrowseResponse.newBuilder(browseResponse_).mergeFrom(value).buildPartial();
    } else {
      browseResponse_ = value;
    }
    bitField0_ |= 0x00000040;
  }
  /**
   * <code>optional .BrowseResponse browseResponse = 7;</code>
   */
  private void clearBrowseResponse() {  browseResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00000040);
  }

  public static final int PURCHASESTATUSRESPONSE_FIELD_NUMBER = 8;
  private com.github.yeriomin.playstore.api.PurchaseStatusResponse purchaseStatusResponse_;
  /**
   * <code>optional .PurchaseStatusResponse purchaseStatusResponse = 8;</code>
   */
  public boolean hasPurchaseStatusResponse() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional .PurchaseStatusResponse purchaseStatusResponse = 8;</code>
   */
  public com.github.yeriomin.playstore.api.PurchaseStatusResponse getPurchaseStatusResponse() {
    return purchaseStatusResponse_ == null ? com.github.yeriomin.playstore.api.PurchaseStatusResponse.getDefaultInstance() : purchaseStatusResponse_;
  }
  /**
   * <code>optional .PurchaseStatusResponse purchaseStatusResponse = 8;</code>
   */
  private void setPurchaseStatusResponse(com.github.yeriomin.playstore.api.PurchaseStatusResponse value) {
    if (value == null) {
      throw new NullPointerException();
    }
    purchaseStatusResponse_ = value;
    bitField0_ |= 0x00000080;
    }
  /**
   * <code>optional .PurchaseStatusResponse purchaseStatusResponse = 8;</code>
   */
  private void setPurchaseStatusResponse(
      com.github.yeriomin.playstore.api.PurchaseStatusResponse.Builder builderForValue) {
    purchaseStatusResponse_ = builderForValue.build();
    bitField0_ |= 0x00000080;
  }
  /**
   * <code>optional .PurchaseStatusResponse purchaseStatusResponse = 8;</code>
   */
  private void mergePurchaseStatusResponse(com.github.yeriomin.playstore.api.PurchaseStatusResponse value) {
    if (purchaseStatusResponse_ != null &&
        purchaseStatusResponse_ != com.github.yeriomin.playstore.api.PurchaseStatusResponse.getDefaultInstance()) {
      purchaseStatusResponse_ =
        com.github.yeriomin.playstore.api.PurchaseStatusResponse.newBuilder(purchaseStatusResponse_).mergeFrom(value).buildPartial();
    } else {
      purchaseStatusResponse_ = value;
    }
    bitField0_ |= 0x00000080;
  }
  /**
   * <code>optional .PurchaseStatusResponse purchaseStatusResponse = 8;</code>
   */
  private void clearPurchaseStatusResponse() {  purchaseStatusResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00000080);
  }

  public static final int LOGRESPONSE_FIELD_NUMBER = 10;
  private java.lang.String logResponse_;
  /**
   * <code>optional string logResponse = 10;</code>
   */
  public boolean hasLogResponse() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional string logResponse = 10;</code>
   */
  public java.lang.String getLogResponse() {
    return logResponse_;
  }
  /**
   * <code>optional string logResponse = 10;</code>
   */
  public com.google.protobuf.ByteString
      getLogResponseBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(logResponse_);
  }
  /**
   * <code>optional string logResponse = 10;</code>
   */
  private void setLogResponse(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
    logResponse_ = value;
  }
  /**
   * <code>optional string logResponse = 10;</code>
   */
  private void clearLogResponse() {
    bitField0_ = (bitField0_ & ~0x00000100);
    logResponse_ = getDefaultInstance().getLogResponse();
  }
  /**
   * <code>optional string logResponse = 10;</code>
   */
  private void setLogResponseBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
    logResponse_ = value.toStringUtf8();
  }

  public static final int FLAGCONTENTRESPONSE_FIELD_NUMBER = 13;
  private java.lang.String flagContentResponse_;
  /**
   * <code>optional string flagContentResponse = 13;</code>
   */
  public boolean hasFlagContentResponse() {
    return ((bitField0_ & 0x00000200) == 0x00000200);
  }
  /**
   * <code>optional string flagContentResponse = 13;</code>
   */
  public java.lang.String getFlagContentResponse() {
    return flagContentResponse_;
  }
  /**
   * <code>optional string flagContentResponse = 13;</code>
   */
  public com.google.protobuf.ByteString
      getFlagContentResponseBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(flagContentResponse_);
  }
  /**
   * <code>optional string flagContentResponse = 13;</code>
   */
  private void setFlagContentResponse(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
    flagContentResponse_ = value;
  }
  /**
   * <code>optional string flagContentResponse = 13;</code>
   */
  private void clearFlagContentResponse() {
    bitField0_ = (bitField0_ & ~0x00000200);
    flagContentResponse_ = getDefaultInstance().getFlagContentResponse();
  }
  /**
   * <code>optional string flagContentResponse = 13;</code>
   */
  private void setFlagContentResponseBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
    flagContentResponse_ = value.toStringUtf8();
  }

  public static final int BULKDETAILSRESPONSE_FIELD_NUMBER = 19;
  private com.github.yeriomin.playstore.api.BulkDetailsResponse bulkDetailsResponse_;
  /**
   * <code>optional .BulkDetailsResponse bulkDetailsResponse = 19;</code>
   */
  public boolean hasBulkDetailsResponse() {
    return ((bitField0_ & 0x00000400) == 0x00000400);
  }
  /**
   * <code>optional .BulkDetailsResponse bulkDetailsResponse = 19;</code>
   */
  public com.github.yeriomin.playstore.api.BulkDetailsResponse getBulkDetailsResponse() {
    return bulkDetailsResponse_ == null ? com.github.yeriomin.playstore.api.BulkDetailsResponse.getDefaultInstance() : bulkDetailsResponse_;
  }
  /**
   * <code>optional .BulkDetailsResponse bulkDetailsResponse = 19;</code>
   */
  private void setBulkDetailsResponse(com.github.yeriomin.playstore.api.BulkDetailsResponse value) {
    if (value == null) {
      throw new NullPointerException();
    }
    bulkDetailsResponse_ = value;
    bitField0_ |= 0x00000400;
    }
  /**
   * <code>optional .BulkDetailsResponse bulkDetailsResponse = 19;</code>
   */
  private void setBulkDetailsResponse(
      com.github.yeriomin.playstore.api.BulkDetailsResponse.Builder builderForValue) {
    bulkDetailsResponse_ = builderForValue.build();
    bitField0_ |= 0x00000400;
  }
  /**
   * <code>optional .BulkDetailsResponse bulkDetailsResponse = 19;</code>
   */
  private void mergeBulkDetailsResponse(com.github.yeriomin.playstore.api.BulkDetailsResponse value) {
    if (bulkDetailsResponse_ != null &&
        bulkDetailsResponse_ != com.github.yeriomin.playstore.api.BulkDetailsResponse.getDefaultInstance()) {
      bulkDetailsResponse_ =
        com.github.yeriomin.playstore.api.BulkDetailsResponse.newBuilder(bulkDetailsResponse_).mergeFrom(value).buildPartial();
    } else {
      bulkDetailsResponse_ = value;
    }
    bitField0_ |= 0x00000400;
  }
  /**
   * <code>optional .BulkDetailsResponse bulkDetailsResponse = 19;</code>
   */
  private void clearBulkDetailsResponse() {  bulkDetailsResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00000400);
  }

  public static final int DELIVERYRESPONSE_FIELD_NUMBER = 21;
  private com.github.yeriomin.playstore.api.DeliveryResponse deliveryResponse_;
  /**
   * <code>optional .DeliveryResponse deliveryResponse = 21;</code>
   */
  public boolean hasDeliveryResponse() {
    return ((bitField0_ & 0x00000800) == 0x00000800);
  }
  /**
   * <code>optional .DeliveryResponse deliveryResponse = 21;</code>
   */
  public com.github.yeriomin.playstore.api.DeliveryResponse getDeliveryResponse() {
    return deliveryResponse_ == null ? com.github.yeriomin.playstore.api.DeliveryResponse.getDefaultInstance() : deliveryResponse_;
  }
  /**
   * <code>optional .DeliveryResponse deliveryResponse = 21;</code>
   */
  private void setDeliveryResponse(com.github.yeriomin.playstore.api.DeliveryResponse value) {
    if (value == null) {
      throw new NullPointerException();
    }
    deliveryResponse_ = value;
    bitField0_ |= 0x00000800;
    }
  /**
   * <code>optional .DeliveryResponse deliveryResponse = 21;</code>
   */
  private void setDeliveryResponse(
      com.github.yeriomin.playstore.api.DeliveryResponse.Builder builderForValue) {
    deliveryResponse_ = builderForValue.build();
    bitField0_ |= 0x00000800;
  }
  /**
   * <code>optional .DeliveryResponse deliveryResponse = 21;</code>
   */
  private void mergeDeliveryResponse(com.github.yeriomin.playstore.api.DeliveryResponse value) {
    if (deliveryResponse_ != null &&
        deliveryResponse_ != com.github.yeriomin.playstore.api.DeliveryResponse.getDefaultInstance()) {
      deliveryResponse_ =
        com.github.yeriomin.playstore.api.DeliveryResponse.newBuilder(deliveryResponse_).mergeFrom(value).buildPartial();
    } else {
      deliveryResponse_ = value;
    }
    bitField0_ |= 0x00000800;
  }
  /**
   * <code>optional .DeliveryResponse deliveryResponse = 21;</code>
   */
  private void clearDeliveryResponse() {  deliveryResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00000800);
  }

  public static final int ACCEPTTOSRESPONSE_FIELD_NUMBER = 22;
  private com.github.yeriomin.playstore.api.AcceptTosResponse acceptTosResponse_;
  /**
   * <code>optional .AcceptTosResponse acceptTosResponse = 22;</code>
   */
  public boolean hasAcceptTosResponse() {
    return ((bitField0_ & 0x00001000) == 0x00001000);
  }
  /**
   * <code>optional .AcceptTosResponse acceptTosResponse = 22;</code>
   */
  public com.github.yeriomin.playstore.api.AcceptTosResponse getAcceptTosResponse() {
    return acceptTosResponse_ == null ? com.github.yeriomin.playstore.api.AcceptTosResponse.getDefaultInstance() : acceptTosResponse_;
  }
  /**
   * <code>optional .AcceptTosResponse acceptTosResponse = 22;</code>
   */
  private void setAcceptTosResponse(com.github.yeriomin.playstore.api.AcceptTosResponse value) {
    if (value == null) {
      throw new NullPointerException();
    }
    acceptTosResponse_ = value;
    bitField0_ |= 0x00001000;
    }
  /**
   * <code>optional .AcceptTosResponse acceptTosResponse = 22;</code>
   */
  private void setAcceptTosResponse(
      com.github.yeriomin.playstore.api.AcceptTosResponse.Builder builderForValue) {
    acceptTosResponse_ = builderForValue.build();
    bitField0_ |= 0x00001000;
  }
  /**
   * <code>optional .AcceptTosResponse acceptTosResponse = 22;</code>
   */
  private void mergeAcceptTosResponse(com.github.yeriomin.playstore.api.AcceptTosResponse value) {
    if (acceptTosResponse_ != null &&
        acceptTosResponse_ != com.github.yeriomin.playstore.api.AcceptTosResponse.getDefaultInstance()) {
      acceptTosResponse_ =
        com.github.yeriomin.playstore.api.AcceptTosResponse.newBuilder(acceptTosResponse_).mergeFrom(value).buildPartial();
    } else {
      acceptTosResponse_ = value;
    }
    bitField0_ |= 0x00001000;
  }
  /**
   * <code>optional .AcceptTosResponse acceptTosResponse = 22;</code>
   */
  private void clearAcceptTosResponse() {  acceptTosResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00001000);
  }

  public static final int ANDROIDCHECKINRESPONSE_FIELD_NUMBER = 26;
  private com.github.yeriomin.playstore.api.AndroidCheckinResponse androidCheckinResponse_;
  /**
   * <code>optional .AndroidCheckinResponse androidCheckinResponse = 26;</code>
   */
  public boolean hasAndroidCheckinResponse() {
    return ((bitField0_ & 0x00002000) == 0x00002000);
  }
  /**
   * <code>optional .AndroidCheckinResponse androidCheckinResponse = 26;</code>
   */
  public com.github.yeriomin.playstore.api.AndroidCheckinResponse getAndroidCheckinResponse() {
    return androidCheckinResponse_ == null ? com.github.yeriomin.playstore.api.AndroidCheckinResponse.getDefaultInstance() : androidCheckinResponse_;
  }
  /**
   * <code>optional .AndroidCheckinResponse androidCheckinResponse = 26;</code>
   */
  private void setAndroidCheckinResponse(com.github.yeriomin.playstore.api.AndroidCheckinResponse value) {
    if (value == null) {
      throw new NullPointerException();
    }
    androidCheckinResponse_ = value;
    bitField0_ |= 0x00002000;
    }
  /**
   * <code>optional .AndroidCheckinResponse androidCheckinResponse = 26;</code>
   */
  private void setAndroidCheckinResponse(
      com.github.yeriomin.playstore.api.AndroidCheckinResponse.Builder builderForValue) {
    androidCheckinResponse_ = builderForValue.build();
    bitField0_ |= 0x00002000;
  }
  /**
   * <code>optional .AndroidCheckinResponse androidCheckinResponse = 26;</code>
   */
  private void mergeAndroidCheckinResponse(com.github.yeriomin.playstore.api.AndroidCheckinResponse value) {
    if (androidCheckinResponse_ != null &&
        androidCheckinResponse_ != com.github.yeriomin.playstore.api.AndroidCheckinResponse.getDefaultInstance()) {
      androidCheckinResponse_ =
        com.github.yeriomin.playstore.api.AndroidCheckinResponse.newBuilder(androidCheckinResponse_).mergeFrom(value).buildPartial();
    } else {
      androidCheckinResponse_ = value;
    }
    bitField0_ |= 0x00002000;
  }
  /**
   * <code>optional .AndroidCheckinResponse androidCheckinResponse = 26;</code>
   */
  private void clearAndroidCheckinResponse() {  androidCheckinResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00002000);
  }

  public static final int UPLOADDEVICECONFIGRESPONSE_FIELD_NUMBER = 28;
  private com.github.yeriomin.playstore.api.UploadDeviceConfigResponse uploadDeviceConfigResponse_;
  /**
   * <code>optional .UploadDeviceConfigResponse uploadDeviceConfigResponse = 28;</code>
   */
  public boolean hasUploadDeviceConfigResponse() {
    return ((bitField0_ & 0x00004000) == 0x00004000);
  }
  /**
   * <code>optional .UploadDeviceConfigResponse uploadDeviceConfigResponse = 28;</code>
   */
  public com.github.yeriomin.playstore.api.UploadDeviceConfigResponse getUploadDeviceConfigResponse() {
    return uploadDeviceConfigResponse_ == null ? com.github.yeriomin.playstore.api.UploadDeviceConfigResponse.getDefaultInstance() : uploadDeviceConfigResponse_;
  }
  /**
   * <code>optional .UploadDeviceConfigResponse uploadDeviceConfigResponse = 28;</code>
   */
  private void setUploadDeviceConfigResponse(com.github.yeriomin.playstore.api.UploadDeviceConfigResponse value) {
    if (value == null) {
      throw new NullPointerException();
    }
    uploadDeviceConfigResponse_ = value;
    bitField0_ |= 0x00004000;
    }
  /**
   * <code>optional .UploadDeviceConfigResponse uploadDeviceConfigResponse = 28;</code>
   */
  private void setUploadDeviceConfigResponse(
      com.github.yeriomin.playstore.api.UploadDeviceConfigResponse.Builder builderForValue) {
    uploadDeviceConfigResponse_ = builderForValue.build();
    bitField0_ |= 0x00004000;
  }
  /**
   * <code>optional .UploadDeviceConfigResponse uploadDeviceConfigResponse = 28;</code>
   */
  private void mergeUploadDeviceConfigResponse(com.github.yeriomin.playstore.api.UploadDeviceConfigResponse value) {
    if (uploadDeviceConfigResponse_ != null &&
        uploadDeviceConfigResponse_ != com.github.yeriomin.playstore.api.UploadDeviceConfigResponse.getDefaultInstance()) {
      uploadDeviceConfigResponse_ =
        com.github.yeriomin.playstore.api.UploadDeviceConfigResponse.newBuilder(uploadDeviceConfigResponse_).mergeFrom(value).buildPartial();
    } else {
      uploadDeviceConfigResponse_ = value;
    }
    bitField0_ |= 0x00004000;
  }
  /**
   * <code>optional .UploadDeviceConfigResponse uploadDeviceConfigResponse = 28;</code>
   */
  private void clearUploadDeviceConfigResponse() {  uploadDeviceConfigResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00004000);
  }

  public static final int SEARCHSUGGESTRESPONSE_FIELD_NUMBER = 40;
  private com.github.yeriomin.playstore.api.SearchSuggestResponse searchSuggestResponse_;
  /**
   * <code>optional .SearchSuggestResponse searchSuggestResponse = 40;</code>
   */
  public boolean hasSearchSuggestResponse() {
    return ((bitField0_ & 0x00008000) == 0x00008000);
  }
  /**
   * <code>optional .SearchSuggestResponse searchSuggestResponse = 40;</code>
   */
  public com.github.yeriomin.playstore.api.SearchSuggestResponse getSearchSuggestResponse() {
    return searchSuggestResponse_ == null ? com.github.yeriomin.playstore.api.SearchSuggestResponse.getDefaultInstance() : searchSuggestResponse_;
  }
  /**
   * <code>optional .SearchSuggestResponse searchSuggestResponse = 40;</code>
   */
  private void setSearchSuggestResponse(com.github.yeriomin.playstore.api.SearchSuggestResponse value) {
    if (value == null) {
      throw new NullPointerException();
    }
    searchSuggestResponse_ = value;
    bitField0_ |= 0x00008000;
    }
  /**
   * <code>optional .SearchSuggestResponse searchSuggestResponse = 40;</code>
   */
  private void setSearchSuggestResponse(
      com.github.yeriomin.playstore.api.SearchSuggestResponse.Builder builderForValue) {
    searchSuggestResponse_ = builderForValue.build();
    bitField0_ |= 0x00008000;
  }
  /**
   * <code>optional .SearchSuggestResponse searchSuggestResponse = 40;</code>
   */
  private void mergeSearchSuggestResponse(com.github.yeriomin.playstore.api.SearchSuggestResponse value) {
    if (searchSuggestResponse_ != null &&
        searchSuggestResponse_ != com.github.yeriomin.playstore.api.SearchSuggestResponse.getDefaultInstance()) {
      searchSuggestResponse_ =
        com.github.yeriomin.playstore.api.SearchSuggestResponse.newBuilder(searchSuggestResponse_).mergeFrom(value).buildPartial();
    } else {
      searchSuggestResponse_ = value;
    }
    bitField0_ |= 0x00008000;
  }
  /**
   * <code>optional .SearchSuggestResponse searchSuggestResponse = 40;</code>
   */
  private void clearSearchSuggestResponse() {  searchSuggestResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00008000);
  }

  public static final int TESTINGPROGRAMRESPONSE_FIELD_NUMBER = 80;
  private com.github.yeriomin.playstore.api.TestingProgramResponse testingProgramResponse_;
  /**
   * <code>optional .TestingProgramResponse testingProgramResponse = 80;</code>
   */
  public boolean hasTestingProgramResponse() {
    return ((bitField0_ & 0x00010000) == 0x00010000);
  }
  /**
   * <code>optional .TestingProgramResponse testingProgramResponse = 80;</code>
   */
  public com.github.yeriomin.playstore.api.TestingProgramResponse getTestingProgramResponse() {
    return testingProgramResponse_ == null ? com.github.yeriomin.playstore.api.TestingProgramResponse.getDefaultInstance() : testingProgramResponse_;
  }
  /**
   * <code>optional .TestingProgramResponse testingProgramResponse = 80;</code>
   */
  private void setTestingProgramResponse(com.github.yeriomin.playstore.api.TestingProgramResponse value) {
    if (value == null) {
      throw new NullPointerException();
    }
    testingProgramResponse_ = value;
    bitField0_ |= 0x00010000;
    }
  /**
   * <code>optional .TestingProgramResponse testingProgramResponse = 80;</code>
   */
  private void setTestingProgramResponse(
      com.github.yeriomin.playstore.api.TestingProgramResponse.Builder builderForValue) {
    testingProgramResponse_ = builderForValue.build();
    bitField0_ |= 0x00010000;
  }
  /**
   * <code>optional .TestingProgramResponse testingProgramResponse = 80;</code>
   */
  private void mergeTestingProgramResponse(com.github.yeriomin.playstore.api.TestingProgramResponse value) {
    if (testingProgramResponse_ != null &&
        testingProgramResponse_ != com.github.yeriomin.playstore.api.TestingProgramResponse.getDefaultInstance()) {
      testingProgramResponse_ =
        com.github.yeriomin.playstore.api.TestingProgramResponse.newBuilder(testingProgramResponse_).mergeFrom(value).buildPartial();
    } else {
      testingProgramResponse_ = value;
    }
    bitField0_ |= 0x00010000;
  }
  /**
   * <code>optional .TestingProgramResponse testingProgramResponse = 80;</code>
   */
  private void clearTestingProgramResponse() {  testingProgramResponse_ = null;
    bitField0_ = (bitField0_ & ~0x00010000);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, getListResponse());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, getDetailsResponse());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeMessage(3, getReviewResponse());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeMessage(4, getBuyResponse());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeMessage(5, getSearchResponse());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeMessage(6, getTocResponse());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeMessage(7, getBrowseResponse());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeMessage(8, getPurchaseStatusResponse());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeString(10, getLogResponse());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      output.writeString(13, getFlagContentResponse());
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      output.writeMessage(19, getBulkDetailsResponse());
    }
    if (((bitField0_ & 0x00000800) == 0x00000800)) {
      output.writeMessage(21, getDeliveryResponse());
    }
    if (((bitField0_ & 0x00001000) == 0x00001000)) {
      output.writeMessage(22, getAcceptTosResponse());
    }
    if (((bitField0_ & 0x00002000) == 0x00002000)) {
      output.writeMessage(26, getAndroidCheckinResponse());
    }
    if (((bitField0_ & 0x00004000) == 0x00004000)) {
      output.writeMessage(28, getUploadDeviceConfigResponse());
    }
    if (((bitField0_ & 0x00008000) == 0x00008000)) {
      output.writeMessage(40, getSearchSuggestResponse());
    }
    if (((bitField0_ & 0x00010000) == 0x00010000)) {
      output.writeMessage(80, getTestingProgramResponse());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getListResponse());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDetailsResponse());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getReviewResponse());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getBuyResponse());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getSearchResponse());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getTocResponse());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getBrowseResponse());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getPurchaseStatusResponse());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(10, getLogResponse());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(13, getFlagContentResponse());
    }
    if (((bitField0_ & 0x00000400) == 0x00000400)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(19, getBulkDetailsResponse());
    }
    if (((bitField0_ & 0x00000800) == 0x00000800)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(21, getDeliveryResponse());
    }
    if (((bitField0_ & 0x00001000) == 0x00001000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(22, getAcceptTosResponse());
    }
    if (((bitField0_ & 0x00002000) == 0x00002000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(26, getAndroidCheckinResponse());
    }
    if (((bitField0_ & 0x00004000) == 0x00004000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(28, getUploadDeviceConfigResponse());
    }
    if (((bitField0_ & 0x00008000) == 0x00008000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(40, getSearchSuggestResponse());
    }
    if (((bitField0_ & 0x00010000) == 0x00010000)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(80, getTestingProgramResponse());
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static com.github.yeriomin.playstore.api.Payload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstore.api.Payload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.api.Payload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstore.api.Payload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.api.Payload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.api.Payload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.api.Payload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.api.Payload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.api.Payload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.api.Payload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.yeriomin.playstore.api.Payload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code Payload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.github.yeriomin.playstore.api.Payload, Builder> implements
      // @@protoc_insertion_point(builder_implements:Payload)
      com.github.yeriomin.playstore.api.PayloadOrBuilder {
    // Construct using com.github.yeriomin.playstoreapi.Payload.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .ListResponse listResponse = 1;</code>
     */
    public boolean hasListResponse() {
      return instance.hasListResponse();
    }
    /**
     * <code>optional .ListResponse listResponse = 1;</code>
     */
    public com.github.yeriomin.playstore.api.ListResponse getListResponse() {
      return instance.getListResponse();
    }
    /**
     * <code>optional .ListResponse listResponse = 1;</code>
     */
    public Builder setListResponse(com.github.yeriomin.playstore.api.ListResponse value) {
      copyOnWrite();
      instance.setListResponse(value);
      return this;
      }
    /**
     * <code>optional .ListResponse listResponse = 1;</code>
     */
    public Builder setListResponse(
        com.github.yeriomin.playstore.api.ListResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setListResponse(builderForValue);
      return this;
    }
    /**
     * <code>optional .ListResponse listResponse = 1;</code>
     */
    public Builder mergeListResponse(com.github.yeriomin.playstore.api.ListResponse value) {
      copyOnWrite();
      instance.mergeListResponse(value);
      return this;
    }
    /**
     * <code>optional .ListResponse listResponse = 1;</code>
     */
    public Builder clearListResponse() {  copyOnWrite();
      instance.clearListResponse();
      return this;
    }

    /**
     * <code>optional .DetailsResponse detailsResponse = 2;</code>
     */
    public boolean hasDetailsResponse() {
      return instance.hasDetailsResponse();
    }
    /**
     * <code>optional .DetailsResponse detailsResponse = 2;</code>
     */
    public com.github.yeriomin.playstore.api.DetailsResponse getDetailsResponse() {
      return instance.getDetailsResponse();
    }
    /**
     * <code>optional .DetailsResponse detailsResponse = 2;</code>
     */
    public Builder setDetailsResponse(com.github.yeriomin.playstore.api.DetailsResponse value) {
      copyOnWrite();
      instance.setDetailsResponse(value);
      return this;
      }
    /**
     * <code>optional .DetailsResponse detailsResponse = 2;</code>
     */
    public Builder setDetailsResponse(
        com.github.yeriomin.playstore.api.DetailsResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setDetailsResponse(builderForValue);
      return this;
    }
    /**
     * <code>optional .DetailsResponse detailsResponse = 2;</code>
     */
    public Builder mergeDetailsResponse(com.github.yeriomin.playstore.api.DetailsResponse value) {
      copyOnWrite();
      instance.mergeDetailsResponse(value);
      return this;
    }
    /**
     * <code>optional .DetailsResponse detailsResponse = 2;</code>
     */
    public Builder clearDetailsResponse() {  copyOnWrite();
      instance.clearDetailsResponse();
      return this;
    }

    /**
     * <code>optional .ReviewResponse reviewResponse = 3;</code>
     */
    public boolean hasReviewResponse() {
      return instance.hasReviewResponse();
    }
    /**
     * <code>optional .ReviewResponse reviewResponse = 3;</code>
     */
    public com.github.yeriomin.playstore.api.ReviewResponse getReviewResponse() {
      return instance.getReviewResponse();
    }
    /**
     * <code>optional .ReviewResponse reviewResponse = 3;</code>
     */
    public Builder setReviewResponse(com.github.yeriomin.playstore.api.ReviewResponse value) {
      copyOnWrite();
      instance.setReviewResponse(value);
      return this;
      }
    /**
     * <code>optional .ReviewResponse reviewResponse = 3;</code>
     */
    public Builder setReviewResponse(
        com.github.yeriomin.playstore.api.ReviewResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setReviewResponse(builderForValue);
      return this;
    }
    /**
     * <code>optional .ReviewResponse reviewResponse = 3;</code>
     */
    public Builder mergeReviewResponse(com.github.yeriomin.playstore.api.ReviewResponse value) {
      copyOnWrite();
      instance.mergeReviewResponse(value);
      return this;
    }
    /**
     * <code>optional .ReviewResponse reviewResponse = 3;</code>
     */
    public Builder clearReviewResponse() {  copyOnWrite();
      instance.clearReviewResponse();
      return this;
    }

    /**
     * <code>optional .BuyResponse buyResponse = 4;</code>
     */
    public boolean hasBuyResponse() {
      return instance.hasBuyResponse();
    }
    /**
     * <code>optional .BuyResponse buyResponse = 4;</code>
     */
    public com.github.yeriomin.playstore.api.BuyResponse getBuyResponse() {
      return instance.getBuyResponse();
    }
    /**
     * <code>optional .BuyResponse buyResponse = 4;</code>
     */
    public Builder setBuyResponse(com.github.yeriomin.playstore.api.BuyResponse value) {
      copyOnWrite();
      instance.setBuyResponse(value);
      return this;
      }
    /**
     * <code>optional .BuyResponse buyResponse = 4;</code>
     */
    public Builder setBuyResponse(
        com.github.yeriomin.playstore.api.BuyResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setBuyResponse(builderForValue);
      return this;
    }
    /**
     * <code>optional .BuyResponse buyResponse = 4;</code>
     */
    public Builder mergeBuyResponse(com.github.yeriomin.playstore.api.BuyResponse value) {
      copyOnWrite();
      instance.mergeBuyResponse(value);
      return this;
    }
    /**
     * <code>optional .BuyResponse buyResponse = 4;</code>
     */
    public Builder clearBuyResponse() {  copyOnWrite();
      instance.clearBuyResponse();
      return this;
    }

    /**
     * <code>optional .SearchResponse searchResponse = 5;</code>
     */
    public boolean hasSearchResponse() {
      return instance.hasSearchResponse();
    }
    /**
     * <code>optional .SearchResponse searchResponse = 5;</code>
     */
    public com.github.yeriomin.playstore.api.SearchResponse getSearchResponse() {
      return instance.getSearchResponse();
    }
    /**
     * <code>optional .SearchResponse searchResponse = 5;</code>
     */
    public Builder setSearchResponse(com.github.yeriomin.playstore.api.SearchResponse value) {
      copyOnWrite();
      instance.setSearchResponse(value);
      return this;
      }
    /**
     * <code>optional .SearchResponse searchResponse = 5;</code>
     */
    public Builder setSearchResponse(
        com.github.yeriomin.playstore.api.SearchResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setSearchResponse(builderForValue);
      return this;
    }
    /**
     * <code>optional .SearchResponse searchResponse = 5;</code>
     */
    public Builder mergeSearchResponse(com.github.yeriomin.playstore.api.SearchResponse value) {
      copyOnWrite();
      instance.mergeSearchResponse(value);
      return this;
    }
    /**
     * <code>optional .SearchResponse searchResponse = 5;</code>
     */
    public Builder clearSearchResponse() {  copyOnWrite();
      instance.clearSearchResponse();
      return this;
    }

    /**
     * <code>optional .TocResponse tocResponse = 6;</code>
     */
    public boolean hasTocResponse() {
      return instance.hasTocResponse();
    }
    /**
     * <code>optional .TocResponse tocResponse = 6;</code>
     */
    public com.github.yeriomin.playstore.api.TocResponse getTocResponse() {
      return instance.getTocResponse();
    }
    /**
     * <code>optional .TocResponse tocResponse = 6;</code>
     */
    public Builder setTocResponse(com.github.yeriomin.playstore.api.TocResponse value) {
      copyOnWrite();
      instance.setTocResponse(value);
      return this;
      }
    /**
     * <code>optional .TocResponse tocResponse = 6;</code>
     */
    public Builder setTocResponse(
        com.github.yeriomin.playstore.api.TocResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setTocResponse(builderForValue);
      return this;
    }
    /**
     * <code>optional .TocResponse tocResponse = 6;</code>
     */
    public Builder mergeTocResponse(com.github.yeriomin.playstore.api.TocResponse value) {
      copyOnWrite();
      instance.mergeTocResponse(value);
      return this;
    }
    /**
     * <code>optional .TocResponse tocResponse = 6;</code>
     */
    public Builder clearTocResponse() {  copyOnWrite();
      instance.clearTocResponse();
      return this;
    }

    /**
     * <code>optional .BrowseResponse browseResponse = 7;</code>
     */
    public boolean hasBrowseResponse() {
      return instance.hasBrowseResponse();
    }
    /**
     * <code>optional .BrowseResponse browseResponse = 7;</code>
     */
    public com.github.yeriomin.playstore.api.BrowseResponse getBrowseResponse() {
      return instance.getBrowseResponse();
    }
    /**
     * <code>optional .BrowseResponse browseResponse = 7;</code>
     */
    public Builder setBrowseResponse(com.github.yeriomin.playstore.api.BrowseResponse value) {
      copyOnWrite();
      instance.setBrowseResponse(value);
      return this;
      }
    /**
     * <code>optional .BrowseResponse browseResponse = 7;</code>
     */
    public Builder setBrowseResponse(
        com.github.yeriomin.playstore.api.BrowseResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setBrowseResponse(builderForValue);
      return this;
    }
    /**
     * <code>optional .BrowseResponse browseResponse = 7;</code>
     */
    public Builder mergeBrowseResponse(com.github.yeriomin.playstore.api.BrowseResponse value) {
      copyOnWrite();
      instance.mergeBrowseResponse(value);
      return this;
    }
    /**
     * <code>optional .BrowseResponse browseResponse = 7;</code>
     */
    public Builder clearBrowseResponse() {  copyOnWrite();
      instance.clearBrowseResponse();
      return this;
    }

    /**
     * <code>optional .PurchaseStatusResponse purchaseStatusResponse = 8;</code>
     */
    public boolean hasPurchaseStatusResponse() {
      return instance.hasPurchaseStatusResponse();
    }
    /**
     * <code>optional .PurchaseStatusResponse purchaseStatusResponse = 8;</code>
     */
    public com.github.yeriomin.playstore.api.PurchaseStatusResponse getPurchaseStatusResponse() {
      return instance.getPurchaseStatusResponse();
    }
    /**
     * <code>optional .PurchaseStatusResponse purchaseStatusResponse = 8;</code>
     */
    public Builder setPurchaseStatusResponse(com.github.yeriomin.playstore.api.PurchaseStatusResponse value) {
      copyOnWrite();
      instance.setPurchaseStatusResponse(value);
      return this;
      }
    /**
     * <code>optional .PurchaseStatusResponse purchaseStatusResponse = 8;</code>
     */
    public Builder setPurchaseStatusResponse(
        com.github.yeriomin.playstore.api.PurchaseStatusResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setPurchaseStatusResponse(builderForValue);
      return this;
    }
    /**
     * <code>optional .PurchaseStatusResponse purchaseStatusResponse = 8;</code>
     */
    public Builder mergePurchaseStatusResponse(com.github.yeriomin.playstore.api.PurchaseStatusResponse value) {
      copyOnWrite();
      instance.mergePurchaseStatusResponse(value);
      return this;
    }
    /**
     * <code>optional .PurchaseStatusResponse purchaseStatusResponse = 8;</code>
     */
    public Builder clearPurchaseStatusResponse() {  copyOnWrite();
      instance.clearPurchaseStatusResponse();
      return this;
    }

    /**
     * <code>optional string logResponse = 10;</code>
     */
    public boolean hasLogResponse() {
      return instance.hasLogResponse();
    }
    /**
     * <code>optional string logResponse = 10;</code>
     */
    public java.lang.String getLogResponse() {
      return instance.getLogResponse();
    }
    /**
     * <code>optional string logResponse = 10;</code>
     */
    public com.google.protobuf.ByteString
        getLogResponseBytes() {
      return instance.getLogResponseBytes();
    }
    /**
     * <code>optional string logResponse = 10;</code>
     */
    public Builder setLogResponse(
        java.lang.String value) {
      copyOnWrite();
      instance.setLogResponse(value);
      return this;
    }
    /**
     * <code>optional string logResponse = 10;</code>
     */
    public Builder clearLogResponse() {
      copyOnWrite();
      instance.clearLogResponse();
      return this;
    }
    /**
     * <code>optional string logResponse = 10;</code>
     */
    public Builder setLogResponseBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLogResponseBytes(value);
      return this;
    }

    /**
     * <code>optional string flagContentResponse = 13;</code>
     */
    public boolean hasFlagContentResponse() {
      return instance.hasFlagContentResponse();
    }
    /**
     * <code>optional string flagContentResponse = 13;</code>
     */
    public java.lang.String getFlagContentResponse() {
      return instance.getFlagContentResponse();
    }
    /**
     * <code>optional string flagContentResponse = 13;</code>
     */
    public com.google.protobuf.ByteString
        getFlagContentResponseBytes() {
      return instance.getFlagContentResponseBytes();
    }
    /**
     * <code>optional string flagContentResponse = 13;</code>
     */
    public Builder setFlagContentResponse(
        java.lang.String value) {
      copyOnWrite();
      instance.setFlagContentResponse(value);
      return this;
    }
    /**
     * <code>optional string flagContentResponse = 13;</code>
     */
    public Builder clearFlagContentResponse() {
      copyOnWrite();
      instance.clearFlagContentResponse();
      return this;
    }
    /**
     * <code>optional string flagContentResponse = 13;</code>
     */
    public Builder setFlagContentResponseBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFlagContentResponseBytes(value);
      return this;
    }

    /**
     * <code>optional .BulkDetailsResponse bulkDetailsResponse = 19;</code>
     */
    public boolean hasBulkDetailsResponse() {
      return instance.hasBulkDetailsResponse();
    }
    /**
     * <code>optional .BulkDetailsResponse bulkDetailsResponse = 19;</code>
     */
    public com.github.yeriomin.playstore.api.BulkDetailsResponse getBulkDetailsResponse() {
      return instance.getBulkDetailsResponse();
    }
    /**
     * <code>optional .BulkDetailsResponse bulkDetailsResponse = 19;</code>
     */
    public Builder setBulkDetailsResponse(com.github.yeriomin.playstore.api.BulkDetailsResponse value) {
      copyOnWrite();
      instance.setBulkDetailsResponse(value);
      return this;
      }
    /**
     * <code>optional .BulkDetailsResponse bulkDetailsResponse = 19;</code>
     */
    public Builder setBulkDetailsResponse(
        com.github.yeriomin.playstore.api.BulkDetailsResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setBulkDetailsResponse(builderForValue);
      return this;
    }
    /**
     * <code>optional .BulkDetailsResponse bulkDetailsResponse = 19;</code>
     */
    public Builder mergeBulkDetailsResponse(com.github.yeriomin.playstore.api.BulkDetailsResponse value) {
      copyOnWrite();
      instance.mergeBulkDetailsResponse(value);
      return this;
    }
    /**
     * <code>optional .BulkDetailsResponse bulkDetailsResponse = 19;</code>
     */
    public Builder clearBulkDetailsResponse() {  copyOnWrite();
      instance.clearBulkDetailsResponse();
      return this;
    }

    /**
     * <code>optional .DeliveryResponse deliveryResponse = 21;</code>
     */
    public boolean hasDeliveryResponse() {
      return instance.hasDeliveryResponse();
    }
    /**
     * <code>optional .DeliveryResponse deliveryResponse = 21;</code>
     */
    public com.github.yeriomin.playstore.api.DeliveryResponse getDeliveryResponse() {
      return instance.getDeliveryResponse();
    }
    /**
     * <code>optional .DeliveryResponse deliveryResponse = 21;</code>
     */
    public Builder setDeliveryResponse(com.github.yeriomin.playstore.api.DeliveryResponse value) {
      copyOnWrite();
      instance.setDeliveryResponse(value);
      return this;
      }
    /**
     * <code>optional .DeliveryResponse deliveryResponse = 21;</code>
     */
    public Builder setDeliveryResponse(
        com.github.yeriomin.playstore.api.DeliveryResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setDeliveryResponse(builderForValue);
      return this;
    }
    /**
     * <code>optional .DeliveryResponse deliveryResponse = 21;</code>
     */
    public Builder mergeDeliveryResponse(com.github.yeriomin.playstore.api.DeliveryResponse value) {
      copyOnWrite();
      instance.mergeDeliveryResponse(value);
      return this;
    }
    /**
     * <code>optional .DeliveryResponse deliveryResponse = 21;</code>
     */
    public Builder clearDeliveryResponse() {  copyOnWrite();
      instance.clearDeliveryResponse();
      return this;
    }

    /**
     * <code>optional .AcceptTosResponse acceptTosResponse = 22;</code>
     */
    public boolean hasAcceptTosResponse() {
      return instance.hasAcceptTosResponse();
    }
    /**
     * <code>optional .AcceptTosResponse acceptTosResponse = 22;</code>
     */
    public com.github.yeriomin.playstore.api.AcceptTosResponse getAcceptTosResponse() {
      return instance.getAcceptTosResponse();
    }
    /**
     * <code>optional .AcceptTosResponse acceptTosResponse = 22;</code>
     */
    public Builder setAcceptTosResponse(com.github.yeriomin.playstore.api.AcceptTosResponse value) {
      copyOnWrite();
      instance.setAcceptTosResponse(value);
      return this;
      }
    /**
     * <code>optional .AcceptTosResponse acceptTosResponse = 22;</code>
     */
    public Builder setAcceptTosResponse(
        com.github.yeriomin.playstore.api.AcceptTosResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setAcceptTosResponse(builderForValue);
      return this;
    }
    /**
     * <code>optional .AcceptTosResponse acceptTosResponse = 22;</code>
     */
    public Builder mergeAcceptTosResponse(com.github.yeriomin.playstore.api.AcceptTosResponse value) {
      copyOnWrite();
      instance.mergeAcceptTosResponse(value);
      return this;
    }
    /**
     * <code>optional .AcceptTosResponse acceptTosResponse = 22;</code>
     */
    public Builder clearAcceptTosResponse() {  copyOnWrite();
      instance.clearAcceptTosResponse();
      return this;
    }

    /**
     * <code>optional .AndroidCheckinResponse androidCheckinResponse = 26;</code>
     */
    public boolean hasAndroidCheckinResponse() {
      return instance.hasAndroidCheckinResponse();
    }
    /**
     * <code>optional .AndroidCheckinResponse androidCheckinResponse = 26;</code>
     */
    public com.github.yeriomin.playstore.api.AndroidCheckinResponse getAndroidCheckinResponse() {
      return instance.getAndroidCheckinResponse();
    }
    /**
     * <code>optional .AndroidCheckinResponse androidCheckinResponse = 26;</code>
     */
    public Builder setAndroidCheckinResponse(com.github.yeriomin.playstore.api.AndroidCheckinResponse value) {
      copyOnWrite();
      instance.setAndroidCheckinResponse(value);
      return this;
      }
    /**
     * <code>optional .AndroidCheckinResponse androidCheckinResponse = 26;</code>
     */
    public Builder setAndroidCheckinResponse(
        com.github.yeriomin.playstore.api.AndroidCheckinResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setAndroidCheckinResponse(builderForValue);
      return this;
    }
    /**
     * <code>optional .AndroidCheckinResponse androidCheckinResponse = 26;</code>
     */
    public Builder mergeAndroidCheckinResponse(com.github.yeriomin.playstore.api.AndroidCheckinResponse value) {
      copyOnWrite();
      instance.mergeAndroidCheckinResponse(value);
      return this;
    }
    /**
     * <code>optional .AndroidCheckinResponse androidCheckinResponse = 26;</code>
     */
    public Builder clearAndroidCheckinResponse() {  copyOnWrite();
      instance.clearAndroidCheckinResponse();
      return this;
    }

    /**
     * <code>optional .UploadDeviceConfigResponse uploadDeviceConfigResponse = 28;</code>
     */
    public boolean hasUploadDeviceConfigResponse() {
      return instance.hasUploadDeviceConfigResponse();
    }
    /**
     * <code>optional .UploadDeviceConfigResponse uploadDeviceConfigResponse = 28;</code>
     */
    public com.github.yeriomin.playstore.api.UploadDeviceConfigResponse getUploadDeviceConfigResponse() {
      return instance.getUploadDeviceConfigResponse();
    }
    /**
     * <code>optional .UploadDeviceConfigResponse uploadDeviceConfigResponse = 28;</code>
     */
    public Builder setUploadDeviceConfigResponse(com.github.yeriomin.playstore.api.UploadDeviceConfigResponse value) {
      copyOnWrite();
      instance.setUploadDeviceConfigResponse(value);
      return this;
      }
    /**
     * <code>optional .UploadDeviceConfigResponse uploadDeviceConfigResponse = 28;</code>
     */
    public Builder setUploadDeviceConfigResponse(
        com.github.yeriomin.playstore.api.UploadDeviceConfigResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setUploadDeviceConfigResponse(builderForValue);
      return this;
    }
    /**
     * <code>optional .UploadDeviceConfigResponse uploadDeviceConfigResponse = 28;</code>
     */
    public Builder mergeUploadDeviceConfigResponse(com.github.yeriomin.playstore.api.UploadDeviceConfigResponse value) {
      copyOnWrite();
      instance.mergeUploadDeviceConfigResponse(value);
      return this;
    }
    /**
     * <code>optional .UploadDeviceConfigResponse uploadDeviceConfigResponse = 28;</code>
     */
    public Builder clearUploadDeviceConfigResponse() {  copyOnWrite();
      instance.clearUploadDeviceConfigResponse();
      return this;
    }

    /**
     * <code>optional .SearchSuggestResponse searchSuggestResponse = 40;</code>
     */
    public boolean hasSearchSuggestResponse() {
      return instance.hasSearchSuggestResponse();
    }
    /**
     * <code>optional .SearchSuggestResponse searchSuggestResponse = 40;</code>
     */
    public com.github.yeriomin.playstore.api.SearchSuggestResponse getSearchSuggestResponse() {
      return instance.getSearchSuggestResponse();
    }
    /**
     * <code>optional .SearchSuggestResponse searchSuggestResponse = 40;</code>
     */
    public Builder setSearchSuggestResponse(com.github.yeriomin.playstore.api.SearchSuggestResponse value) {
      copyOnWrite();
      instance.setSearchSuggestResponse(value);
      return this;
      }
    /**
     * <code>optional .SearchSuggestResponse searchSuggestResponse = 40;</code>
     */
    public Builder setSearchSuggestResponse(
        com.github.yeriomin.playstore.api.SearchSuggestResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setSearchSuggestResponse(builderForValue);
      return this;
    }
    /**
     * <code>optional .SearchSuggestResponse searchSuggestResponse = 40;</code>
     */
    public Builder mergeSearchSuggestResponse(com.github.yeriomin.playstore.api.SearchSuggestResponse value) {
      copyOnWrite();
      instance.mergeSearchSuggestResponse(value);
      return this;
    }
    /**
     * <code>optional .SearchSuggestResponse searchSuggestResponse = 40;</code>
     */
    public Builder clearSearchSuggestResponse() {  copyOnWrite();
      instance.clearSearchSuggestResponse();
      return this;
    }

    /**
     * <code>optional .TestingProgramResponse testingProgramResponse = 80;</code>
     */
    public boolean hasTestingProgramResponse() {
      return instance.hasTestingProgramResponse();
    }
    /**
     * <code>optional .TestingProgramResponse testingProgramResponse = 80;</code>
     */
    public com.github.yeriomin.playstore.api.TestingProgramResponse getTestingProgramResponse() {
      return instance.getTestingProgramResponse();
    }
    /**
     * <code>optional .TestingProgramResponse testingProgramResponse = 80;</code>
     */
    public Builder setTestingProgramResponse(com.github.yeriomin.playstore.api.TestingProgramResponse value) {
      copyOnWrite();
      instance.setTestingProgramResponse(value);
      return this;
      }
    /**
     * <code>optional .TestingProgramResponse testingProgramResponse = 80;</code>
     */
    public Builder setTestingProgramResponse(
        com.github.yeriomin.playstore.api.TestingProgramResponse.Builder builderForValue) {
      copyOnWrite();
      instance.setTestingProgramResponse(builderForValue);
      return this;
    }
    /**
     * <code>optional .TestingProgramResponse testingProgramResponse = 80;</code>
     */
    public Builder mergeTestingProgramResponse(com.github.yeriomin.playstore.api.TestingProgramResponse value) {
      copyOnWrite();
      instance.mergeTestingProgramResponse(value);
      return this;
    }
    /**
     * <code>optional .TestingProgramResponse testingProgramResponse = 80;</code>
     */
    public Builder clearTestingProgramResponse() {  copyOnWrite();
      instance.clearTestingProgramResponse();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Payload)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.github.yeriomin.playstore.api.Payload();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.github.yeriomin.playstore.api.Payload other = (com.github.yeriomin.playstore.api.Payload) arg1;
        listResponse_ = visitor.visitMessage(listResponse_, other.listResponse_);
        detailsResponse_ = visitor.visitMessage(detailsResponse_, other.detailsResponse_);
        reviewResponse_ = visitor.visitMessage(reviewResponse_, other.reviewResponse_);
        buyResponse_ = visitor.visitMessage(buyResponse_, other.buyResponse_);
        searchResponse_ = visitor.visitMessage(searchResponse_, other.searchResponse_);
        tocResponse_ = visitor.visitMessage(tocResponse_, other.tocResponse_);
        browseResponse_ = visitor.visitMessage(browseResponse_, other.browseResponse_);
        purchaseStatusResponse_ = visitor.visitMessage(purchaseStatusResponse_, other.purchaseStatusResponse_);
        logResponse_ = visitor.visitString(
            hasLogResponse(), logResponse_,
            other.hasLogResponse(), other.logResponse_);
        flagContentResponse_ = visitor.visitString(
            hasFlagContentResponse(), flagContentResponse_,
            other.hasFlagContentResponse(), other.flagContentResponse_);
        bulkDetailsResponse_ = visitor.visitMessage(bulkDetailsResponse_, other.bulkDetailsResponse_);
        deliveryResponse_ = visitor.visitMessage(deliveryResponse_, other.deliveryResponse_);
        acceptTosResponse_ = visitor.visitMessage(acceptTosResponse_, other.acceptTosResponse_);
        androidCheckinResponse_ = visitor.visitMessage(androidCheckinResponse_, other.androidCheckinResponse_);
        uploadDeviceConfigResponse_ = visitor.visitMessage(uploadDeviceConfigResponse_, other.uploadDeviceConfigResponse_);
        searchSuggestResponse_ = visitor.visitMessage(searchSuggestResponse_, other.searchSuggestResponse_);
        testingProgramResponse_ = visitor.visitMessage(testingProgramResponse_, other.testingProgramResponse_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.github.yeriomin.playstore.api.ListResponse.Builder subBuilder = null;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                  subBuilder = listResponse_.toBuilder();
                }
                listResponse_ = input.readMessage(com.github.yeriomin.playstore.api.ListResponse.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(listResponse_);
                  listResponse_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000001;
                break;
              }
              case 18: {
                com.github.yeriomin.playstore.api.DetailsResponse.Builder subBuilder = null;
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                  subBuilder = detailsResponse_.toBuilder();
                }
                detailsResponse_ = input.readMessage(com.github.yeriomin.playstore.api.DetailsResponse.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(detailsResponse_);
                  detailsResponse_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000002;
                break;
              }
              case 26: {
                com.github.yeriomin.playstore.api.ReviewResponse.Builder subBuilder = null;
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                  subBuilder = reviewResponse_.toBuilder();
                }
                reviewResponse_ = input.readMessage(com.github.yeriomin.playstore.api.ReviewResponse.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(reviewResponse_);
                  reviewResponse_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000004;
                break;
              }
              case 34: {
                com.github.yeriomin.playstore.api.BuyResponse.Builder subBuilder = null;
                if (((bitField0_ & 0x00000008) == 0x00000008)) {
                  subBuilder = buyResponse_.toBuilder();
                }
                buyResponse_ = input.readMessage(com.github.yeriomin.playstore.api.BuyResponse.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(buyResponse_);
                  buyResponse_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000008;
                break;
              }
              case 42: {
                com.github.yeriomin.playstore.api.SearchResponse.Builder subBuilder = null;
                if (((bitField0_ & 0x00000010) == 0x00000010)) {
                  subBuilder = searchResponse_.toBuilder();
                }
                searchResponse_ = input.readMessage(com.github.yeriomin.playstore.api.SearchResponse.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(searchResponse_);
                  searchResponse_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000010;
                break;
              }
              case 50: {
                com.github.yeriomin.playstore.api.TocResponse.Builder subBuilder = null;
                if (((bitField0_ & 0x00000020) == 0x00000020)) {
                  subBuilder = tocResponse_.toBuilder();
                }
                tocResponse_ = input.readMessage(com.github.yeriomin.playstore.api.TocResponse.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(tocResponse_);
                  tocResponse_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000020;
                break;
              }
              case 58: {
                com.github.yeriomin.playstore.api.BrowseResponse.Builder subBuilder = null;
                if (((bitField0_ & 0x00000040) == 0x00000040)) {
                  subBuilder = browseResponse_.toBuilder();
                }
                browseResponse_ = input.readMessage(com.github.yeriomin.playstore.api.BrowseResponse.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(browseResponse_);
                  browseResponse_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000040;
                break;
              }
              case 66: {
                com.github.yeriomin.playstore.api.PurchaseStatusResponse.Builder subBuilder = null;
                if (((bitField0_ & 0x00000080) == 0x00000080)) {
                  subBuilder = purchaseStatusResponse_.toBuilder();
                }
                purchaseStatusResponse_ = input.readMessage(com.github.yeriomin.playstore.api.PurchaseStatusResponse.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(purchaseStatusResponse_);
                  purchaseStatusResponse_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000080;
                break;
              }
              case 82: {
                String s = input.readString();
                bitField0_ |= 0x00000100;
                logResponse_ = s;
                break;
              }
              case 106: {
                String s = input.readString();
                bitField0_ |= 0x00000200;
                flagContentResponse_ = s;
                break;
              }
              case 154: {
                com.github.yeriomin.playstore.api.BulkDetailsResponse.Builder subBuilder = null;
                if (((bitField0_ & 0x00000400) == 0x00000400)) {
                  subBuilder = bulkDetailsResponse_.toBuilder();
                }
                bulkDetailsResponse_ = input.readMessage(com.github.yeriomin.playstore.api.BulkDetailsResponse.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(bulkDetailsResponse_);
                  bulkDetailsResponse_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000400;
                break;
              }
              case 170: {
                com.github.yeriomin.playstore.api.DeliveryResponse.Builder subBuilder = null;
                if (((bitField0_ & 0x00000800) == 0x00000800)) {
                  subBuilder = deliveryResponse_.toBuilder();
                }
                deliveryResponse_ = input.readMessage(com.github.yeriomin.playstore.api.DeliveryResponse.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(deliveryResponse_);
                  deliveryResponse_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000800;
                break;
              }
              case 178: {
                com.github.yeriomin.playstore.api.AcceptTosResponse.Builder subBuilder = null;
                if (((bitField0_ & 0x00001000) == 0x00001000)) {
                  subBuilder = acceptTosResponse_.toBuilder();
                }
                acceptTosResponse_ = input.readMessage(com.github.yeriomin.playstore.api.AcceptTosResponse.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(acceptTosResponse_);
                  acceptTosResponse_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00001000;
                break;
              }
              case 210: {
                com.github.yeriomin.playstore.api.AndroidCheckinResponse.Builder subBuilder = null;
                if (((bitField0_ & 0x00002000) == 0x00002000)) {
                  subBuilder = androidCheckinResponse_.toBuilder();
                }
                androidCheckinResponse_ = input.readMessage(com.github.yeriomin.playstore.api.AndroidCheckinResponse.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(androidCheckinResponse_);
                  androidCheckinResponse_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00002000;
                break;
              }
              case 226: {
                com.github.yeriomin.playstore.api.UploadDeviceConfigResponse.Builder subBuilder = null;
                if (((bitField0_ & 0x00004000) == 0x00004000)) {
                  subBuilder = uploadDeviceConfigResponse_.toBuilder();
                }
                uploadDeviceConfigResponse_ = input.readMessage(com.github.yeriomin.playstore.api.UploadDeviceConfigResponse.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(uploadDeviceConfigResponse_);
                  uploadDeviceConfigResponse_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00004000;
                break;
              }
              case 322: {
                com.github.yeriomin.playstore.api.SearchSuggestResponse.Builder subBuilder = null;
                if (((bitField0_ & 0x00008000) == 0x00008000)) {
                  subBuilder = searchSuggestResponse_.toBuilder();
                }
                searchSuggestResponse_ = input.readMessage(com.github.yeriomin.playstore.api.SearchSuggestResponse.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(searchSuggestResponse_);
                  searchSuggestResponse_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00008000;
                break;
              }
              case 642: {
                com.github.yeriomin.playstore.api.TestingProgramResponse.Builder subBuilder = null;
                if (((bitField0_ & 0x00010000) == 0x00010000)) {
                  subBuilder = testingProgramResponse_.toBuilder();
                }
                testingProgramResponse_ = input.readMessage(com.github.yeriomin.playstore.api.TestingProgramResponse.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(testingProgramResponse_);
                  testingProgramResponse_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00010000;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.github.yeriomin.playstore.api.Payload.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:Payload)
  private static final com.github.yeriomin.playstore.api.Payload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Payload();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.github.yeriomin.playstore.api.Payload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Payload> PARSER;

  public static com.google.protobuf.Parser<Payload> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

