// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.api;

public interface PurchaseDeclinedDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PurchaseDeclinedData)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int32 reason = 1;</code>
   */
  boolean hasReason();
  /**
   * <code>optional int32 reason = 1;</code>
   */
  int getReason();

  /**
   * <code>optional bool showNotification = 2;</code>
   */
  boolean hasShowNotification();
  /**
   * <code>optional bool showNotification = 2;</code>
   */
  boolean getShowNotification();
}
