// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.api;

public interface VideoDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VideoDetails)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .VideoCredit credit = 1;</code>
   */
  java.util.List<com.github.yeriomin.playstore.api.VideoCredit> 
      getCreditList();
  /**
   * <code>repeated .VideoCredit credit = 1;</code>
   */
  com.github.yeriomin.playstore.api.VideoCredit getCredit(int index);
  /**
   * <code>repeated .VideoCredit credit = 1;</code>
   */
  int getCreditCount();

  /**
   * <code>optional string duration = 2;</code>
   */
  boolean hasDuration();
  /**
   * <code>optional string duration = 2;</code>
   */
  java.lang.String getDuration();
  /**
   * <code>optional string duration = 2;</code>
   */
  com.google.protobuf.ByteString
      getDurationBytes();

  /**
   * <code>optional string releaseDate = 3;</code>
   */
  boolean hasReleaseDate();
  /**
   * <code>optional string releaseDate = 3;</code>
   */
  java.lang.String getReleaseDate();
  /**
   * <code>optional string releaseDate = 3;</code>
   */
  com.google.protobuf.ByteString
      getReleaseDateBytes();

  /**
   * <code>optional string contentRating = 4;</code>
   */
  boolean hasContentRating();
  /**
   * <code>optional string contentRating = 4;</code>
   */
  java.lang.String getContentRating();
  /**
   * <code>optional string contentRating = 4;</code>
   */
  com.google.protobuf.ByteString
      getContentRatingBytes();

  /**
   * <code>optional int64 likes = 5;</code>
   */
  boolean hasLikes();
  /**
   * <code>optional int64 likes = 5;</code>
   */
  long getLikes();

  /**
   * <code>optional int64 dislikes = 6;</code>
   */
  boolean hasDislikes();
  /**
   * <code>optional int64 dislikes = 6;</code>
   */
  long getDislikes();

  /**
   * <code>repeated string genre = 7;</code>
   */
  java.util.List<String>
      getGenreList();
  /**
   * <code>repeated string genre = 7;</code>
   */
  int getGenreCount();
  /**
   * <code>repeated string genre = 7;</code>
   */
  java.lang.String getGenre(int index);
  /**
   * <code>repeated string genre = 7;</code>
   */
  com.google.protobuf.ByteString
      getGenreBytes(int index);

  /**
   * <code>repeated .Trailer trailer = 8;</code>
   */
  java.util.List<com.github.yeriomin.playstore.api.Trailer> 
      getTrailerList();
  /**
   * <code>repeated .Trailer trailer = 8;</code>
   */
  com.github.yeriomin.playstore.api.Trailer getTrailer(int index);
  /**
   * <code>repeated .Trailer trailer = 8;</code>
   */
  int getTrailerCount();

  /**
   * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
   */
  java.util.List<com.github.yeriomin.playstore.api.VideoRentalTerm> 
      getRentalTermList();
  /**
   * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
   */
  com.github.yeriomin.playstore.api.VideoRentalTerm getRentalTerm(int index);
  /**
   * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
   */
  int getRentalTermCount();
}
