// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface AndroidCheckinProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AndroidCheckinProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .AndroidBuildProto build = 1;</code>
   */
  boolean hasBuild();
  /**
   * <code>optional .AndroidBuildProto build = 1;</code>
   */
  com.github.yeriomin.playstoreapi.AndroidBuildProto getBuild();

  /**
   * <code>optional int64 lastCheckinMsec = 2;</code>
   */
  boolean hasLastCheckinMsec();
  /**
   * <code>optional int64 lastCheckinMsec = 2;</code>
   */
  long getLastCheckinMsec();

  /**
   * <code>repeated .AndroidEventProto event = 3;</code>
   */
  java.util.List<com.github.yeriomin.playstoreapi.AndroidEventProto> 
      getEventList();
  /**
   * <code>repeated .AndroidEventProto event = 3;</code>
   */
  com.github.yeriomin.playstoreapi.AndroidEventProto getEvent(int index);
  /**
   * <code>repeated .AndroidEventProto event = 3;</code>
   */
  int getEventCount();

  /**
   * <code>repeated .AndroidStatisticProto stat = 4;</code>
   */
  java.util.List<com.github.yeriomin.playstoreapi.AndroidStatisticProto> 
      getStatList();
  /**
   * <code>repeated .AndroidStatisticProto stat = 4;</code>
   */
  com.github.yeriomin.playstoreapi.AndroidStatisticProto getStat(int index);
  /**
   * <code>repeated .AndroidStatisticProto stat = 4;</code>
   */
  int getStatCount();

  /**
   * <code>repeated string requestedGroup = 5;</code>
   */
  java.util.List<String>
      getRequestedGroupList();
  /**
   * <code>repeated string requestedGroup = 5;</code>
   */
  int getRequestedGroupCount();
  /**
   * <code>repeated string requestedGroup = 5;</code>
   */
  java.lang.String getRequestedGroup(int index);
  /**
   * <code>repeated string requestedGroup = 5;</code>
   */
  com.google.protobuf.ByteString
      getRequestedGroupBytes(int index);

  /**
   * <code>optional string cellOperator = 6;</code>
   */
  boolean hasCellOperator();
  /**
   * <code>optional string cellOperator = 6;</code>
   */
  java.lang.String getCellOperator();
  /**
   * <code>optional string cellOperator = 6;</code>
   */
  com.google.protobuf.ByteString
      getCellOperatorBytes();

  /**
   * <code>optional string simOperator = 7;</code>
   */
  boolean hasSimOperator();
  /**
   * <code>optional string simOperator = 7;</code>
   */
  java.lang.String getSimOperator();
  /**
   * <code>optional string simOperator = 7;</code>
   */
  com.google.protobuf.ByteString
      getSimOperatorBytes();

  /**
   * <code>optional string roaming = 8;</code>
   */
  boolean hasRoaming();
  /**
   * <code>optional string roaming = 8;</code>
   */
  java.lang.String getRoaming();
  /**
   * <code>optional string roaming = 8;</code>
   */
  com.google.protobuf.ByteString
      getRoamingBytes();

  /**
   * <code>optional int32 userNumber = 9;</code>
   */
  boolean hasUserNumber();
  /**
   * <code>optional int32 userNumber = 9;</code>
   */
  int getUserNumber();
}
