// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstoreapi;

/**
 * Protobuf type {@code BrowseLink}
 */
public  final class BrowseLink extends
    com.google.protobuf.GeneratedMessageLite<
        BrowseLink, BrowseLink.Builder> implements
    // @@protoc_insertion_point(message_implements:BrowseLink)
    BrowseLinkOrBuilder {
  private BrowseLink() {
    name_ = "";
    dataUrl_ = "";
  }
  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <code>optional string name = 1;</code>
   */
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string name = 1;</code>
   */
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>optional string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>optional string name = 1;</code>
   */
  private void setName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    name_ = value;
  }
  /**
   * <code>optional string name = 1;</code>
   */
  private void clearName() {
    bitField0_ = (bitField0_ & ~0x00000001);
    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>optional string name = 1;</code>
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    name_ = value.toStringUtf8();
  }

  public static final int DATAURL_FIELD_NUMBER = 3;
  private java.lang.String dataUrl_;
  /**
   * <code>optional string dataUrl = 3;</code>
   */
  public boolean hasDataUrl() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string dataUrl = 3;</code>
   */
  public java.lang.String getDataUrl() {
    return dataUrl_;
  }
  /**
   * <code>optional string dataUrl = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDataUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(dataUrl_);
  }
  /**
   * <code>optional string dataUrl = 3;</code>
   */
  private void setDataUrl(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    dataUrl_ = value;
  }
  /**
   * <code>optional string dataUrl = 3;</code>
   */
  private void clearDataUrl() {
    bitField0_ = (bitField0_ & ~0x00000002);
    dataUrl_ = getDefaultInstance().getDataUrl();
  }
  /**
   * <code>optional string dataUrl = 3;</code>
   */
  private void setDataUrlBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    dataUrl_ = value.toStringUtf8();
  }

  public static final int ICON_FIELD_NUMBER = 5;
  private com.github.yeriomin.playstoreapi.Image icon_;
  /**
   * <code>optional .Image icon = 5;</code>
   */
  public boolean hasIcon() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional .Image icon = 5;</code>
   */
  public com.github.yeriomin.playstoreapi.Image getIcon() {
    return icon_ == null ? com.github.yeriomin.playstoreapi.Image.getDefaultInstance() : icon_;
  }
  /**
   * <code>optional .Image icon = 5;</code>
   */
  private void setIcon(com.github.yeriomin.playstoreapi.Image value) {
    if (value == null) {
      throw new NullPointerException();
    }
    icon_ = value;
    bitField0_ |= 0x00000004;
    }
  /**
   * <code>optional .Image icon = 5;</code>
   */
  private void setIcon(
      com.github.yeriomin.playstoreapi.Image.Builder builderForValue) {
    icon_ = builderForValue.build();
    bitField0_ |= 0x00000004;
  }
  /**
   * <code>optional .Image icon = 5;</code>
   */
  private void mergeIcon(com.github.yeriomin.playstoreapi.Image value) {
    if (icon_ != null &&
        icon_ != com.github.yeriomin.playstoreapi.Image.getDefaultInstance()) {
      icon_ =
        com.github.yeriomin.playstoreapi.Image.newBuilder(icon_).mergeFrom(value).buildPartial();
    } else {
      icon_ = value;
    }
    bitField0_ |= 0x00000004;
  }
  /**
   * <code>optional .Image icon = 5;</code>
   */
  private void clearIcon() {  icon_ = null;
    bitField0_ = (bitField0_ & ~0x00000004);
  }

  public static final int UNKNOWNCATEGORYCONTAINER_FIELD_NUMBER = 4;
  private com.github.yeriomin.playstoreapi.UnknownCategoryContainer unknownCategoryContainer_;
  /**
   * <code>optional .UnknownCategoryContainer unknownCategoryContainer = 4;</code>
   */
  public boolean hasUnknownCategoryContainer() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional .UnknownCategoryContainer unknownCategoryContainer = 4;</code>
   */
  public com.github.yeriomin.playstoreapi.UnknownCategoryContainer getUnknownCategoryContainer() {
    return unknownCategoryContainer_ == null ? com.github.yeriomin.playstoreapi.UnknownCategoryContainer.getDefaultInstance() : unknownCategoryContainer_;
  }
  /**
   * <code>optional .UnknownCategoryContainer unknownCategoryContainer = 4;</code>
   */
  private void setUnknownCategoryContainer(com.github.yeriomin.playstoreapi.UnknownCategoryContainer value) {
    if (value == null) {
      throw new NullPointerException();
    }
    unknownCategoryContainer_ = value;
    bitField0_ |= 0x00000008;
    }
  /**
   * <code>optional .UnknownCategoryContainer unknownCategoryContainer = 4;</code>
   */
  private void setUnknownCategoryContainer(
      com.github.yeriomin.playstoreapi.UnknownCategoryContainer.Builder builderForValue) {
    unknownCategoryContainer_ = builderForValue.build();
    bitField0_ |= 0x00000008;
  }
  /**
   * <code>optional .UnknownCategoryContainer unknownCategoryContainer = 4;</code>
   */
  private void mergeUnknownCategoryContainer(com.github.yeriomin.playstoreapi.UnknownCategoryContainer value) {
    if (unknownCategoryContainer_ != null &&
        unknownCategoryContainer_ != com.github.yeriomin.playstoreapi.UnknownCategoryContainer.getDefaultInstance()) {
      unknownCategoryContainer_ =
        com.github.yeriomin.playstoreapi.UnknownCategoryContainer.newBuilder(unknownCategoryContainer_).mergeFrom(value).buildPartial();
    } else {
      unknownCategoryContainer_ = value;
    }
    bitField0_ |= 0x00000008;
  }
  /**
   * <code>optional .UnknownCategoryContainer unknownCategoryContainer = 4;</code>
   */
  private void clearUnknownCategoryContainer() {  unknownCategoryContainer_ = null;
    bitField0_ = (bitField0_ & ~0x00000008);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeString(1, getName());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeString(3, getDataUrl());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeMessage(4, getUnknownCategoryContainer());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeMessage(5, getIcon());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getName());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getDataUrl());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getUnknownCategoryContainer());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getIcon());
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static com.github.yeriomin.playstoreapi.BrowseLink parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstoreapi.BrowseLink parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.BrowseLink parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstoreapi.BrowseLink parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.BrowseLink parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstoreapi.BrowseLink parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.BrowseLink parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstoreapi.BrowseLink parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.BrowseLink parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstoreapi.BrowseLink parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.yeriomin.playstoreapi.BrowseLink prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code BrowseLink}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.github.yeriomin.playstoreapi.BrowseLink, Builder> implements
      // @@protoc_insertion_point(builder_implements:BrowseLink)
      com.github.yeriomin.playstoreapi.BrowseLinkOrBuilder {
    // Construct using com.github.yeriomin.playstoreapi.BrowseLink.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return instance.hasName();
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>optional string dataUrl = 3;</code>
     */
    public boolean hasDataUrl() {
      return instance.hasDataUrl();
    }
    /**
     * <code>optional string dataUrl = 3;</code>
     */
    public java.lang.String getDataUrl() {
      return instance.getDataUrl();
    }
    /**
     * <code>optional string dataUrl = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataUrlBytes() {
      return instance.getDataUrlBytes();
    }
    /**
     * <code>optional string dataUrl = 3;</code>
     */
    public Builder setDataUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setDataUrl(value);
      return this;
    }
    /**
     * <code>optional string dataUrl = 3;</code>
     */
    public Builder clearDataUrl() {
      copyOnWrite();
      instance.clearDataUrl();
      return this;
    }
    /**
     * <code>optional string dataUrl = 3;</code>
     */
    public Builder setDataUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDataUrlBytes(value);
      return this;
    }

    /**
     * <code>optional .Image icon = 5;</code>
     */
    public boolean hasIcon() {
      return instance.hasIcon();
    }
    /**
     * <code>optional .Image icon = 5;</code>
     */
    public com.github.yeriomin.playstoreapi.Image getIcon() {
      return instance.getIcon();
    }
    /**
     * <code>optional .Image icon = 5;</code>
     */
    public Builder setIcon(com.github.yeriomin.playstoreapi.Image value) {
      copyOnWrite();
      instance.setIcon(value);
      return this;
      }
    /**
     * <code>optional .Image icon = 5;</code>
     */
    public Builder setIcon(
        com.github.yeriomin.playstoreapi.Image.Builder builderForValue) {
      copyOnWrite();
      instance.setIcon(builderForValue);
      return this;
    }
    /**
     * <code>optional .Image icon = 5;</code>
     */
    public Builder mergeIcon(com.github.yeriomin.playstoreapi.Image value) {
      copyOnWrite();
      instance.mergeIcon(value);
      return this;
    }
    /**
     * <code>optional .Image icon = 5;</code>
     */
    public Builder clearIcon() {  copyOnWrite();
      instance.clearIcon();
      return this;
    }

    /**
     * <code>optional .UnknownCategoryContainer unknownCategoryContainer = 4;</code>
     */
    public boolean hasUnknownCategoryContainer() {
      return instance.hasUnknownCategoryContainer();
    }
    /**
     * <code>optional .UnknownCategoryContainer unknownCategoryContainer = 4;</code>
     */
    public com.github.yeriomin.playstoreapi.UnknownCategoryContainer getUnknownCategoryContainer() {
      return instance.getUnknownCategoryContainer();
    }
    /**
     * <code>optional .UnknownCategoryContainer unknownCategoryContainer = 4;</code>
     */
    public Builder setUnknownCategoryContainer(com.github.yeriomin.playstoreapi.UnknownCategoryContainer value) {
      copyOnWrite();
      instance.setUnknownCategoryContainer(value);
      return this;
      }
    /**
     * <code>optional .UnknownCategoryContainer unknownCategoryContainer = 4;</code>
     */
    public Builder setUnknownCategoryContainer(
        com.github.yeriomin.playstoreapi.UnknownCategoryContainer.Builder builderForValue) {
      copyOnWrite();
      instance.setUnknownCategoryContainer(builderForValue);
      return this;
    }
    /**
     * <code>optional .UnknownCategoryContainer unknownCategoryContainer = 4;</code>
     */
    public Builder mergeUnknownCategoryContainer(com.github.yeriomin.playstoreapi.UnknownCategoryContainer value) {
      copyOnWrite();
      instance.mergeUnknownCategoryContainer(value);
      return this;
    }
    /**
     * <code>optional .UnknownCategoryContainer unknownCategoryContainer = 4;</code>
     */
    public Builder clearUnknownCategoryContainer() {  copyOnWrite();
      instance.clearUnknownCategoryContainer();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:BrowseLink)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.github.yeriomin.playstoreapi.BrowseLink();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.github.yeriomin.playstoreapi.BrowseLink other = (com.github.yeriomin.playstoreapi.BrowseLink) arg1;
        name_ = visitor.visitString(
            hasName(), name_,
            other.hasName(), other.name_);
        dataUrl_ = visitor.visitString(
            hasDataUrl(), dataUrl_,
            other.hasDataUrl(), other.dataUrl_);
        icon_ = visitor.visitMessage(icon_, other.icon_);
        unknownCategoryContainer_ = visitor.visitMessage(unknownCategoryContainer_, other.unknownCategoryContainer_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readString();
                bitField0_ |= 0x00000001;
                name_ = s;
                break;
              }
              case 26: {
                String s = input.readString();
                bitField0_ |= 0x00000002;
                dataUrl_ = s;
                break;
              }
              case 34: {
                com.github.yeriomin.playstoreapi.UnknownCategoryContainer.Builder subBuilder = null;
                if (((bitField0_ & 0x00000008) == 0x00000008)) {
                  subBuilder = unknownCategoryContainer_.toBuilder();
                }
                unknownCategoryContainer_ = input.readMessage(com.github.yeriomin.playstoreapi.UnknownCategoryContainer.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(unknownCategoryContainer_);
                  unknownCategoryContainer_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000008;
                break;
              }
              case 42: {
                com.github.yeriomin.playstoreapi.Image.Builder subBuilder = null;
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                  subBuilder = icon_.toBuilder();
                }
                icon_ = input.readMessage(com.github.yeriomin.playstoreapi.Image.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(icon_);
                  icon_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000004;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.github.yeriomin.playstoreapi.BrowseLink.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:BrowseLink)
  private static final com.github.yeriomin.playstoreapi.BrowseLink DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BrowseLink();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.github.yeriomin.playstoreapi.BrowseLink getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<BrowseLink> PARSER;

  public static com.google.protobuf.Parser<BrowseLink> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

