// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstoreapi;

/**
 * Protobuf type {@code Bucket}
 */
public  final class Bucket extends
    com.google.protobuf.GeneratedMessageLite<
        Bucket, Bucket.Builder> implements
    // @@protoc_insertion_point(message_implements:Bucket)
    BucketOrBuilder {
  private Bucket() {
    document_ = emptyProtobufList();
    title_ = "";
    iconUrl_ = "";
    fullContentsUrl_ = "";
    analyticsCookie_ = "";
    fullContentsListUrl_ = "";
    nextPageUrl_ = "";
  }
  private int bitField0_;
  public static final int DOCUMENT_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.github.yeriomin.playstoreapi.DocV1> document_;
  /**
   * <code>repeated .DocV1 document = 1;</code>
   */
  public java.util.List<com.github.yeriomin.playstoreapi.DocV1> getDocumentList() {
    return document_;
  }
  /**
   * <code>repeated .DocV1 document = 1;</code>
   */
  public java.util.List<? extends com.github.yeriomin.playstoreapi.DocV1OrBuilder> 
      getDocumentOrBuilderList() {
    return document_;
  }
  /**
   * <code>repeated .DocV1 document = 1;</code>
   */
  public int getDocumentCount() {
    return document_.size();
  }
  /**
   * <code>repeated .DocV1 document = 1;</code>
   */
  public com.github.yeriomin.playstoreapi.DocV1 getDocument(int index) {
    return document_.get(index);
  }
  /**
   * <code>repeated .DocV1 document = 1;</code>
   */
  public com.github.yeriomin.playstoreapi.DocV1OrBuilder getDocumentOrBuilder(
      int index) {
    return document_.get(index);
  }
  private void ensureDocumentIsMutable() {
    if (!document_.isModifiable()) {
      document_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(document_);
     }
  }

  /**
   * <code>repeated .DocV1 document = 1;</code>
   */
  private void setDocument(
      int index, com.github.yeriomin.playstoreapi.DocV1 value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureDocumentIsMutable();
    document_.set(index, value);
  }
  /**
   * <code>repeated .DocV1 document = 1;</code>
   */
  private void setDocument(
      int index, com.github.yeriomin.playstoreapi.DocV1.Builder builderForValue) {
    ensureDocumentIsMutable();
    document_.set(index, builderForValue.build());
  }
  /**
   * <code>repeated .DocV1 document = 1;</code>
   */
  private void addDocument(com.github.yeriomin.playstoreapi.DocV1 value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureDocumentIsMutable();
    document_.add(value);
  }
  /**
   * <code>repeated .DocV1 document = 1;</code>
   */
  private void addDocument(
      int index, com.github.yeriomin.playstoreapi.DocV1 value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureDocumentIsMutable();
    document_.add(index, value);
  }
  /**
   * <code>repeated .DocV1 document = 1;</code>
   */
  private void addDocument(
      com.github.yeriomin.playstoreapi.DocV1.Builder builderForValue) {
    ensureDocumentIsMutable();
    document_.add(builderForValue.build());
  }
  /**
   * <code>repeated .DocV1 document = 1;</code>
   */
  private void addDocument(
      int index, com.github.yeriomin.playstoreapi.DocV1.Builder builderForValue) {
    ensureDocumentIsMutable();
    document_.add(index, builderForValue.build());
  }
  /**
   * <code>repeated .DocV1 document = 1;</code>
   */
  private void addAllDocument(
      java.lang.Iterable<? extends com.github.yeriomin.playstoreapi.DocV1> values) {
    ensureDocumentIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, document_);
  }
  /**
   * <code>repeated .DocV1 document = 1;</code>
   */
  private void clearDocument() {
    document_ = emptyProtobufList();
  }
  /**
   * <code>repeated .DocV1 document = 1;</code>
   */
  private void removeDocument(int index) {
    ensureDocumentIsMutable();
    document_.remove(index);
  }

  public static final int MULTICORPUS_FIELD_NUMBER = 2;
  private boolean multiCorpus_;
  /**
   * <code>optional bool multiCorpus = 2;</code>
   */
  public boolean hasMultiCorpus() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional bool multiCorpus = 2;</code>
   */
  public boolean getMultiCorpus() {
    return multiCorpus_;
  }
  /**
   * <code>optional bool multiCorpus = 2;</code>
   */
  private void setMultiCorpus(boolean value) {
    bitField0_ |= 0x00000001;
    multiCorpus_ = value;
  }
  /**
   * <code>optional bool multiCorpus = 2;</code>
   */
  private void clearMultiCorpus() {
    bitField0_ = (bitField0_ & ~0x00000001);
    multiCorpus_ = false;
  }

  public static final int TITLE_FIELD_NUMBER = 3;
  private java.lang.String title_;
  /**
   * <code>optional string title = 3;</code>
   */
  public boolean hasTitle() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string title = 3;</code>
   */
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <code>optional string title = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <code>optional string title = 3;</code>
   */
  private void setTitle(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    title_ = value;
  }
  /**
   * <code>optional string title = 3;</code>
   */
  private void clearTitle() {
    bitField0_ = (bitField0_ & ~0x00000002);
    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <code>optional string title = 3;</code>
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    title_ = value.toStringUtf8();
  }

  public static final int ICONURL_FIELD_NUMBER = 4;
  private java.lang.String iconUrl_;
  /**
   * <code>optional string iconUrl = 4;</code>
   */
  public boolean hasIconUrl() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string iconUrl = 4;</code>
   */
  public java.lang.String getIconUrl() {
    return iconUrl_;
  }
  /**
   * <code>optional string iconUrl = 4;</code>
   */
  public com.google.protobuf.ByteString
      getIconUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(iconUrl_);
  }
  /**
   * <code>optional string iconUrl = 4;</code>
   */
  private void setIconUrl(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    iconUrl_ = value;
  }
  /**
   * <code>optional string iconUrl = 4;</code>
   */
  private void clearIconUrl() {
    bitField0_ = (bitField0_ & ~0x00000004);
    iconUrl_ = getDefaultInstance().getIconUrl();
  }
  /**
   * <code>optional string iconUrl = 4;</code>
   */
  private void setIconUrlBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    iconUrl_ = value.toStringUtf8();
  }

  public static final int FULLCONTENTSURL_FIELD_NUMBER = 5;
  private java.lang.String fullContentsUrl_;
  /**
   * <code>optional string fullContentsUrl = 5;</code>
   */
  public boolean hasFullContentsUrl() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional string fullContentsUrl = 5;</code>
   */
  public java.lang.String getFullContentsUrl() {
    return fullContentsUrl_;
  }
  /**
   * <code>optional string fullContentsUrl = 5;</code>
   */
  public com.google.protobuf.ByteString
      getFullContentsUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(fullContentsUrl_);
  }
  /**
   * <code>optional string fullContentsUrl = 5;</code>
   */
  private void setFullContentsUrl(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
    fullContentsUrl_ = value;
  }
  /**
   * <code>optional string fullContentsUrl = 5;</code>
   */
  private void clearFullContentsUrl() {
    bitField0_ = (bitField0_ & ~0x00000008);
    fullContentsUrl_ = getDefaultInstance().getFullContentsUrl();
  }
  /**
   * <code>optional string fullContentsUrl = 5;</code>
   */
  private void setFullContentsUrlBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
    fullContentsUrl_ = value.toStringUtf8();
  }

  public static final int RELEVANCE_FIELD_NUMBER = 6;
  private double relevance_;
  /**
   * <code>optional double relevance = 6;</code>
   */
  public boolean hasRelevance() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional double relevance = 6;</code>
   */
  public double getRelevance() {
    return relevance_;
  }
  /**
   * <code>optional double relevance = 6;</code>
   */
  private void setRelevance(double value) {
    bitField0_ |= 0x00000010;
    relevance_ = value;
  }
  /**
   * <code>optional double relevance = 6;</code>
   */
  private void clearRelevance() {
    bitField0_ = (bitField0_ & ~0x00000010);
    relevance_ = 0D;
  }

  public static final int ESTIMATEDRESULTS_FIELD_NUMBER = 7;
  private long estimatedResults_;
  /**
   * <code>optional int64 estimatedResults = 7;</code>
   */
  public boolean hasEstimatedResults() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional int64 estimatedResults = 7;</code>
   */
  public long getEstimatedResults() {
    return estimatedResults_;
  }
  /**
   * <code>optional int64 estimatedResults = 7;</code>
   */
  private void setEstimatedResults(long value) {
    bitField0_ |= 0x00000020;
    estimatedResults_ = value;
  }
  /**
   * <code>optional int64 estimatedResults = 7;</code>
   */
  private void clearEstimatedResults() {
    bitField0_ = (bitField0_ & ~0x00000020);
    estimatedResults_ = 0L;
  }

  public static final int ANALYTICSCOOKIE_FIELD_NUMBER = 8;
  private java.lang.String analyticsCookie_;
  /**
   * <code>optional string analyticsCookie = 8;</code>
   */
  public boolean hasAnalyticsCookie() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional string analyticsCookie = 8;</code>
   */
  public java.lang.String getAnalyticsCookie() {
    return analyticsCookie_;
  }
  /**
   * <code>optional string analyticsCookie = 8;</code>
   */
  public com.google.protobuf.ByteString
      getAnalyticsCookieBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(analyticsCookie_);
  }
  /**
   * <code>optional string analyticsCookie = 8;</code>
   */
  private void setAnalyticsCookie(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
    analyticsCookie_ = value;
  }
  /**
   * <code>optional string analyticsCookie = 8;</code>
   */
  private void clearAnalyticsCookie() {
    bitField0_ = (bitField0_ & ~0x00000040);
    analyticsCookie_ = getDefaultInstance().getAnalyticsCookie();
  }
  /**
   * <code>optional string analyticsCookie = 8;</code>
   */
  private void setAnalyticsCookieBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
    analyticsCookie_ = value.toStringUtf8();
  }

  public static final int FULLCONTENTSLISTURL_FIELD_NUMBER = 9;
  private java.lang.String fullContentsListUrl_;
  /**
   * <code>optional string fullContentsListUrl = 9;</code>
   */
  public boolean hasFullContentsListUrl() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional string fullContentsListUrl = 9;</code>
   */
  public java.lang.String getFullContentsListUrl() {
    return fullContentsListUrl_;
  }
  /**
   * <code>optional string fullContentsListUrl = 9;</code>
   */
  public com.google.protobuf.ByteString
      getFullContentsListUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(fullContentsListUrl_);
  }
  /**
   * <code>optional string fullContentsListUrl = 9;</code>
   */
  private void setFullContentsListUrl(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
    fullContentsListUrl_ = value;
  }
  /**
   * <code>optional string fullContentsListUrl = 9;</code>
   */
  private void clearFullContentsListUrl() {
    bitField0_ = (bitField0_ & ~0x00000080);
    fullContentsListUrl_ = getDefaultInstance().getFullContentsListUrl();
  }
  /**
   * <code>optional string fullContentsListUrl = 9;</code>
   */
  private void setFullContentsListUrlBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
    fullContentsListUrl_ = value.toStringUtf8();
  }

  public static final int NEXTPAGEURL_FIELD_NUMBER = 10;
  private java.lang.String nextPageUrl_;
  /**
   * <code>optional string nextPageUrl = 10;</code>
   */
  public boolean hasNextPageUrl() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional string nextPageUrl = 10;</code>
   */
  public java.lang.String getNextPageUrl() {
    return nextPageUrl_;
  }
  /**
   * <code>optional string nextPageUrl = 10;</code>
   */
  public com.google.protobuf.ByteString
      getNextPageUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(nextPageUrl_);
  }
  /**
   * <code>optional string nextPageUrl = 10;</code>
   */
  private void setNextPageUrl(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
    nextPageUrl_ = value;
  }
  /**
   * <code>optional string nextPageUrl = 10;</code>
   */
  private void clearNextPageUrl() {
    bitField0_ = (bitField0_ & ~0x00000100);
    nextPageUrl_ = getDefaultInstance().getNextPageUrl();
  }
  /**
   * <code>optional string nextPageUrl = 10;</code>
   */
  private void setNextPageUrlBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
    nextPageUrl_ = value.toStringUtf8();
  }

  public static final int ORDERED_FIELD_NUMBER = 11;
  private boolean ordered_;
  /**
   * <code>optional bool ordered = 11;</code>
   */
  public boolean hasOrdered() {
    return ((bitField0_ & 0x00000200) == 0x00000200);
  }
  /**
   * <code>optional bool ordered = 11;</code>
   */
  public boolean getOrdered() {
    return ordered_;
  }
  /**
   * <code>optional bool ordered = 11;</code>
   */
  private void setOrdered(boolean value) {
    bitField0_ |= 0x00000200;
    ordered_ = value;
  }
  /**
   * <code>optional bool ordered = 11;</code>
   */
  private void clearOrdered() {
    bitField0_ = (bitField0_ & ~0x00000200);
    ordered_ = false;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < document_.size(); i++) {
      output.writeMessage(1, document_.get(i));
    }
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBool(2, multiCorpus_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeString(3, getTitle());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeString(4, getIconUrl());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeString(5, getFullContentsUrl());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeDouble(6, relevance_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeInt64(7, estimatedResults_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeString(8, getAnalyticsCookie());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeString(9, getFullContentsListUrl());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeString(10, getNextPageUrl());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      output.writeBool(11, ordered_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < document_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, document_.get(i));
    }
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, multiCorpus_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getTitle());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(4, getIconUrl());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(5, getFullContentsUrl());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, relevance_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, estimatedResults_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(8, getAnalyticsCookie());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(9, getFullContentsListUrl());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(10, getNextPageUrl());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, ordered_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static com.github.yeriomin.playstoreapi.Bucket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstoreapi.Bucket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.Bucket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstoreapi.Bucket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.Bucket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstoreapi.Bucket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.Bucket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstoreapi.Bucket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.Bucket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstoreapi.Bucket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.yeriomin.playstoreapi.Bucket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code Bucket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.github.yeriomin.playstoreapi.Bucket, Builder> implements
      // @@protoc_insertion_point(builder_implements:Bucket)
      com.github.yeriomin.playstoreapi.BucketOrBuilder {
    // Construct using com.github.yeriomin.playstoreapi.Bucket.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .DocV1 document = 1;</code>
     */
    public java.util.List<com.github.yeriomin.playstoreapi.DocV1> getDocumentList() {
      return java.util.Collections.unmodifiableList(
          instance.getDocumentList());
    }
    /**
     * <code>repeated .DocV1 document = 1;</code>
     */
    public int getDocumentCount() {
      return instance.getDocumentCount();
    }/**
     * <code>repeated .DocV1 document = 1;</code>
     */
    public com.github.yeriomin.playstoreapi.DocV1 getDocument(int index) {
      return instance.getDocument(index);
    }
    /**
     * <code>repeated .DocV1 document = 1;</code>
     */
    public Builder setDocument(
        int index, com.github.yeriomin.playstoreapi.DocV1 value) {
      copyOnWrite();
      instance.setDocument(index, value);
      return this;
    }
    /**
     * <code>repeated .DocV1 document = 1;</code>
     */
    public Builder setDocument(
        int index, com.github.yeriomin.playstoreapi.DocV1.Builder builderForValue) {
      copyOnWrite();
      instance.setDocument(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .DocV1 document = 1;</code>
     */
    public Builder addDocument(com.github.yeriomin.playstoreapi.DocV1 value) {
      copyOnWrite();
      instance.addDocument(value);
      return this;
    }
    /**
     * <code>repeated .DocV1 document = 1;</code>
     */
    public Builder addDocument(
        int index, com.github.yeriomin.playstoreapi.DocV1 value) {
      copyOnWrite();
      instance.addDocument(index, value);
      return this;
    }
    /**
     * <code>repeated .DocV1 document = 1;</code>
     */
    public Builder addDocument(
        com.github.yeriomin.playstoreapi.DocV1.Builder builderForValue) {
      copyOnWrite();
      instance.addDocument(builderForValue);
      return this;
    }
    /**
     * <code>repeated .DocV1 document = 1;</code>
     */
    public Builder addDocument(
        int index, com.github.yeriomin.playstoreapi.DocV1.Builder builderForValue) {
      copyOnWrite();
      instance.addDocument(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .DocV1 document = 1;</code>
     */
    public Builder addAllDocument(
        java.lang.Iterable<? extends com.github.yeriomin.playstoreapi.DocV1> values) {
      copyOnWrite();
      instance.addAllDocument(values);
      return this;
    }
    /**
     * <code>repeated .DocV1 document = 1;</code>
     */
    public Builder clearDocument() {
      copyOnWrite();
      instance.clearDocument();
      return this;
    }
    /**
     * <code>repeated .DocV1 document = 1;</code>
     */
    public Builder removeDocument(int index) {
      copyOnWrite();
      instance.removeDocument(index);
      return this;
    }

    /**
     * <code>optional bool multiCorpus = 2;</code>
     */
    public boolean hasMultiCorpus() {
      return instance.hasMultiCorpus();
    }
    /**
     * <code>optional bool multiCorpus = 2;</code>
     */
    public boolean getMultiCorpus() {
      return instance.getMultiCorpus();
    }
    /**
     * <code>optional bool multiCorpus = 2;</code>
     */
    public Builder setMultiCorpus(boolean value) {
      copyOnWrite();
      instance.setMultiCorpus(value);
      return this;
    }
    /**
     * <code>optional bool multiCorpus = 2;</code>
     */
    public Builder clearMultiCorpus() {
      copyOnWrite();
      instance.clearMultiCorpus();
      return this;
    }

    /**
     * <code>optional string title = 3;</code>
     */
    public boolean hasTitle() {
      return instance.hasTitle();
    }
    /**
     * <code>optional string title = 3;</code>
     */
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <code>optional string title = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <code>optional string title = 3;</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <code>optional string title = 3;</code>
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <code>optional string title = 3;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <code>optional string iconUrl = 4;</code>
     */
    public boolean hasIconUrl() {
      return instance.hasIconUrl();
    }
    /**
     * <code>optional string iconUrl = 4;</code>
     */
    public java.lang.String getIconUrl() {
      return instance.getIconUrl();
    }
    /**
     * <code>optional string iconUrl = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIconUrlBytes() {
      return instance.getIconUrlBytes();
    }
    /**
     * <code>optional string iconUrl = 4;</code>
     */
    public Builder setIconUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setIconUrl(value);
      return this;
    }
    /**
     * <code>optional string iconUrl = 4;</code>
     */
    public Builder clearIconUrl() {
      copyOnWrite();
      instance.clearIconUrl();
      return this;
    }
    /**
     * <code>optional string iconUrl = 4;</code>
     */
    public Builder setIconUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIconUrlBytes(value);
      return this;
    }

    /**
     * <code>optional string fullContentsUrl = 5;</code>
     */
    public boolean hasFullContentsUrl() {
      return instance.hasFullContentsUrl();
    }
    /**
     * <code>optional string fullContentsUrl = 5;</code>
     */
    public java.lang.String getFullContentsUrl() {
      return instance.getFullContentsUrl();
    }
    /**
     * <code>optional string fullContentsUrl = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFullContentsUrlBytes() {
      return instance.getFullContentsUrlBytes();
    }
    /**
     * <code>optional string fullContentsUrl = 5;</code>
     */
    public Builder setFullContentsUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setFullContentsUrl(value);
      return this;
    }
    /**
     * <code>optional string fullContentsUrl = 5;</code>
     */
    public Builder clearFullContentsUrl() {
      copyOnWrite();
      instance.clearFullContentsUrl();
      return this;
    }
    /**
     * <code>optional string fullContentsUrl = 5;</code>
     */
    public Builder setFullContentsUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFullContentsUrlBytes(value);
      return this;
    }

    /**
     * <code>optional double relevance = 6;</code>
     */
    public boolean hasRelevance() {
      return instance.hasRelevance();
    }
    /**
     * <code>optional double relevance = 6;</code>
     */
    public double getRelevance() {
      return instance.getRelevance();
    }
    /**
     * <code>optional double relevance = 6;</code>
     */
    public Builder setRelevance(double value) {
      copyOnWrite();
      instance.setRelevance(value);
      return this;
    }
    /**
     * <code>optional double relevance = 6;</code>
     */
    public Builder clearRelevance() {
      copyOnWrite();
      instance.clearRelevance();
      return this;
    }

    /**
     * <code>optional int64 estimatedResults = 7;</code>
     */
    public boolean hasEstimatedResults() {
      return instance.hasEstimatedResults();
    }
    /**
     * <code>optional int64 estimatedResults = 7;</code>
     */
    public long getEstimatedResults() {
      return instance.getEstimatedResults();
    }
    /**
     * <code>optional int64 estimatedResults = 7;</code>
     */
    public Builder setEstimatedResults(long value) {
      copyOnWrite();
      instance.setEstimatedResults(value);
      return this;
    }
    /**
     * <code>optional int64 estimatedResults = 7;</code>
     */
    public Builder clearEstimatedResults() {
      copyOnWrite();
      instance.clearEstimatedResults();
      return this;
    }

    /**
     * <code>optional string analyticsCookie = 8;</code>
     */
    public boolean hasAnalyticsCookie() {
      return instance.hasAnalyticsCookie();
    }
    /**
     * <code>optional string analyticsCookie = 8;</code>
     */
    public java.lang.String getAnalyticsCookie() {
      return instance.getAnalyticsCookie();
    }
    /**
     * <code>optional string analyticsCookie = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAnalyticsCookieBytes() {
      return instance.getAnalyticsCookieBytes();
    }
    /**
     * <code>optional string analyticsCookie = 8;</code>
     */
    public Builder setAnalyticsCookie(
        java.lang.String value) {
      copyOnWrite();
      instance.setAnalyticsCookie(value);
      return this;
    }
    /**
     * <code>optional string analyticsCookie = 8;</code>
     */
    public Builder clearAnalyticsCookie() {
      copyOnWrite();
      instance.clearAnalyticsCookie();
      return this;
    }
    /**
     * <code>optional string analyticsCookie = 8;</code>
     */
    public Builder setAnalyticsCookieBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAnalyticsCookieBytes(value);
      return this;
    }

    /**
     * <code>optional string fullContentsListUrl = 9;</code>
     */
    public boolean hasFullContentsListUrl() {
      return instance.hasFullContentsListUrl();
    }
    /**
     * <code>optional string fullContentsListUrl = 9;</code>
     */
    public java.lang.String getFullContentsListUrl() {
      return instance.getFullContentsListUrl();
    }
    /**
     * <code>optional string fullContentsListUrl = 9;</code>
     */
    public com.google.protobuf.ByteString
        getFullContentsListUrlBytes() {
      return instance.getFullContentsListUrlBytes();
    }
    /**
     * <code>optional string fullContentsListUrl = 9;</code>
     */
    public Builder setFullContentsListUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setFullContentsListUrl(value);
      return this;
    }
    /**
     * <code>optional string fullContentsListUrl = 9;</code>
     */
    public Builder clearFullContentsListUrl() {
      copyOnWrite();
      instance.clearFullContentsListUrl();
      return this;
    }
    /**
     * <code>optional string fullContentsListUrl = 9;</code>
     */
    public Builder setFullContentsListUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFullContentsListUrlBytes(value);
      return this;
    }

    /**
     * <code>optional string nextPageUrl = 10;</code>
     */
    public boolean hasNextPageUrl() {
      return instance.hasNextPageUrl();
    }
    /**
     * <code>optional string nextPageUrl = 10;</code>
     */
    public java.lang.String getNextPageUrl() {
      return instance.getNextPageUrl();
    }
    /**
     * <code>optional string nextPageUrl = 10;</code>
     */
    public com.google.protobuf.ByteString
        getNextPageUrlBytes() {
      return instance.getNextPageUrlBytes();
    }
    /**
     * <code>optional string nextPageUrl = 10;</code>
     */
    public Builder setNextPageUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setNextPageUrl(value);
      return this;
    }
    /**
     * <code>optional string nextPageUrl = 10;</code>
     */
    public Builder clearNextPageUrl() {
      copyOnWrite();
      instance.clearNextPageUrl();
      return this;
    }
    /**
     * <code>optional string nextPageUrl = 10;</code>
     */
    public Builder setNextPageUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNextPageUrlBytes(value);
      return this;
    }

    /**
     * <code>optional bool ordered = 11;</code>
     */
    public boolean hasOrdered() {
      return instance.hasOrdered();
    }
    /**
     * <code>optional bool ordered = 11;</code>
     */
    public boolean getOrdered() {
      return instance.getOrdered();
    }
    /**
     * <code>optional bool ordered = 11;</code>
     */
    public Builder setOrdered(boolean value) {
      copyOnWrite();
      instance.setOrdered(value);
      return this;
    }
    /**
     * <code>optional bool ordered = 11;</code>
     */
    public Builder clearOrdered() {
      copyOnWrite();
      instance.clearOrdered();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Bucket)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.github.yeriomin.playstoreapi.Bucket();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        document_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.github.yeriomin.playstoreapi.Bucket other = (com.github.yeriomin.playstoreapi.Bucket) arg1;
        document_= visitor.visitList(document_, other.document_);
        multiCorpus_ = visitor.visitBoolean(
            hasMultiCorpus(), multiCorpus_,
            other.hasMultiCorpus(), other.multiCorpus_);
        title_ = visitor.visitString(
            hasTitle(), title_,
            other.hasTitle(), other.title_);
        iconUrl_ = visitor.visitString(
            hasIconUrl(), iconUrl_,
            other.hasIconUrl(), other.iconUrl_);
        fullContentsUrl_ = visitor.visitString(
            hasFullContentsUrl(), fullContentsUrl_,
            other.hasFullContentsUrl(), other.fullContentsUrl_);
        relevance_ = visitor.visitDouble(
            hasRelevance(), relevance_,
            other.hasRelevance(), other.relevance_);
        estimatedResults_ = visitor.visitLong(
            hasEstimatedResults(), estimatedResults_,
            other.hasEstimatedResults(), other.estimatedResults_);
        analyticsCookie_ = visitor.visitString(
            hasAnalyticsCookie(), analyticsCookie_,
            other.hasAnalyticsCookie(), other.analyticsCookie_);
        fullContentsListUrl_ = visitor.visitString(
            hasFullContentsListUrl(), fullContentsListUrl_,
            other.hasFullContentsListUrl(), other.fullContentsListUrl_);
        nextPageUrl_ = visitor.visitString(
            hasNextPageUrl(), nextPageUrl_,
            other.hasNextPageUrl(), other.nextPageUrl_);
        ordered_ = visitor.visitBoolean(
            hasOrdered(), ordered_,
            other.hasOrdered(), other.ordered_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                if (!document_.isModifiable()) {
                  document_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(document_);
                }
                document_.add(
                    input.readMessage(com.github.yeriomin.playstoreapi.DocV1.parser(), extensionRegistry));
                break;
              }
              case 16: {
                bitField0_ |= 0x00000001;
                multiCorpus_ = input.readBool();
                break;
              }
              case 26: {
                String s = input.readString();
                bitField0_ |= 0x00000002;
                title_ = s;
                break;
              }
              case 34: {
                String s = input.readString();
                bitField0_ |= 0x00000004;
                iconUrl_ = s;
                break;
              }
              case 42: {
                String s = input.readString();
                bitField0_ |= 0x00000008;
                fullContentsUrl_ = s;
                break;
              }
              case 49: {
                bitField0_ |= 0x00000010;
                relevance_ = input.readDouble();
                break;
              }
              case 56: {
                bitField0_ |= 0x00000020;
                estimatedResults_ = input.readInt64();
                break;
              }
              case 66: {
                String s = input.readString();
                bitField0_ |= 0x00000040;
                analyticsCookie_ = s;
                break;
              }
              case 74: {
                String s = input.readString();
                bitField0_ |= 0x00000080;
                fullContentsListUrl_ = s;
                break;
              }
              case 82: {
                String s = input.readString();
                bitField0_ |= 0x00000100;
                nextPageUrl_ = s;
                break;
              }
              case 88: {
                bitField0_ |= 0x00000200;
                ordered_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.github.yeriomin.playstoreapi.Bucket.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:Bucket)
  private static final com.github.yeriomin.playstoreapi.Bucket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Bucket();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.github.yeriomin.playstoreapi.Bucket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Bucket> PARSER;

  public static com.google.protobuf.Parser<Bucket> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

