// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstoreapi;

public interface CategoryIdContainerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CategoryIdContainer)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string categoryId = 4;</code>
   */
  boolean hasCategoryId();
  /**
   * <code>optional string categoryId = 4;</code>
   */
  java.lang.String getCategoryId();
  /**
   * <code>optional string categoryId = 4;</code>
   */
  com.google.protobuf.ByteString
      getCategoryIdBytes();
}
