// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstoreapi;

/**
 * Protobuf type {@code RelatedLinksUnknown1}
 */
public  final class RelatedLinksUnknown1 extends
    com.google.protobuf.GeneratedMessageLite<
        RelatedLinksUnknown1, RelatedLinksUnknown1.Builder> implements
    // @@protoc_insertion_point(message_implements:RelatedLinksUnknown1)
    RelatedLinksUnknown1OrBuilder {
  private RelatedLinksUnknown1() {
  }
  private int bitField0_;
  public static final int UNKNOWN2_FIELD_NUMBER = 2;
  private com.github.yeriomin.playstoreapi.RelatedLinksUnknown2 unknown2_;
  /**
   * <code>optional .RelatedLinksUnknown2 unknown2 = 2;</code>
   */
  public boolean hasUnknown2() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional .RelatedLinksUnknown2 unknown2 = 2;</code>
   */
  public com.github.yeriomin.playstoreapi.RelatedLinksUnknown2 getUnknown2() {
    return unknown2_ == null ? com.github.yeriomin.playstoreapi.RelatedLinksUnknown2.getDefaultInstance() : unknown2_;
  }
  /**
   * <code>optional .RelatedLinksUnknown2 unknown2 = 2;</code>
   */
  private void setUnknown2(com.github.yeriomin.playstoreapi.RelatedLinksUnknown2 value) {
    if (value == null) {
      throw new NullPointerException();
    }
    unknown2_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>optional .RelatedLinksUnknown2 unknown2 = 2;</code>
   */
  private void setUnknown2(
      com.github.yeriomin.playstoreapi.RelatedLinksUnknown2.Builder builderForValue) {
    unknown2_ = builderForValue.build();
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .RelatedLinksUnknown2 unknown2 = 2;</code>
   */
  private void mergeUnknown2(com.github.yeriomin.playstoreapi.RelatedLinksUnknown2 value) {
    if (unknown2_ != null &&
        unknown2_ != com.github.yeriomin.playstoreapi.RelatedLinksUnknown2.getDefaultInstance()) {
      unknown2_ =
        com.github.yeriomin.playstoreapi.RelatedLinksUnknown2.newBuilder(unknown2_).mergeFrom(value).buildPartial();
    } else {
      unknown2_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .RelatedLinksUnknown2 unknown2 = 2;</code>
   */
  private void clearUnknown2() {  unknown2_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(2, getUnknown2());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUnknown2());
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static com.github.yeriomin.playstoreapi.RelatedLinksUnknown1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstoreapi.RelatedLinksUnknown1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.RelatedLinksUnknown1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstoreapi.RelatedLinksUnknown1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.RelatedLinksUnknown1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstoreapi.RelatedLinksUnknown1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.RelatedLinksUnknown1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstoreapi.RelatedLinksUnknown1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.RelatedLinksUnknown1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstoreapi.RelatedLinksUnknown1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.yeriomin.playstoreapi.RelatedLinksUnknown1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code RelatedLinksUnknown1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.github.yeriomin.playstoreapi.RelatedLinksUnknown1, Builder> implements
      // @@protoc_insertion_point(builder_implements:RelatedLinksUnknown1)
      com.github.yeriomin.playstoreapi.RelatedLinksUnknown1OrBuilder {
    // Construct using com.github.yeriomin.playstoreapi.RelatedLinksUnknown1.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .RelatedLinksUnknown2 unknown2 = 2;</code>
     */
    public boolean hasUnknown2() {
      return instance.hasUnknown2();
    }
    /**
     * <code>optional .RelatedLinksUnknown2 unknown2 = 2;</code>
     */
    public com.github.yeriomin.playstoreapi.RelatedLinksUnknown2 getUnknown2() {
      return instance.getUnknown2();
    }
    /**
     * <code>optional .RelatedLinksUnknown2 unknown2 = 2;</code>
     */
    public Builder setUnknown2(com.github.yeriomin.playstoreapi.RelatedLinksUnknown2 value) {
      copyOnWrite();
      instance.setUnknown2(value);
      return this;
      }
    /**
     * <code>optional .RelatedLinksUnknown2 unknown2 = 2;</code>
     */
    public Builder setUnknown2(
        com.github.yeriomin.playstoreapi.RelatedLinksUnknown2.Builder builderForValue) {
      copyOnWrite();
      instance.setUnknown2(builderForValue);
      return this;
    }
    /**
     * <code>optional .RelatedLinksUnknown2 unknown2 = 2;</code>
     */
    public Builder mergeUnknown2(com.github.yeriomin.playstoreapi.RelatedLinksUnknown2 value) {
      copyOnWrite();
      instance.mergeUnknown2(value);
      return this;
    }
    /**
     * <code>optional .RelatedLinksUnknown2 unknown2 = 2;</code>
     */
    public Builder clearUnknown2() {  copyOnWrite();
      instance.clearUnknown2();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:RelatedLinksUnknown1)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.github.yeriomin.playstoreapi.RelatedLinksUnknown1();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.github.yeriomin.playstoreapi.RelatedLinksUnknown1 other = (com.github.yeriomin.playstoreapi.RelatedLinksUnknown1) arg1;
        unknown2_ = visitor.visitMessage(unknown2_, other.unknown2_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 18: {
                com.github.yeriomin.playstoreapi.RelatedLinksUnknown2.Builder subBuilder = null;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                  subBuilder = unknown2_.toBuilder();
                }
                unknown2_ = input.readMessage(com.github.yeriomin.playstoreapi.RelatedLinksUnknown2.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(unknown2_);
                  unknown2_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000001;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.github.yeriomin.playstoreapi.RelatedLinksUnknown1.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:RelatedLinksUnknown1)
  private static final com.github.yeriomin.playstoreapi.RelatedLinksUnknown1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RelatedLinksUnknown1();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.github.yeriomin.playstoreapi.RelatedLinksUnknown1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RelatedLinksUnknown1> PARSER;

  public static com.google.protobuf.Parser<RelatedLinksUnknown1> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

