// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstoreapi;

/**
 * Protobuf type {@code VideoDetails}
 */
public  final class VideoDetails extends
    com.google.protobuf.GeneratedMessageLite<
        VideoDetails, VideoDetails.Builder> implements
    // @@protoc_insertion_point(message_implements:VideoDetails)
    VideoDetailsOrBuilder {
  private VideoDetails() {
    credit_ = emptyProtobufList();
    duration_ = "";
    releaseDate_ = "";
    contentRating_ = "";
    genre_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    trailer_ = emptyProtobufList();
    rentalTerm_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int CREDIT_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.github.yeriomin.playstoreapi.VideoCredit> credit_;
  /**
   * <code>repeated .VideoCredit credit = 1;</code>
   */
  public java.util.List<com.github.yeriomin.playstoreapi.VideoCredit> getCreditList() {
    return credit_;
  }
  /**
   * <code>repeated .VideoCredit credit = 1;</code>
   */
  public java.util.List<? extends com.github.yeriomin.playstoreapi.VideoCreditOrBuilder> 
      getCreditOrBuilderList() {
    return credit_;
  }
  /**
   * <code>repeated .VideoCredit credit = 1;</code>
   */
  public int getCreditCount() {
    return credit_.size();
  }
  /**
   * <code>repeated .VideoCredit credit = 1;</code>
   */
  public com.github.yeriomin.playstoreapi.VideoCredit getCredit(int index) {
    return credit_.get(index);
  }
  /**
   * <code>repeated .VideoCredit credit = 1;</code>
   */
  public com.github.yeriomin.playstoreapi.VideoCreditOrBuilder getCreditOrBuilder(
      int index) {
    return credit_.get(index);
  }
  private void ensureCreditIsMutable() {
    if (!credit_.isModifiable()) {
      credit_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(credit_);
     }
  }

  /**
   * <code>repeated .VideoCredit credit = 1;</code>
   */
  private void setCredit(
      int index, com.github.yeriomin.playstoreapi.VideoCredit value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureCreditIsMutable();
    credit_.set(index, value);
  }
  /**
   * <code>repeated .VideoCredit credit = 1;</code>
   */
  private void setCredit(
      int index, com.github.yeriomin.playstoreapi.VideoCredit.Builder builderForValue) {
    ensureCreditIsMutable();
    credit_.set(index, builderForValue.build());
  }
  /**
   * <code>repeated .VideoCredit credit = 1;</code>
   */
  private void addCredit(com.github.yeriomin.playstoreapi.VideoCredit value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureCreditIsMutable();
    credit_.add(value);
  }
  /**
   * <code>repeated .VideoCredit credit = 1;</code>
   */
  private void addCredit(
      int index, com.github.yeriomin.playstoreapi.VideoCredit value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureCreditIsMutable();
    credit_.add(index, value);
  }
  /**
   * <code>repeated .VideoCredit credit = 1;</code>
   */
  private void addCredit(
      com.github.yeriomin.playstoreapi.VideoCredit.Builder builderForValue) {
    ensureCreditIsMutable();
    credit_.add(builderForValue.build());
  }
  /**
   * <code>repeated .VideoCredit credit = 1;</code>
   */
  private void addCredit(
      int index, com.github.yeriomin.playstoreapi.VideoCredit.Builder builderForValue) {
    ensureCreditIsMutable();
    credit_.add(index, builderForValue.build());
  }
  /**
   * <code>repeated .VideoCredit credit = 1;</code>
   */
  private void addAllCredit(
      java.lang.Iterable<? extends com.github.yeriomin.playstoreapi.VideoCredit> values) {
    ensureCreditIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, credit_);
  }
  /**
   * <code>repeated .VideoCredit credit = 1;</code>
   */
  private void clearCredit() {
    credit_ = emptyProtobufList();
  }
  /**
   * <code>repeated .VideoCredit credit = 1;</code>
   */
  private void removeCredit(int index) {
    ensureCreditIsMutable();
    credit_.remove(index);
  }

  public static final int DURATION_FIELD_NUMBER = 2;
  private java.lang.String duration_;
  /**
   * <code>optional string duration = 2;</code>
   */
  public boolean hasDuration() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string duration = 2;</code>
   */
  public java.lang.String getDuration() {
    return duration_;
  }
  /**
   * <code>optional string duration = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDurationBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(duration_);
  }
  /**
   * <code>optional string duration = 2;</code>
   */
  private void setDuration(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    duration_ = value;
  }
  /**
   * <code>optional string duration = 2;</code>
   */
  private void clearDuration() {
    bitField0_ = (bitField0_ & ~0x00000001);
    duration_ = getDefaultInstance().getDuration();
  }
  /**
   * <code>optional string duration = 2;</code>
   */
  private void setDurationBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    duration_ = value.toStringUtf8();
  }

  public static final int RELEASEDATE_FIELD_NUMBER = 3;
  private java.lang.String releaseDate_;
  /**
   * <code>optional string releaseDate = 3;</code>
   */
  public boolean hasReleaseDate() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string releaseDate = 3;</code>
   */
  public java.lang.String getReleaseDate() {
    return releaseDate_;
  }
  /**
   * <code>optional string releaseDate = 3;</code>
   */
  public com.google.protobuf.ByteString
      getReleaseDateBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(releaseDate_);
  }
  /**
   * <code>optional string releaseDate = 3;</code>
   */
  private void setReleaseDate(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    releaseDate_ = value;
  }
  /**
   * <code>optional string releaseDate = 3;</code>
   */
  private void clearReleaseDate() {
    bitField0_ = (bitField0_ & ~0x00000002);
    releaseDate_ = getDefaultInstance().getReleaseDate();
  }
  /**
   * <code>optional string releaseDate = 3;</code>
   */
  private void setReleaseDateBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    releaseDate_ = value.toStringUtf8();
  }

  public static final int CONTENTRATING_FIELD_NUMBER = 4;
  private java.lang.String contentRating_;
  /**
   * <code>optional string contentRating = 4;</code>
   */
  public boolean hasContentRating() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string contentRating = 4;</code>
   */
  public java.lang.String getContentRating() {
    return contentRating_;
  }
  /**
   * <code>optional string contentRating = 4;</code>
   */
  public com.google.protobuf.ByteString
      getContentRatingBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(contentRating_);
  }
  /**
   * <code>optional string contentRating = 4;</code>
   */
  private void setContentRating(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    contentRating_ = value;
  }
  /**
   * <code>optional string contentRating = 4;</code>
   */
  private void clearContentRating() {
    bitField0_ = (bitField0_ & ~0x00000004);
    contentRating_ = getDefaultInstance().getContentRating();
  }
  /**
   * <code>optional string contentRating = 4;</code>
   */
  private void setContentRatingBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    contentRating_ = value.toStringUtf8();
  }

  public static final int LIKES_FIELD_NUMBER = 5;
  private long likes_;
  /**
   * <code>optional int64 likes = 5;</code>
   */
  public boolean hasLikes() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional int64 likes = 5;</code>
   */
  public long getLikes() {
    return likes_;
  }
  /**
   * <code>optional int64 likes = 5;</code>
   */
  private void setLikes(long value) {
    bitField0_ |= 0x00000008;
    likes_ = value;
  }
  /**
   * <code>optional int64 likes = 5;</code>
   */
  private void clearLikes() {
    bitField0_ = (bitField0_ & ~0x00000008);
    likes_ = 0L;
  }

  public static final int DISLIKES_FIELD_NUMBER = 6;
  private long dislikes_;
  /**
   * <code>optional int64 dislikes = 6;</code>
   */
  public boolean hasDislikes() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional int64 dislikes = 6;</code>
   */
  public long getDislikes() {
    return dislikes_;
  }
  /**
   * <code>optional int64 dislikes = 6;</code>
   */
  private void setDislikes(long value) {
    bitField0_ |= 0x00000010;
    dislikes_ = value;
  }
  /**
   * <code>optional int64 dislikes = 6;</code>
   */
  private void clearDislikes() {
    bitField0_ = (bitField0_ & ~0x00000010);
    dislikes_ = 0L;
  }

  public static final int GENRE_FIELD_NUMBER = 7;
  private com.google.protobuf.Internal.ProtobufList<String> genre_;
  /**
   * <code>repeated string genre = 7;</code>
   */
  public java.util.List<String> getGenreList() {
    return genre_;
  }
  /**
   * <code>repeated string genre = 7;</code>
   */
  public int getGenreCount() {
    return genre_.size();
  }
  /**
   * <code>repeated string genre = 7;</code>
   */
  public java.lang.String getGenre(int index) {
    return genre_.get(index);
  }
  /**
   * <code>repeated string genre = 7;</code>
   */
  public com.google.protobuf.ByteString
      getGenreBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        genre_.get(index));
  }
  private void ensureGenreIsMutable() {
    if (!genre_.isModifiable()) {
      genre_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(genre_);
     }
  }
  /**
   * <code>repeated string genre = 7;</code>
   */
  private void setGenre(
      int index, java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  ensureGenreIsMutable();
    genre_.set(index, value);
  }
  /**
   * <code>repeated string genre = 7;</code>
   */
  private void addGenre(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  ensureGenreIsMutable();
    genre_.add(value);
  }
  /**
   * <code>repeated string genre = 7;</code>
   */
  private void addAllGenre(
      java.lang.Iterable<java.lang.String> values) {
    ensureGenreIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, genre_);
  }
  /**
   * <code>repeated string genre = 7;</code>
   */
  private void clearGenre() {
    genre_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string genre = 7;</code>
   */
  private void addGenreBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  ensureGenreIsMutable();
    genre_.add(value.toStringUtf8());
  }

  public static final int TRAILER_FIELD_NUMBER = 8;
  private com.google.protobuf.Internal.ProtobufList<com.github.yeriomin.playstoreapi.Trailer> trailer_;
  /**
   * <code>repeated .Trailer trailer = 8;</code>
   */
  public java.util.List<com.github.yeriomin.playstoreapi.Trailer> getTrailerList() {
    return trailer_;
  }
  /**
   * <code>repeated .Trailer trailer = 8;</code>
   */
  public java.util.List<? extends com.github.yeriomin.playstoreapi.TrailerOrBuilder> 
      getTrailerOrBuilderList() {
    return trailer_;
  }
  /**
   * <code>repeated .Trailer trailer = 8;</code>
   */
  public int getTrailerCount() {
    return trailer_.size();
  }
  /**
   * <code>repeated .Trailer trailer = 8;</code>
   */
  public com.github.yeriomin.playstoreapi.Trailer getTrailer(int index) {
    return trailer_.get(index);
  }
  /**
   * <code>repeated .Trailer trailer = 8;</code>
   */
  public com.github.yeriomin.playstoreapi.TrailerOrBuilder getTrailerOrBuilder(
      int index) {
    return trailer_.get(index);
  }
  private void ensureTrailerIsMutable() {
    if (!trailer_.isModifiable()) {
      trailer_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(trailer_);
     }
  }

  /**
   * <code>repeated .Trailer trailer = 8;</code>
   */
  private void setTrailer(
      int index, com.github.yeriomin.playstoreapi.Trailer value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureTrailerIsMutable();
    trailer_.set(index, value);
  }
  /**
   * <code>repeated .Trailer trailer = 8;</code>
   */
  private void setTrailer(
      int index, com.github.yeriomin.playstoreapi.Trailer.Builder builderForValue) {
    ensureTrailerIsMutable();
    trailer_.set(index, builderForValue.build());
  }
  /**
   * <code>repeated .Trailer trailer = 8;</code>
   */
  private void addTrailer(com.github.yeriomin.playstoreapi.Trailer value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureTrailerIsMutable();
    trailer_.add(value);
  }
  /**
   * <code>repeated .Trailer trailer = 8;</code>
   */
  private void addTrailer(
      int index, com.github.yeriomin.playstoreapi.Trailer value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureTrailerIsMutable();
    trailer_.add(index, value);
  }
  /**
   * <code>repeated .Trailer trailer = 8;</code>
   */
  private void addTrailer(
      com.github.yeriomin.playstoreapi.Trailer.Builder builderForValue) {
    ensureTrailerIsMutable();
    trailer_.add(builderForValue.build());
  }
  /**
   * <code>repeated .Trailer trailer = 8;</code>
   */
  private void addTrailer(
      int index, com.github.yeriomin.playstoreapi.Trailer.Builder builderForValue) {
    ensureTrailerIsMutable();
    trailer_.add(index, builderForValue.build());
  }
  /**
   * <code>repeated .Trailer trailer = 8;</code>
   */
  private void addAllTrailer(
      java.lang.Iterable<? extends com.github.yeriomin.playstoreapi.Trailer> values) {
    ensureTrailerIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, trailer_);
  }
  /**
   * <code>repeated .Trailer trailer = 8;</code>
   */
  private void clearTrailer() {
    trailer_ = emptyProtobufList();
  }
  /**
   * <code>repeated .Trailer trailer = 8;</code>
   */
  private void removeTrailer(int index) {
    ensureTrailerIsMutable();
    trailer_.remove(index);
  }

  public static final int RENTALTERM_FIELD_NUMBER = 9;
  private com.google.protobuf.Internal.ProtobufList<com.github.yeriomin.playstoreapi.VideoRentalTerm> rentalTerm_;
  /**
   * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
   */
  public java.util.List<com.github.yeriomin.playstoreapi.VideoRentalTerm> getRentalTermList() {
    return rentalTerm_;
  }
  /**
   * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
   */
  public java.util.List<? extends com.github.yeriomin.playstoreapi.VideoRentalTermOrBuilder> 
      getRentalTermOrBuilderList() {
    return rentalTerm_;
  }
  /**
   * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
   */
  public int getRentalTermCount() {
    return rentalTerm_.size();
  }
  /**
   * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
   */
  public com.github.yeriomin.playstoreapi.VideoRentalTerm getRentalTerm(int index) {
    return rentalTerm_.get(index);
  }
  /**
   * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
   */
  public com.github.yeriomin.playstoreapi.VideoRentalTermOrBuilder getRentalTermOrBuilder(
      int index) {
    return rentalTerm_.get(index);
  }
  private void ensureRentalTermIsMutable() {
    if (!rentalTerm_.isModifiable()) {
      rentalTerm_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(rentalTerm_);
     }
  }

  /**
   * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
   */
  private void setRentalTerm(
      int index, com.github.yeriomin.playstoreapi.VideoRentalTerm value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureRentalTermIsMutable();
    rentalTerm_.set(index, value);
  }
  /**
   * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
   */
  private void setRentalTerm(
      int index, com.github.yeriomin.playstoreapi.VideoRentalTerm.Builder builderForValue) {
    ensureRentalTermIsMutable();
    rentalTerm_.set(index, builderForValue.build());
  }
  /**
   * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
   */
  private void addRentalTerm(com.github.yeriomin.playstoreapi.VideoRentalTerm value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureRentalTermIsMutable();
    rentalTerm_.add(value);
  }
  /**
   * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
   */
  private void addRentalTerm(
      int index, com.github.yeriomin.playstoreapi.VideoRentalTerm value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureRentalTermIsMutable();
    rentalTerm_.add(index, value);
  }
  /**
   * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
   */
  private void addRentalTerm(
      com.github.yeriomin.playstoreapi.VideoRentalTerm.Builder builderForValue) {
    ensureRentalTermIsMutable();
    rentalTerm_.add(builderForValue.build());
  }
  /**
   * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
   */
  private void addRentalTerm(
      int index, com.github.yeriomin.playstoreapi.VideoRentalTerm.Builder builderForValue) {
    ensureRentalTermIsMutable();
    rentalTerm_.add(index, builderForValue.build());
  }
  /**
   * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
   */
  private void addAllRentalTerm(
      java.lang.Iterable<? extends com.github.yeriomin.playstoreapi.VideoRentalTerm> values) {
    ensureRentalTermIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, rentalTerm_);
  }
  /**
   * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
   */
  private void clearRentalTerm() {
    rentalTerm_ = emptyProtobufList();
  }
  /**
   * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
   */
  private void removeRentalTerm(int index) {
    ensureRentalTermIsMutable();
    rentalTerm_.remove(index);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < credit_.size(); i++) {
      output.writeMessage(1, credit_.get(i));
    }
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeString(2, getDuration());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeString(3, getReleaseDate());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeString(4, getContentRating());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt64(5, likes_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeInt64(6, dislikes_);
    }
    for (int i = 0; i < genre_.size(); i++) {
      output.writeString(7, genre_.get(i));
    }
    for (int i = 0; i < trailer_.size(); i++) {
      output.writeMessage(8, trailer_.get(i));
    }
    for (int i = 0; i < rentalTerm_.size(); i++) {
      output.writeMessage(9, rentalTerm_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < credit_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, credit_.get(i));
    }
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getDuration());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getReleaseDate());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(4, getContentRating());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, likes_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, dislikes_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < genre_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeStringSizeNoTag(genre_.get(i));
      }
      size += dataSize;
      size += 1 * getGenreList().size();
    }
    for (int i = 0; i < trailer_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, trailer_.get(i));
    }
    for (int i = 0; i < rentalTerm_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, rentalTerm_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static com.github.yeriomin.playstoreapi.VideoDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstoreapi.VideoDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.VideoDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstoreapi.VideoDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.VideoDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstoreapi.VideoDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.VideoDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstoreapi.VideoDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstoreapi.VideoDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstoreapi.VideoDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.yeriomin.playstoreapi.VideoDetails prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code VideoDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.github.yeriomin.playstoreapi.VideoDetails, Builder> implements
      // @@protoc_insertion_point(builder_implements:VideoDetails)
      com.github.yeriomin.playstoreapi.VideoDetailsOrBuilder {
    // Construct using com.github.yeriomin.playstoreapi.VideoDetails.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .VideoCredit credit = 1;</code>
     */
    public java.util.List<com.github.yeriomin.playstoreapi.VideoCredit> getCreditList() {
      return java.util.Collections.unmodifiableList(
          instance.getCreditList());
    }
    /**
     * <code>repeated .VideoCredit credit = 1;</code>
     */
    public int getCreditCount() {
      return instance.getCreditCount();
    }/**
     * <code>repeated .VideoCredit credit = 1;</code>
     */
    public com.github.yeriomin.playstoreapi.VideoCredit getCredit(int index) {
      return instance.getCredit(index);
    }
    /**
     * <code>repeated .VideoCredit credit = 1;</code>
     */
    public Builder setCredit(
        int index, com.github.yeriomin.playstoreapi.VideoCredit value) {
      copyOnWrite();
      instance.setCredit(index, value);
      return this;
    }
    /**
     * <code>repeated .VideoCredit credit = 1;</code>
     */
    public Builder setCredit(
        int index, com.github.yeriomin.playstoreapi.VideoCredit.Builder builderForValue) {
      copyOnWrite();
      instance.setCredit(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .VideoCredit credit = 1;</code>
     */
    public Builder addCredit(com.github.yeriomin.playstoreapi.VideoCredit value) {
      copyOnWrite();
      instance.addCredit(value);
      return this;
    }
    /**
     * <code>repeated .VideoCredit credit = 1;</code>
     */
    public Builder addCredit(
        int index, com.github.yeriomin.playstoreapi.VideoCredit value) {
      copyOnWrite();
      instance.addCredit(index, value);
      return this;
    }
    /**
     * <code>repeated .VideoCredit credit = 1;</code>
     */
    public Builder addCredit(
        com.github.yeriomin.playstoreapi.VideoCredit.Builder builderForValue) {
      copyOnWrite();
      instance.addCredit(builderForValue);
      return this;
    }
    /**
     * <code>repeated .VideoCredit credit = 1;</code>
     */
    public Builder addCredit(
        int index, com.github.yeriomin.playstoreapi.VideoCredit.Builder builderForValue) {
      copyOnWrite();
      instance.addCredit(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .VideoCredit credit = 1;</code>
     */
    public Builder addAllCredit(
        java.lang.Iterable<? extends com.github.yeriomin.playstoreapi.VideoCredit> values) {
      copyOnWrite();
      instance.addAllCredit(values);
      return this;
    }
    /**
     * <code>repeated .VideoCredit credit = 1;</code>
     */
    public Builder clearCredit() {
      copyOnWrite();
      instance.clearCredit();
      return this;
    }
    /**
     * <code>repeated .VideoCredit credit = 1;</code>
     */
    public Builder removeCredit(int index) {
      copyOnWrite();
      instance.removeCredit(index);
      return this;
    }

    /**
     * <code>optional string duration = 2;</code>
     */
    public boolean hasDuration() {
      return instance.hasDuration();
    }
    /**
     * <code>optional string duration = 2;</code>
     */
    public java.lang.String getDuration() {
      return instance.getDuration();
    }
    /**
     * <code>optional string duration = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDurationBytes() {
      return instance.getDurationBytes();
    }
    /**
     * <code>optional string duration = 2;</code>
     */
    public Builder setDuration(
        java.lang.String value) {
      copyOnWrite();
      instance.setDuration(value);
      return this;
    }
    /**
     * <code>optional string duration = 2;</code>
     */
    public Builder clearDuration() {
      copyOnWrite();
      instance.clearDuration();
      return this;
    }
    /**
     * <code>optional string duration = 2;</code>
     */
    public Builder setDurationBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDurationBytes(value);
      return this;
    }

    /**
     * <code>optional string releaseDate = 3;</code>
     */
    public boolean hasReleaseDate() {
      return instance.hasReleaseDate();
    }
    /**
     * <code>optional string releaseDate = 3;</code>
     */
    public java.lang.String getReleaseDate() {
      return instance.getReleaseDate();
    }
    /**
     * <code>optional string releaseDate = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReleaseDateBytes() {
      return instance.getReleaseDateBytes();
    }
    /**
     * <code>optional string releaseDate = 3;</code>
     */
    public Builder setReleaseDate(
        java.lang.String value) {
      copyOnWrite();
      instance.setReleaseDate(value);
      return this;
    }
    /**
     * <code>optional string releaseDate = 3;</code>
     */
    public Builder clearReleaseDate() {
      copyOnWrite();
      instance.clearReleaseDate();
      return this;
    }
    /**
     * <code>optional string releaseDate = 3;</code>
     */
    public Builder setReleaseDateBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReleaseDateBytes(value);
      return this;
    }

    /**
     * <code>optional string contentRating = 4;</code>
     */
    public boolean hasContentRating() {
      return instance.hasContentRating();
    }
    /**
     * <code>optional string contentRating = 4;</code>
     */
    public java.lang.String getContentRating() {
      return instance.getContentRating();
    }
    /**
     * <code>optional string contentRating = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentRatingBytes() {
      return instance.getContentRatingBytes();
    }
    /**
     * <code>optional string contentRating = 4;</code>
     */
    public Builder setContentRating(
        java.lang.String value) {
      copyOnWrite();
      instance.setContentRating(value);
      return this;
    }
    /**
     * <code>optional string contentRating = 4;</code>
     */
    public Builder clearContentRating() {
      copyOnWrite();
      instance.clearContentRating();
      return this;
    }
    /**
     * <code>optional string contentRating = 4;</code>
     */
    public Builder setContentRatingBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setContentRatingBytes(value);
      return this;
    }

    /**
     * <code>optional int64 likes = 5;</code>
     */
    public boolean hasLikes() {
      return instance.hasLikes();
    }
    /**
     * <code>optional int64 likes = 5;</code>
     */
    public long getLikes() {
      return instance.getLikes();
    }
    /**
     * <code>optional int64 likes = 5;</code>
     */
    public Builder setLikes(long value) {
      copyOnWrite();
      instance.setLikes(value);
      return this;
    }
    /**
     * <code>optional int64 likes = 5;</code>
     */
    public Builder clearLikes() {
      copyOnWrite();
      instance.clearLikes();
      return this;
    }

    /**
     * <code>optional int64 dislikes = 6;</code>
     */
    public boolean hasDislikes() {
      return instance.hasDislikes();
    }
    /**
     * <code>optional int64 dislikes = 6;</code>
     */
    public long getDislikes() {
      return instance.getDislikes();
    }
    /**
     * <code>optional int64 dislikes = 6;</code>
     */
    public Builder setDislikes(long value) {
      copyOnWrite();
      instance.setDislikes(value);
      return this;
    }
    /**
     * <code>optional int64 dislikes = 6;</code>
     */
    public Builder clearDislikes() {
      copyOnWrite();
      instance.clearDislikes();
      return this;
    }

    /**
     * <code>repeated string genre = 7;</code>
     */
    public java.util.List<String>
        getGenreList() {
      return java.util.Collections.unmodifiableList(
          instance.getGenreList());
    }
    /**
     * <code>repeated string genre = 7;</code>
     */
    public int getGenreCount() {
      return instance.getGenreCount();
    }
    /**
     * <code>repeated string genre = 7;</code>
     */
    public java.lang.String getGenre(int index) {
      return instance.getGenre(index);
    }
    /**
     * <code>repeated string genre = 7;</code>
     */
    public com.google.protobuf.ByteString
        getGenreBytes(int index) {
      return instance.getGenreBytes(index);
    }
    /**
     * <code>repeated string genre = 7;</code>
     */
    public Builder setGenre(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setGenre(index, value);
      return this;
    }
    /**
     * <code>repeated string genre = 7;</code>
     */
    public Builder addGenre(
        java.lang.String value) {
      copyOnWrite();
      instance.addGenre(value);
      return this;
    }
    /**
     * <code>repeated string genre = 7;</code>
     */
    public Builder addAllGenre(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllGenre(values);
      return this;
    }
    /**
     * <code>repeated string genre = 7;</code>
     */
    public Builder clearGenre() {
      copyOnWrite();
      instance.clearGenre();
      return this;
    }
    /**
     * <code>repeated string genre = 7;</code>
     */
    public Builder addGenreBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addGenreBytes(value);
      return this;
    }

    /**
     * <code>repeated .Trailer trailer = 8;</code>
     */
    public java.util.List<com.github.yeriomin.playstoreapi.Trailer> getTrailerList() {
      return java.util.Collections.unmodifiableList(
          instance.getTrailerList());
    }
    /**
     * <code>repeated .Trailer trailer = 8;</code>
     */
    public int getTrailerCount() {
      return instance.getTrailerCount();
    }/**
     * <code>repeated .Trailer trailer = 8;</code>
     */
    public com.github.yeriomin.playstoreapi.Trailer getTrailer(int index) {
      return instance.getTrailer(index);
    }
    /**
     * <code>repeated .Trailer trailer = 8;</code>
     */
    public Builder setTrailer(
        int index, com.github.yeriomin.playstoreapi.Trailer value) {
      copyOnWrite();
      instance.setTrailer(index, value);
      return this;
    }
    /**
     * <code>repeated .Trailer trailer = 8;</code>
     */
    public Builder setTrailer(
        int index, com.github.yeriomin.playstoreapi.Trailer.Builder builderForValue) {
      copyOnWrite();
      instance.setTrailer(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .Trailer trailer = 8;</code>
     */
    public Builder addTrailer(com.github.yeriomin.playstoreapi.Trailer value) {
      copyOnWrite();
      instance.addTrailer(value);
      return this;
    }
    /**
     * <code>repeated .Trailer trailer = 8;</code>
     */
    public Builder addTrailer(
        int index, com.github.yeriomin.playstoreapi.Trailer value) {
      copyOnWrite();
      instance.addTrailer(index, value);
      return this;
    }
    /**
     * <code>repeated .Trailer trailer = 8;</code>
     */
    public Builder addTrailer(
        com.github.yeriomin.playstoreapi.Trailer.Builder builderForValue) {
      copyOnWrite();
      instance.addTrailer(builderForValue);
      return this;
    }
    /**
     * <code>repeated .Trailer trailer = 8;</code>
     */
    public Builder addTrailer(
        int index, com.github.yeriomin.playstoreapi.Trailer.Builder builderForValue) {
      copyOnWrite();
      instance.addTrailer(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .Trailer trailer = 8;</code>
     */
    public Builder addAllTrailer(
        java.lang.Iterable<? extends com.github.yeriomin.playstoreapi.Trailer> values) {
      copyOnWrite();
      instance.addAllTrailer(values);
      return this;
    }
    /**
     * <code>repeated .Trailer trailer = 8;</code>
     */
    public Builder clearTrailer() {
      copyOnWrite();
      instance.clearTrailer();
      return this;
    }
    /**
     * <code>repeated .Trailer trailer = 8;</code>
     */
    public Builder removeTrailer(int index) {
      copyOnWrite();
      instance.removeTrailer(index);
      return this;
    }

    /**
     * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
     */
    public java.util.List<com.github.yeriomin.playstoreapi.VideoRentalTerm> getRentalTermList() {
      return java.util.Collections.unmodifiableList(
          instance.getRentalTermList());
    }
    /**
     * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
     */
    public int getRentalTermCount() {
      return instance.getRentalTermCount();
    }/**
     * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
     */
    public com.github.yeriomin.playstoreapi.VideoRentalTerm getRentalTerm(int index) {
      return instance.getRentalTerm(index);
    }
    /**
     * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
     */
    public Builder setRentalTerm(
        int index, com.github.yeriomin.playstoreapi.VideoRentalTerm value) {
      copyOnWrite();
      instance.setRentalTerm(index, value);
      return this;
    }
    /**
     * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
     */
    public Builder setRentalTerm(
        int index, com.github.yeriomin.playstoreapi.VideoRentalTerm.Builder builderForValue) {
      copyOnWrite();
      instance.setRentalTerm(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
     */
    public Builder addRentalTerm(com.github.yeriomin.playstoreapi.VideoRentalTerm value) {
      copyOnWrite();
      instance.addRentalTerm(value);
      return this;
    }
    /**
     * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
     */
    public Builder addRentalTerm(
        int index, com.github.yeriomin.playstoreapi.VideoRentalTerm value) {
      copyOnWrite();
      instance.addRentalTerm(index, value);
      return this;
    }
    /**
     * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
     */
    public Builder addRentalTerm(
        com.github.yeriomin.playstoreapi.VideoRentalTerm.Builder builderForValue) {
      copyOnWrite();
      instance.addRentalTerm(builderForValue);
      return this;
    }
    /**
     * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
     */
    public Builder addRentalTerm(
        int index, com.github.yeriomin.playstoreapi.VideoRentalTerm.Builder builderForValue) {
      copyOnWrite();
      instance.addRentalTerm(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
     */
    public Builder addAllRentalTerm(
        java.lang.Iterable<? extends com.github.yeriomin.playstoreapi.VideoRentalTerm> values) {
      copyOnWrite();
      instance.addAllRentalTerm(values);
      return this;
    }
    /**
     * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
     */
    public Builder clearRentalTerm() {
      copyOnWrite();
      instance.clearRentalTerm();
      return this;
    }
    /**
     * <code>repeated .VideoRentalTerm rentalTerm = 9;</code>
     */
    public Builder removeRentalTerm(int index) {
      copyOnWrite();
      instance.removeRentalTerm(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:VideoDetails)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.github.yeriomin.playstoreapi.VideoDetails();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        credit_.makeImmutable();
        genre_.makeImmutable();
        trailer_.makeImmutable();
        rentalTerm_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.github.yeriomin.playstoreapi.VideoDetails other = (com.github.yeriomin.playstoreapi.VideoDetails) arg1;
        credit_= visitor.visitList(credit_, other.credit_);
        duration_ = visitor.visitString(
            hasDuration(), duration_,
            other.hasDuration(), other.duration_);
        releaseDate_ = visitor.visitString(
            hasReleaseDate(), releaseDate_,
            other.hasReleaseDate(), other.releaseDate_);
        contentRating_ = visitor.visitString(
            hasContentRating(), contentRating_,
            other.hasContentRating(), other.contentRating_);
        likes_ = visitor.visitLong(
            hasLikes(), likes_,
            other.hasLikes(), other.likes_);
        dislikes_ = visitor.visitLong(
            hasDislikes(), dislikes_,
            other.hasDislikes(), other.dislikes_);
        genre_= visitor.visitList(genre_, other.genre_);
        trailer_= visitor.visitList(trailer_, other.trailer_);
        rentalTerm_= visitor.visitList(rentalTerm_, other.rentalTerm_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                if (!credit_.isModifiable()) {
                  credit_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(credit_);
                }
                credit_.add(
                    input.readMessage(com.github.yeriomin.playstoreapi.VideoCredit.parser(), extensionRegistry));
                break;
              }
              case 18: {
                String s = input.readString();
                bitField0_ |= 0x00000001;
                duration_ = s;
                break;
              }
              case 26: {
                String s = input.readString();
                bitField0_ |= 0x00000002;
                releaseDate_ = s;
                break;
              }
              case 34: {
                String s = input.readString();
                bitField0_ |= 0x00000004;
                contentRating_ = s;
                break;
              }
              case 40: {
                bitField0_ |= 0x00000008;
                likes_ = input.readInt64();
                break;
              }
              case 48: {
                bitField0_ |= 0x00000010;
                dislikes_ = input.readInt64();
                break;
              }
              case 58: {
                String s = input.readString();
                if (!genre_.isModifiable()) {
                  genre_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(genre_);
                }
                genre_.add(s);
                break;
              }
              case 66: {
                if (!trailer_.isModifiable()) {
                  trailer_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(trailer_);
                }
                trailer_.add(
                    input.readMessage(com.github.yeriomin.playstoreapi.Trailer.parser(), extensionRegistry));
                break;
              }
              case 74: {
                if (!rentalTerm_.isModifiable()) {
                  rentalTerm_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(rentalTerm_);
                }
                rentalTerm_.add(
                    input.readMessage(com.github.yeriomin.playstoreapi.VideoRentalTerm.parser(), extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.github.yeriomin.playstoreapi.VideoDetails.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:VideoDetails)
  private static final com.github.yeriomin.playstoreapi.VideoDetails DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new VideoDetails();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.github.yeriomin.playstoreapi.VideoDetails getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<VideoDetails> PARSER;

  public static com.google.protobuf.Parser<VideoDetails> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

