// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.message;

/**
 * Protobuf type {@code AndroidIntentProto}
 */
public  final class AndroidIntentProto extends
    com.google.protobuf.GeneratedMessageLite<
        AndroidIntentProto, AndroidIntentProto.Builder> implements
    // @@protoc_insertion_point(message_implements:AndroidIntentProto)
    AndroidIntentProtoOrBuilder {
  private AndroidIntentProto() {
    action_ = "";
    dataUri_ = "";
    mimeType_ = "";
    javaClass_ = "";
    extra_ = emptyProtobufList();
  }
  public interface ExtraOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AndroidIntentProto.Extra)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string name = 6;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 6;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 6;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string value = 7;</code>
     */
    boolean hasValue();
    /**
     * <code>optional string value = 7;</code>
     */
    java.lang.String getValue();
    /**
     * <code>optional string value = 7;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code AndroidIntentProto.Extra}
   */
  public  static final class Extra extends
      com.google.protobuf.GeneratedMessageLite<
          Extra, Extra.Builder> implements
      // @@protoc_insertion_point(message_implements:AndroidIntentProto.Extra)
      ExtraOrBuilder {
    private Extra() {
      name_ = "";
      value_ = "";
    }
    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 6;
    private java.lang.String name_;
    /**
     * <code>optional string name = 6;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 6;</code>
     */
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>optional string name = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>optional string name = 6;</code>
     */
    private void setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
    }
    /**
     * <code>optional string name = 6;</code>
     */
    private void clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>optional string name = 6;</code>
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value.toStringUtf8();
    }

    public static final int VALUE_FIELD_NUMBER = 7;
    private java.lang.String value_;
    /**
     * <code>optional string value = 7;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string value = 7;</code>
     */
    public java.lang.String getValue() {
      return value_;
    }
    /**
     * <code>optional string value = 7;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(value_);
    }
    /**
     * <code>optional string value = 7;</code>
     */
    private void setValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      value_ = value;
    }
    /**
     * <code>optional string value = 7;</code>
     */
    private void clearValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      value_ = getDefaultInstance().getValue();
    }
    /**
     * <code>optional string value = 7;</code>
     */
    private void setValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      value_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeString(6, getName());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(7, getValue());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getName());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getValue());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.github.yeriomin.playstore.message.AndroidIntentProto.Extra parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.yeriomin.playstore.message.AndroidIntentProto.Extra parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.yeriomin.playstore.message.AndroidIntentProto.Extra parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.github.yeriomin.playstore.message.AndroidIntentProto.Extra parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.github.yeriomin.playstore.message.AndroidIntentProto.Extra parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.yeriomin.playstore.message.AndroidIntentProto.Extra parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.yeriomin.playstore.message.AndroidIntentProto.Extra parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.github.yeriomin.playstore.message.AndroidIntentProto.Extra parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.github.yeriomin.playstore.message.AndroidIntentProto.Extra parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.github.yeriomin.playstore.message.AndroidIntentProto.Extra parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.yeriomin.playstore.message.AndroidIntentProto.Extra prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code AndroidIntentProto.Extra}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.github.yeriomin.playstore.message.AndroidIntentProto.Extra, Builder> implements
        // @@protoc_insertion_point(builder_implements:AndroidIntentProto.Extra)
        com.github.yeriomin.playstore.message.AndroidIntentProto.ExtraOrBuilder {
      // Construct using com.github.yeriomin.playstoreapi.AndroidIntentProto.Extra.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string name = 6;</code>
       */
      public boolean hasName() {
        return instance.hasName();
      }
      /**
       * <code>optional string name = 6;</code>
       */
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>optional string name = 6;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>optional string name = 6;</code>
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>optional string name = 6;</code>
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>optional string name = 6;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>optional string value = 7;</code>
       */
      public boolean hasValue() {
        return instance.hasValue();
      }
      /**
       * <code>optional string value = 7;</code>
       */
      public java.lang.String getValue() {
        return instance.getValue();
      }
      /**
       * <code>optional string value = 7;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        return instance.getValueBytes();
      }
      /**
       * <code>optional string value = 7;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        copyOnWrite();
        instance.setValue(value);
        return this;
      }
      /**
       * <code>optional string value = 7;</code>
       */
      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }
      /**
       * <code>optional string value = 7;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setValueBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AndroidIntentProto.Extra)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.github.yeriomin.playstore.message.AndroidIntentProto.Extra();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.github.yeriomin.playstore.message.AndroidIntentProto.Extra other = (com.github.yeriomin.playstore.message.AndroidIntentProto.Extra) arg1;
          name_ = visitor.visitString(
              hasName(), name_,
              other.hasName(), other.name_);
          value_ = visitor.visitString(
              hasValue(), value_,
              other.hasValue(), other.value_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 50: {
                  String s = input.readString();
                  bitField0_ |= 0x00000001;
                  name_ = s;
                  break;
                }
                case 58: {
                  String s = input.readString();
                  bitField0_ |= 0x00000002;
                  value_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.github.yeriomin.playstore.message.AndroidIntentProto.Extra.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:AndroidIntentProto.Extra)
    private static final com.github.yeriomin.playstore.message.AndroidIntentProto.Extra DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Extra();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.github.yeriomin.playstore.message.AndroidIntentProto.Extra getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Extra> PARSER;

    public static com.google.protobuf.Parser<Extra> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  private int bitField0_;
  public static final int ACTION_FIELD_NUMBER = 1;
  private java.lang.String action_;
  /**
   * <code>optional string action = 1;</code>
   */
  public boolean hasAction() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string action = 1;</code>
   */
  public java.lang.String getAction() {
    return action_;
  }
  /**
   * <code>optional string action = 1;</code>
   */
  public com.google.protobuf.ByteString
      getActionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(action_);
  }
  /**
   * <code>optional string action = 1;</code>
   */
  private void setAction(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    action_ = value;
  }
  /**
   * <code>optional string action = 1;</code>
   */
  private void clearAction() {
    bitField0_ = (bitField0_ & ~0x00000001);
    action_ = getDefaultInstance().getAction();
  }
  /**
   * <code>optional string action = 1;</code>
   */
  private void setActionBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    action_ = value.toStringUtf8();
  }

  public static final int DATAURI_FIELD_NUMBER = 2;
  private java.lang.String dataUri_;
  /**
   * <code>optional string dataUri = 2;</code>
   */
  public boolean hasDataUri() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string dataUri = 2;</code>
   */
  public java.lang.String getDataUri() {
    return dataUri_;
  }
  /**
   * <code>optional string dataUri = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDataUriBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(dataUri_);
  }
  /**
   * <code>optional string dataUri = 2;</code>
   */
  private void setDataUri(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    dataUri_ = value;
  }
  /**
   * <code>optional string dataUri = 2;</code>
   */
  private void clearDataUri() {
    bitField0_ = (bitField0_ & ~0x00000002);
    dataUri_ = getDefaultInstance().getDataUri();
  }
  /**
   * <code>optional string dataUri = 2;</code>
   */
  private void setDataUriBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    dataUri_ = value.toStringUtf8();
  }

  public static final int MIMETYPE_FIELD_NUMBER = 3;
  private java.lang.String mimeType_;
  /**
   * <code>optional string mimeType = 3;</code>
   */
  public boolean hasMimeType() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string mimeType = 3;</code>
   */
  public java.lang.String getMimeType() {
    return mimeType_;
  }
  /**
   * <code>optional string mimeType = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMimeTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mimeType_);
  }
  /**
   * <code>optional string mimeType = 3;</code>
   */
  private void setMimeType(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    mimeType_ = value;
  }
  /**
   * <code>optional string mimeType = 3;</code>
   */
  private void clearMimeType() {
    bitField0_ = (bitField0_ & ~0x00000004);
    mimeType_ = getDefaultInstance().getMimeType();
  }
  /**
   * <code>optional string mimeType = 3;</code>
   */
  private void setMimeTypeBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    mimeType_ = value.toStringUtf8();
  }

  public static final int JAVACLASS_FIELD_NUMBER = 4;
  private java.lang.String javaClass_;
  /**
   * <code>optional string javaClass = 4;</code>
   */
  public boolean hasJavaClass() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional string javaClass = 4;</code>
   */
  public java.lang.String getJavaClass() {
    return javaClass_;
  }
  /**
   * <code>optional string javaClass = 4;</code>
   */
  public com.google.protobuf.ByteString
      getJavaClassBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(javaClass_);
  }
  /**
   * <code>optional string javaClass = 4;</code>
   */
  private void setJavaClass(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
    javaClass_ = value;
  }
  /**
   * <code>optional string javaClass = 4;</code>
   */
  private void clearJavaClass() {
    bitField0_ = (bitField0_ & ~0x00000008);
    javaClass_ = getDefaultInstance().getJavaClass();
  }
  /**
   * <code>optional string javaClass = 4;</code>
   */
  private void setJavaClassBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
    javaClass_ = value.toStringUtf8();
  }

  public static final int EXTRA_FIELD_NUMBER = 5;
  private com.google.protobuf.Internal.ProtobufList<com.github.yeriomin.playstore.message.AndroidIntentProto.Extra> extra_;
  /**
   * <code>repeated group Extra = 5 { ... }</code>
   */
  public java.util.List<com.github.yeriomin.playstore.message.AndroidIntentProto.Extra> getExtraList() {
    return extra_;
  }
  /**
   * <code>repeated group Extra = 5 { ... }</code>
   */
  public java.util.List<? extends com.github.yeriomin.playstore.message.AndroidIntentProto.ExtraOrBuilder> 
      getExtraOrBuilderList() {
    return extra_;
  }
  /**
   * <code>repeated group Extra = 5 { ... }</code>
   */
  public int getExtraCount() {
    return extra_.size();
  }
  /**
   * <code>repeated group Extra = 5 { ... }</code>
   */
  public com.github.yeriomin.playstore.message.AndroidIntentProto.Extra getExtra(int index) {
    return extra_.get(index);
  }
  /**
   * <code>repeated group Extra = 5 { ... }</code>
   */
  public com.github.yeriomin.playstore.message.AndroidIntentProto.ExtraOrBuilder getExtraOrBuilder(
      int index) {
    return extra_.get(index);
  }
  private void ensureExtraIsMutable() {
    if (!extra_.isModifiable()) {
      extra_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(extra_);
     }
  }

  /**
   * <code>repeated group Extra = 5 { ... }</code>
   */
  private void setExtra(
      int index, com.github.yeriomin.playstore.message.AndroidIntentProto.Extra value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureExtraIsMutable();
    extra_.set(index, value);
  }
  /**
   * <code>repeated group Extra = 5 { ... }</code>
   */
  private void setExtra(
      int index, com.github.yeriomin.playstore.message.AndroidIntentProto.Extra.Builder builderForValue) {
    ensureExtraIsMutable();
    extra_.set(index, builderForValue.build());
  }
  /**
   * <code>repeated group Extra = 5 { ... }</code>
   */
  private void addExtra(com.github.yeriomin.playstore.message.AndroidIntentProto.Extra value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureExtraIsMutable();
    extra_.add(value);
  }
  /**
   * <code>repeated group Extra = 5 { ... }</code>
   */
  private void addExtra(
      int index, com.github.yeriomin.playstore.message.AndroidIntentProto.Extra value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureExtraIsMutable();
    extra_.add(index, value);
  }
  /**
   * <code>repeated group Extra = 5 { ... }</code>
   */
  private void addExtra(
      com.github.yeriomin.playstore.message.AndroidIntentProto.Extra.Builder builderForValue) {
    ensureExtraIsMutable();
    extra_.add(builderForValue.build());
  }
  /**
   * <code>repeated group Extra = 5 { ... }</code>
   */
  private void addExtra(
      int index, com.github.yeriomin.playstore.message.AndroidIntentProto.Extra.Builder builderForValue) {
    ensureExtraIsMutable();
    extra_.add(index, builderForValue.build());
  }
  /**
   * <code>repeated group Extra = 5 { ... }</code>
   */
  private void addAllExtra(
      java.lang.Iterable<? extends com.github.yeriomin.playstore.message.AndroidIntentProto.Extra> values) {
    ensureExtraIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, extra_);
  }
  /**
   * <code>repeated group Extra = 5 { ... }</code>
   */
  private void clearExtra() {
    extra_ = emptyProtobufList();
  }
  /**
   * <code>repeated group Extra = 5 { ... }</code>
   */
  private void removeExtra(int index) {
    ensureExtraIsMutable();
    extra_.remove(index);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeString(1, getAction());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeString(2, getDataUri());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeString(3, getMimeType());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeString(4, getJavaClass());
    }
    for (int i = 0; i < extra_.size(); i++) {
      output.writeGroup(5, extra_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getAction());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getDataUri());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getMimeType());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(4, getJavaClass());
    }
    for (int i = 0; i < extra_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeGroupSize(5, extra_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static com.github.yeriomin.playstore.message.AndroidIntentProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstore.message.AndroidIntentProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.message.AndroidIntentProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstore.message.AndroidIntentProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.message.AndroidIntentProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.message.AndroidIntentProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.message.AndroidIntentProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.message.AndroidIntentProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.message.AndroidIntentProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.message.AndroidIntentProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.yeriomin.playstore.message.AndroidIntentProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code AndroidIntentProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.github.yeriomin.playstore.message.AndroidIntentProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:AndroidIntentProto)
      com.github.yeriomin.playstore.message.AndroidIntentProtoOrBuilder {
    // Construct using com.github.yeriomin.playstoreapi.AndroidIntentProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string action = 1;</code>
     */
    public boolean hasAction() {
      return instance.hasAction();
    }
    /**
     * <code>optional string action = 1;</code>
     */
    public java.lang.String getAction() {
      return instance.getAction();
    }
    /**
     * <code>optional string action = 1;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      return instance.getActionBytes();
    }
    /**
     * <code>optional string action = 1;</code>
     */
    public Builder setAction(
        java.lang.String value) {
      copyOnWrite();
      instance.setAction(value);
      return this;
    }
    /**
     * <code>optional string action = 1;</code>
     */
    public Builder clearAction() {
      copyOnWrite();
      instance.clearAction();
      return this;
    }
    /**
     * <code>optional string action = 1;</code>
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setActionBytes(value);
      return this;
    }

    /**
     * <code>optional string dataUri = 2;</code>
     */
    public boolean hasDataUri() {
      return instance.hasDataUri();
    }
    /**
     * <code>optional string dataUri = 2;</code>
     */
    public java.lang.String getDataUri() {
      return instance.getDataUri();
    }
    /**
     * <code>optional string dataUri = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataUriBytes() {
      return instance.getDataUriBytes();
    }
    /**
     * <code>optional string dataUri = 2;</code>
     */
    public Builder setDataUri(
        java.lang.String value) {
      copyOnWrite();
      instance.setDataUri(value);
      return this;
    }
    /**
     * <code>optional string dataUri = 2;</code>
     */
    public Builder clearDataUri() {
      copyOnWrite();
      instance.clearDataUri();
      return this;
    }
    /**
     * <code>optional string dataUri = 2;</code>
     */
    public Builder setDataUriBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDataUriBytes(value);
      return this;
    }

    /**
     * <code>optional string mimeType = 3;</code>
     */
    public boolean hasMimeType() {
      return instance.hasMimeType();
    }
    /**
     * <code>optional string mimeType = 3;</code>
     */
    public java.lang.String getMimeType() {
      return instance.getMimeType();
    }
    /**
     * <code>optional string mimeType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMimeTypeBytes() {
      return instance.getMimeTypeBytes();
    }
    /**
     * <code>optional string mimeType = 3;</code>
     */
    public Builder setMimeType(
        java.lang.String value) {
      copyOnWrite();
      instance.setMimeType(value);
      return this;
    }
    /**
     * <code>optional string mimeType = 3;</code>
     */
    public Builder clearMimeType() {
      copyOnWrite();
      instance.clearMimeType();
      return this;
    }
    /**
     * <code>optional string mimeType = 3;</code>
     */
    public Builder setMimeTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMimeTypeBytes(value);
      return this;
    }

    /**
     * <code>optional string javaClass = 4;</code>
     */
    public boolean hasJavaClass() {
      return instance.hasJavaClass();
    }
    /**
     * <code>optional string javaClass = 4;</code>
     */
    public java.lang.String getJavaClass() {
      return instance.getJavaClass();
    }
    /**
     * <code>optional string javaClass = 4;</code>
     */
    public com.google.protobuf.ByteString
        getJavaClassBytes() {
      return instance.getJavaClassBytes();
    }
    /**
     * <code>optional string javaClass = 4;</code>
     */
    public Builder setJavaClass(
        java.lang.String value) {
      copyOnWrite();
      instance.setJavaClass(value);
      return this;
    }
    /**
     * <code>optional string javaClass = 4;</code>
     */
    public Builder clearJavaClass() {
      copyOnWrite();
      instance.clearJavaClass();
      return this;
    }
    /**
     * <code>optional string javaClass = 4;</code>
     */
    public Builder setJavaClassBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setJavaClassBytes(value);
      return this;
    }

    /**
     * <code>repeated group Extra = 5 { ... }</code>
     */
    public java.util.List<com.github.yeriomin.playstore.message.AndroidIntentProto.Extra> getExtraList() {
      return java.util.Collections.unmodifiableList(
          instance.getExtraList());
    }
    /**
     * <code>repeated group Extra = 5 { ... }</code>
     */
    public int getExtraCount() {
      return instance.getExtraCount();
    }/**
     * <code>repeated group Extra = 5 { ... }</code>
     */
    public com.github.yeriomin.playstore.message.AndroidIntentProto.Extra getExtra(int index) {
      return instance.getExtra(index);
    }
    /**
     * <code>repeated group Extra = 5 { ... }</code>
     */
    public Builder setExtra(
        int index, com.github.yeriomin.playstore.message.AndroidIntentProto.Extra value) {
      copyOnWrite();
      instance.setExtra(index, value);
      return this;
    }
    /**
     * <code>repeated group Extra = 5 { ... }</code>
     */
    public Builder setExtra(
        int index, com.github.yeriomin.playstore.message.AndroidIntentProto.Extra.Builder builderForValue) {
      copyOnWrite();
      instance.setExtra(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated group Extra = 5 { ... }</code>
     */
    public Builder addExtra(com.github.yeriomin.playstore.message.AndroidIntentProto.Extra value) {
      copyOnWrite();
      instance.addExtra(value);
      return this;
    }
    /**
     * <code>repeated group Extra = 5 { ... }</code>
     */
    public Builder addExtra(
        int index, com.github.yeriomin.playstore.message.AndroidIntentProto.Extra value) {
      copyOnWrite();
      instance.addExtra(index, value);
      return this;
    }
    /**
     * <code>repeated group Extra = 5 { ... }</code>
     */
    public Builder addExtra(
        com.github.yeriomin.playstore.message.AndroidIntentProto.Extra.Builder builderForValue) {
      copyOnWrite();
      instance.addExtra(builderForValue);
      return this;
    }
    /**
     * <code>repeated group Extra = 5 { ... }</code>
     */
    public Builder addExtra(
        int index, com.github.yeriomin.playstore.message.AndroidIntentProto.Extra.Builder builderForValue) {
      copyOnWrite();
      instance.addExtra(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated group Extra = 5 { ... }</code>
     */
    public Builder addAllExtra(
        java.lang.Iterable<? extends com.github.yeriomin.playstore.message.AndroidIntentProto.Extra> values) {
      copyOnWrite();
      instance.addAllExtra(values);
      return this;
    }
    /**
     * <code>repeated group Extra = 5 { ... }</code>
     */
    public Builder clearExtra() {
      copyOnWrite();
      instance.clearExtra();
      return this;
    }
    /**
     * <code>repeated group Extra = 5 { ... }</code>
     */
    public Builder removeExtra(int index) {
      copyOnWrite();
      instance.removeExtra(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:AndroidIntentProto)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.github.yeriomin.playstore.message.AndroidIntentProto();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        extra_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.github.yeriomin.playstore.message.AndroidIntentProto other = (com.github.yeriomin.playstore.message.AndroidIntentProto) arg1;
        action_ = visitor.visitString(
            hasAction(), action_,
            other.hasAction(), other.action_);
        dataUri_ = visitor.visitString(
            hasDataUri(), dataUri_,
            other.hasDataUri(), other.dataUri_);
        mimeType_ = visitor.visitString(
            hasMimeType(), mimeType_,
            other.hasMimeType(), other.mimeType_);
        javaClass_ = visitor.visitString(
            hasJavaClass(), javaClass_,
            other.hasJavaClass(), other.javaClass_);
        extra_= visitor.visitList(extra_, other.extra_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readString();
                bitField0_ |= 0x00000001;
                action_ = s;
                break;
              }
              case 18: {
                String s = input.readString();
                bitField0_ |= 0x00000002;
                dataUri_ = s;
                break;
              }
              case 26: {
                String s = input.readString();
                bitField0_ |= 0x00000004;
                mimeType_ = s;
                break;
              }
              case 34: {
                String s = input.readString();
                bitField0_ |= 0x00000008;
                javaClass_ = s;
                break;
              }
              case 43: {
                if (!extra_.isModifiable()) {
                  extra_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(extra_);
                }
                extra_.add(input.readGroup(5, com.github.yeriomin.playstore.message.AndroidIntentProto.Extra.parser(),
                    extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.github.yeriomin.playstore.message.AndroidIntentProto.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:AndroidIntentProto)
  private static final com.github.yeriomin.playstore.message.AndroidIntentProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AndroidIntentProto();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.github.yeriomin.playstore.message.AndroidIntentProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AndroidIntentProto> PARSER;

  public static com.google.protobuf.Parser<AndroidIntentProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

