// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.message;

public interface BuyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BuyResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .PurchaseNotificationResponse purchaseResponse = 1;</code>
   */
  boolean hasPurchaseResponse();
  /**
   * <code>optional .PurchaseNotificationResponse purchaseResponse = 1;</code>
   */
  com.github.yeriomin.playstore.message.PurchaseNotificationResponse getPurchaseResponse();

  /**
   * <code>optional group CheckoutInfo = 2 { ... }</code>
   */
  boolean hasCheckoutInfo();
  /**
   * <code>optional group CheckoutInfo = 2 { ... }</code>
   */
  com.github.yeriomin.playstore.message.BuyResponse.CheckoutInfo getCheckoutInfo();

  /**
   * <code>optional string continueViaUrl = 8;</code>
   */
  boolean hasContinueViaUrl();
  /**
   * <code>optional string continueViaUrl = 8;</code>
   */
  java.lang.String getContinueViaUrl();
  /**
   * <code>optional string continueViaUrl = 8;</code>
   */
  com.google.protobuf.ByteString
      getContinueViaUrlBytes();

  /**
   * <code>optional string purchaseStatusUrl = 9;</code>
   */
  boolean hasPurchaseStatusUrl();
  /**
   * <code>optional string purchaseStatusUrl = 9;</code>
   */
  java.lang.String getPurchaseStatusUrl();
  /**
   * <code>optional string purchaseStatusUrl = 9;</code>
   */
  com.google.protobuf.ByteString
      getPurchaseStatusUrlBytes();

  /**
   * <code>optional string checkoutServiceId = 12;</code>
   */
  boolean hasCheckoutServiceId();
  /**
   * <code>optional string checkoutServiceId = 12;</code>
   */
  java.lang.String getCheckoutServiceId();
  /**
   * <code>optional string checkoutServiceId = 12;</code>
   */
  com.google.protobuf.ByteString
      getCheckoutServiceIdBytes();

  /**
   * <code>optional bool checkoutTokenRequired = 13;</code>
   */
  boolean hasCheckoutTokenRequired();
  /**
   * <code>optional bool checkoutTokenRequired = 13;</code>
   */
  boolean getCheckoutTokenRequired();

  /**
   * <code>optional string baseCheckoutUrl = 14;</code>
   */
  boolean hasBaseCheckoutUrl();
  /**
   * <code>optional string baseCheckoutUrl = 14;</code>
   */
  java.lang.String getBaseCheckoutUrl();
  /**
   * <code>optional string baseCheckoutUrl = 14;</code>
   */
  com.google.protobuf.ByteString
      getBaseCheckoutUrlBytes();

  /**
   * <code>repeated string tosCheckboxHtml = 37;</code>
   */
  java.util.List<String>
      getTosCheckboxHtmlList();
  /**
   * <code>repeated string tosCheckboxHtml = 37;</code>
   */
  int getTosCheckboxHtmlCount();
  /**
   * <code>repeated string tosCheckboxHtml = 37;</code>
   */
  java.lang.String getTosCheckboxHtml(int index);
  /**
   * <code>repeated string tosCheckboxHtml = 37;</code>
   */
  com.google.protobuf.ByteString
      getTosCheckboxHtmlBytes(int index);

  /**
   * <code>optional int32 iabPermissionError = 38;</code>
   */
  boolean hasIabPermissionError();
  /**
   * <code>optional int32 iabPermissionError = 38;</code>
   */
  int getIabPermissionError();

  /**
   * <code>optional .PurchaseStatusResponse purchaseStatusResponse = 39;</code>
   */
  boolean hasPurchaseStatusResponse();
  /**
   * <code>optional .PurchaseStatusResponse purchaseStatusResponse = 39;</code>
   */
  com.github.yeriomin.playstore.message.PurchaseStatusResponse getPurchaseStatusResponse();

  /**
   * <code>optional string purchaseCookie = 46;</code>
   */
  boolean hasPurchaseCookie();
  /**
   * <code>optional string purchaseCookie = 46;</code>
   */
  java.lang.String getPurchaseCookie();
  /**
   * <code>optional string purchaseCookie = 46;</code>
   */
  com.google.protobuf.ByteString
      getPurchaseCookieBytes();

  /**
   * <code>optional .Challenge challenge = 49;</code>
   */
  boolean hasChallenge();
  /**
   * <code>optional .Challenge challenge = 49;</code>
   */
  com.github.yeriomin.playstore.message.Challenge getChallenge();

  /**
   * <code>optional string downloadToken = 55;</code>
   */
  boolean hasDownloadToken();
  /**
   * <code>optional string downloadToken = 55;</code>
   */
  java.lang.String getDownloadToken();
  /**
   * <code>optional string downloadToken = 55;</code>
   */
  com.google.protobuf.ByteString
      getDownloadTokenBytes();
}
