// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.message;

/**
 * Protobuf type {@code CarrierBillingInstrumentStatus}
 */
public  final class CarrierBillingInstrumentStatus extends
    com.google.protobuf.GeneratedMessageLite<
        CarrierBillingInstrumentStatus, CarrierBillingInstrumentStatus.Builder> implements
    // @@protoc_insertion_point(message_implements:CarrierBillingInstrumentStatus)
    CarrierBillingInstrumentStatusOrBuilder {
  private CarrierBillingInstrumentStatus() {
    name_ = "";
  }
  private int bitField0_;
  public static final int CARRIERTOS_FIELD_NUMBER = 1;
  private com.github.yeriomin.playstore.message.CarrierTos carrierTos_;
  /**
   * <code>optional .CarrierTos carrierTos = 1;</code>
   */
  public boolean hasCarrierTos() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional .CarrierTos carrierTos = 1;</code>
   */
  public com.github.yeriomin.playstore.message.CarrierTos getCarrierTos() {
    return carrierTos_ == null ? com.github.yeriomin.playstore.message.CarrierTos.getDefaultInstance() : carrierTos_;
  }
  /**
   * <code>optional .CarrierTos carrierTos = 1;</code>
   */
  private void setCarrierTos(com.github.yeriomin.playstore.message.CarrierTos value) {
    if (value == null) {
      throw new NullPointerException();
    }
    carrierTos_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>optional .CarrierTos carrierTos = 1;</code>
   */
  private void setCarrierTos(
      com.github.yeriomin.playstore.message.CarrierTos.Builder builderForValue) {
    carrierTos_ = builderForValue.build();
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .CarrierTos carrierTos = 1;</code>
   */
  private void mergeCarrierTos(com.github.yeriomin.playstore.message.CarrierTos value) {
    if (carrierTos_ != null &&
        carrierTos_ != com.github.yeriomin.playstore.message.CarrierTos.getDefaultInstance()) {
      carrierTos_ =
        com.github.yeriomin.playstore.message.CarrierTos.newBuilder(carrierTos_).mergeFrom(value).buildPartial();
    } else {
      carrierTos_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .CarrierTos carrierTos = 1;</code>
   */
  private void clearCarrierTos() {  carrierTos_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int ASSOCIATIONREQUIRED_FIELD_NUMBER = 2;
  private boolean associationRequired_;
  /**
   * <code>optional bool associationRequired = 2;</code>
   */
  public boolean hasAssociationRequired() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional bool associationRequired = 2;</code>
   */
  public boolean getAssociationRequired() {
    return associationRequired_;
  }
  /**
   * <code>optional bool associationRequired = 2;</code>
   */
  private void setAssociationRequired(boolean value) {
    bitField0_ |= 0x00000002;
    associationRequired_ = value;
  }
  /**
   * <code>optional bool associationRequired = 2;</code>
   */
  private void clearAssociationRequired() {
    bitField0_ = (bitField0_ & ~0x00000002);
    associationRequired_ = false;
  }

  public static final int PASSWORDREQUIRED_FIELD_NUMBER = 3;
  private boolean passwordRequired_;
  /**
   * <code>optional bool passwordRequired = 3;</code>
   */
  public boolean hasPasswordRequired() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional bool passwordRequired = 3;</code>
   */
  public boolean getPasswordRequired() {
    return passwordRequired_;
  }
  /**
   * <code>optional bool passwordRequired = 3;</code>
   */
  private void setPasswordRequired(boolean value) {
    bitField0_ |= 0x00000004;
    passwordRequired_ = value;
  }
  /**
   * <code>optional bool passwordRequired = 3;</code>
   */
  private void clearPasswordRequired() {
    bitField0_ = (bitField0_ & ~0x00000004);
    passwordRequired_ = false;
  }

  public static final int CARRIERPASSWORDPROMPT_FIELD_NUMBER = 4;
  private com.github.yeriomin.playstore.message.PasswordPrompt carrierPasswordPrompt_;
  /**
   * <code>optional .PasswordPrompt carrierPasswordPrompt = 4;</code>
   */
  public boolean hasCarrierPasswordPrompt() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional .PasswordPrompt carrierPasswordPrompt = 4;</code>
   */
  public com.github.yeriomin.playstore.message.PasswordPrompt getCarrierPasswordPrompt() {
    return carrierPasswordPrompt_ == null ? com.github.yeriomin.playstore.message.PasswordPrompt.getDefaultInstance() : carrierPasswordPrompt_;
  }
  /**
   * <code>optional .PasswordPrompt carrierPasswordPrompt = 4;</code>
   */
  private void setCarrierPasswordPrompt(com.github.yeriomin.playstore.message.PasswordPrompt value) {
    if (value == null) {
      throw new NullPointerException();
    }
    carrierPasswordPrompt_ = value;
    bitField0_ |= 0x00000008;
    }
  /**
   * <code>optional .PasswordPrompt carrierPasswordPrompt = 4;</code>
   */
  private void setCarrierPasswordPrompt(
      com.github.yeriomin.playstore.message.PasswordPrompt.Builder builderForValue) {
    carrierPasswordPrompt_ = builderForValue.build();
    bitField0_ |= 0x00000008;
  }
  /**
   * <code>optional .PasswordPrompt carrierPasswordPrompt = 4;</code>
   */
  private void mergeCarrierPasswordPrompt(com.github.yeriomin.playstore.message.PasswordPrompt value) {
    if (carrierPasswordPrompt_ != null &&
        carrierPasswordPrompt_ != com.github.yeriomin.playstore.message.PasswordPrompt.getDefaultInstance()) {
      carrierPasswordPrompt_ =
        com.github.yeriomin.playstore.message.PasswordPrompt.newBuilder(carrierPasswordPrompt_).mergeFrom(value).buildPartial();
    } else {
      carrierPasswordPrompt_ = value;
    }
    bitField0_ |= 0x00000008;
  }
  /**
   * <code>optional .PasswordPrompt carrierPasswordPrompt = 4;</code>
   */
  private void clearCarrierPasswordPrompt() {  carrierPasswordPrompt_ = null;
    bitField0_ = (bitField0_ & ~0x00000008);
  }

  public static final int APIVERSION_FIELD_NUMBER = 5;
  private int apiVersion_;
  /**
   * <code>optional int32 apiVersion = 5;</code>
   */
  public boolean hasApiVersion() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional int32 apiVersion = 5;</code>
   */
  public int getApiVersion() {
    return apiVersion_;
  }
  /**
   * <code>optional int32 apiVersion = 5;</code>
   */
  private void setApiVersion(int value) {
    bitField0_ |= 0x00000010;
    apiVersion_ = value;
  }
  /**
   * <code>optional int32 apiVersion = 5;</code>
   */
  private void clearApiVersion() {
    bitField0_ = (bitField0_ & ~0x00000010);
    apiVersion_ = 0;
  }

  public static final int NAME_FIELD_NUMBER = 6;
  private java.lang.String name_;
  /**
   * <code>optional string name = 6;</code>
   */
  public boolean hasName() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional string name = 6;</code>
   */
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>optional string name = 6;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>optional string name = 6;</code>
   */
  private void setName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
    name_ = value;
  }
  /**
   * <code>optional string name = 6;</code>
   */
  private void clearName() {
    bitField0_ = (bitField0_ & ~0x00000020);
    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>optional string name = 6;</code>
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
    name_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, getCarrierTos());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBool(2, associationRequired_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBool(3, passwordRequired_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeMessage(4, getCarrierPasswordPrompt());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeInt32(5, apiVersion_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeString(6, getName());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCarrierTos());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, associationRequired_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, passwordRequired_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCarrierPasswordPrompt());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, apiVersion_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(6, getName());
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code CarrierBillingInstrumentStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus, Builder> implements
      // @@protoc_insertion_point(builder_implements:CarrierBillingInstrumentStatus)
      com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatusOrBuilder {
    // Construct using com.github.yeriomin.playstoreapi.CarrierBillingInstrumentStatus.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .CarrierTos carrierTos = 1;</code>
     */
    public boolean hasCarrierTos() {
      return instance.hasCarrierTos();
    }
    /**
     * <code>optional .CarrierTos carrierTos = 1;</code>
     */
    public com.github.yeriomin.playstore.message.CarrierTos getCarrierTos() {
      return instance.getCarrierTos();
    }
    /**
     * <code>optional .CarrierTos carrierTos = 1;</code>
     */
    public Builder setCarrierTos(com.github.yeriomin.playstore.message.CarrierTos value) {
      copyOnWrite();
      instance.setCarrierTos(value);
      return this;
      }
    /**
     * <code>optional .CarrierTos carrierTos = 1;</code>
     */
    public Builder setCarrierTos(
        com.github.yeriomin.playstore.message.CarrierTos.Builder builderForValue) {
      copyOnWrite();
      instance.setCarrierTos(builderForValue);
      return this;
    }
    /**
     * <code>optional .CarrierTos carrierTos = 1;</code>
     */
    public Builder mergeCarrierTos(com.github.yeriomin.playstore.message.CarrierTos value) {
      copyOnWrite();
      instance.mergeCarrierTos(value);
      return this;
    }
    /**
     * <code>optional .CarrierTos carrierTos = 1;</code>
     */
    public Builder clearCarrierTos() {  copyOnWrite();
      instance.clearCarrierTos();
      return this;
    }

    /**
     * <code>optional bool associationRequired = 2;</code>
     */
    public boolean hasAssociationRequired() {
      return instance.hasAssociationRequired();
    }
    /**
     * <code>optional bool associationRequired = 2;</code>
     */
    public boolean getAssociationRequired() {
      return instance.getAssociationRequired();
    }
    /**
     * <code>optional bool associationRequired = 2;</code>
     */
    public Builder setAssociationRequired(boolean value) {
      copyOnWrite();
      instance.setAssociationRequired(value);
      return this;
    }
    /**
     * <code>optional bool associationRequired = 2;</code>
     */
    public Builder clearAssociationRequired() {
      copyOnWrite();
      instance.clearAssociationRequired();
      return this;
    }

    /**
     * <code>optional bool passwordRequired = 3;</code>
     */
    public boolean hasPasswordRequired() {
      return instance.hasPasswordRequired();
    }
    /**
     * <code>optional bool passwordRequired = 3;</code>
     */
    public boolean getPasswordRequired() {
      return instance.getPasswordRequired();
    }
    /**
     * <code>optional bool passwordRequired = 3;</code>
     */
    public Builder setPasswordRequired(boolean value) {
      copyOnWrite();
      instance.setPasswordRequired(value);
      return this;
    }
    /**
     * <code>optional bool passwordRequired = 3;</code>
     */
    public Builder clearPasswordRequired() {
      copyOnWrite();
      instance.clearPasswordRequired();
      return this;
    }

    /**
     * <code>optional .PasswordPrompt carrierPasswordPrompt = 4;</code>
     */
    public boolean hasCarrierPasswordPrompt() {
      return instance.hasCarrierPasswordPrompt();
    }
    /**
     * <code>optional .PasswordPrompt carrierPasswordPrompt = 4;</code>
     */
    public com.github.yeriomin.playstore.message.PasswordPrompt getCarrierPasswordPrompt() {
      return instance.getCarrierPasswordPrompt();
    }
    /**
     * <code>optional .PasswordPrompt carrierPasswordPrompt = 4;</code>
     */
    public Builder setCarrierPasswordPrompt(com.github.yeriomin.playstore.message.PasswordPrompt value) {
      copyOnWrite();
      instance.setCarrierPasswordPrompt(value);
      return this;
      }
    /**
     * <code>optional .PasswordPrompt carrierPasswordPrompt = 4;</code>
     */
    public Builder setCarrierPasswordPrompt(
        com.github.yeriomin.playstore.message.PasswordPrompt.Builder builderForValue) {
      copyOnWrite();
      instance.setCarrierPasswordPrompt(builderForValue);
      return this;
    }
    /**
     * <code>optional .PasswordPrompt carrierPasswordPrompt = 4;</code>
     */
    public Builder mergeCarrierPasswordPrompt(com.github.yeriomin.playstore.message.PasswordPrompt value) {
      copyOnWrite();
      instance.mergeCarrierPasswordPrompt(value);
      return this;
    }
    /**
     * <code>optional .PasswordPrompt carrierPasswordPrompt = 4;</code>
     */
    public Builder clearCarrierPasswordPrompt() {  copyOnWrite();
      instance.clearCarrierPasswordPrompt();
      return this;
    }

    /**
     * <code>optional int32 apiVersion = 5;</code>
     */
    public boolean hasApiVersion() {
      return instance.hasApiVersion();
    }
    /**
     * <code>optional int32 apiVersion = 5;</code>
     */
    public int getApiVersion() {
      return instance.getApiVersion();
    }
    /**
     * <code>optional int32 apiVersion = 5;</code>
     */
    public Builder setApiVersion(int value) {
      copyOnWrite();
      instance.setApiVersion(value);
      return this;
    }
    /**
     * <code>optional int32 apiVersion = 5;</code>
     */
    public Builder clearApiVersion() {
      copyOnWrite();
      instance.clearApiVersion();
      return this;
    }

    /**
     * <code>optional string name = 6;</code>
     */
    public boolean hasName() {
      return instance.hasName();
    }
    /**
     * <code>optional string name = 6;</code>
     */
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>optional string name = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>optional string name = 6;</code>
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>optional string name = 6;</code>
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>optional string name = 6;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:CarrierBillingInstrumentStatus)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus other = (com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus) arg1;
        carrierTos_ = visitor.visitMessage(carrierTos_, other.carrierTos_);
        associationRequired_ = visitor.visitBoolean(
            hasAssociationRequired(), associationRequired_,
            other.hasAssociationRequired(), other.associationRequired_);
        passwordRequired_ = visitor.visitBoolean(
            hasPasswordRequired(), passwordRequired_,
            other.hasPasswordRequired(), other.passwordRequired_);
        carrierPasswordPrompt_ = visitor.visitMessage(carrierPasswordPrompt_, other.carrierPasswordPrompt_);
        apiVersion_ = visitor.visitInt(
            hasApiVersion(), apiVersion_,
            other.hasApiVersion(), other.apiVersion_);
        name_ = visitor.visitString(
            hasName(), name_,
            other.hasName(), other.name_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.github.yeriomin.playstore.message.CarrierTos.Builder subBuilder = null;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                  subBuilder = carrierTos_.toBuilder();
                }
                carrierTos_ = input.readMessage(com.github.yeriomin.playstore.message.CarrierTos.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(carrierTos_);
                  carrierTos_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000001;
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                associationRequired_ = input.readBool();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                passwordRequired_ = input.readBool();
                break;
              }
              case 34: {
                com.github.yeriomin.playstore.message.PasswordPrompt.Builder subBuilder = null;
                if (((bitField0_ & 0x00000008) == 0x00000008)) {
                  subBuilder = carrierPasswordPrompt_.toBuilder();
                }
                carrierPasswordPrompt_ = input.readMessage(com.github.yeriomin.playstore.message.PasswordPrompt.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(carrierPasswordPrompt_);
                  carrierPasswordPrompt_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000008;
                break;
              }
              case 40: {
                bitField0_ |= 0x00000010;
                apiVersion_ = input.readInt32();
                break;
              }
              case 50: {
                String s = input.readString();
                bitField0_ |= 0x00000020;
                name_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:CarrierBillingInstrumentStatus)
  private static final com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CarrierBillingInstrumentStatus();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.github.yeriomin.playstore.message.CarrierBillingInstrumentStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CarrierBillingInstrumentStatus> PARSER;

  public static com.google.protobuf.Parser<CarrierBillingInstrumentStatus> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

