// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.message;

/**
 * Protobuf type {@code CategoryContainer}
 */
public  final class CategoryContainer extends
    com.google.protobuf.GeneratedMessageLite<
        CategoryContainer, CategoryContainer.Builder> implements
    // @@protoc_insertion_point(message_implements:CategoryContainer)
    CategoryContainerOrBuilder {
  private CategoryContainer() {
    category_ = emptyProtobufList();
  }
  public static final int CATEGORY_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.ProtobufList<com.github.yeriomin.playstore.message.BrowseLink> category_;
  /**
   * <code>repeated .BrowseLink category = 4;</code>
   */
  public java.util.List<com.github.yeriomin.playstore.message.BrowseLink> getCategoryList() {
    return category_;
  }
  /**
   * <code>repeated .BrowseLink category = 4;</code>
   */
  public java.util.List<? extends com.github.yeriomin.playstore.message.BrowseLinkOrBuilder> 
      getCategoryOrBuilderList() {
    return category_;
  }
  /**
   * <code>repeated .BrowseLink category = 4;</code>
   */
  public int getCategoryCount() {
    return category_.size();
  }
  /**
   * <code>repeated .BrowseLink category = 4;</code>
   */
  public com.github.yeriomin.playstore.message.BrowseLink getCategory(int index) {
    return category_.get(index);
  }
  /**
   * <code>repeated .BrowseLink category = 4;</code>
   */
  public com.github.yeriomin.playstore.message.BrowseLinkOrBuilder getCategoryOrBuilder(
      int index) {
    return category_.get(index);
  }
  private void ensureCategoryIsMutable() {
    if (!category_.isModifiable()) {
      category_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(category_);
     }
  }

  /**
   * <code>repeated .BrowseLink category = 4;</code>
   */
  private void setCategory(
      int index, com.github.yeriomin.playstore.message.BrowseLink value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureCategoryIsMutable();
    category_.set(index, value);
  }
  /**
   * <code>repeated .BrowseLink category = 4;</code>
   */
  private void setCategory(
      int index, com.github.yeriomin.playstore.message.BrowseLink.Builder builderForValue) {
    ensureCategoryIsMutable();
    category_.set(index, builderForValue.build());
  }
  /**
   * <code>repeated .BrowseLink category = 4;</code>
   */
  private void addCategory(com.github.yeriomin.playstore.message.BrowseLink value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureCategoryIsMutable();
    category_.add(value);
  }
  /**
   * <code>repeated .BrowseLink category = 4;</code>
   */
  private void addCategory(
      int index, com.github.yeriomin.playstore.message.BrowseLink value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureCategoryIsMutable();
    category_.add(index, value);
  }
  /**
   * <code>repeated .BrowseLink category = 4;</code>
   */
  private void addCategory(
      com.github.yeriomin.playstore.message.BrowseLink.Builder builderForValue) {
    ensureCategoryIsMutable();
    category_.add(builderForValue.build());
  }
  /**
   * <code>repeated .BrowseLink category = 4;</code>
   */
  private void addCategory(
      int index, com.github.yeriomin.playstore.message.BrowseLink.Builder builderForValue) {
    ensureCategoryIsMutable();
    category_.add(index, builderForValue.build());
  }
  /**
   * <code>repeated .BrowseLink category = 4;</code>
   */
  private void addAllCategory(
      java.lang.Iterable<? extends com.github.yeriomin.playstore.message.BrowseLink> values) {
    ensureCategoryIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, category_);
  }
  /**
   * <code>repeated .BrowseLink category = 4;</code>
   */
  private void clearCategory() {
    category_ = emptyProtobufList();
  }
  /**
   * <code>repeated .BrowseLink category = 4;</code>
   */
  private void removeCategory(int index) {
    ensureCategoryIsMutable();
    category_.remove(index);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < category_.size(); i++) {
      output.writeMessage(4, category_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < category_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, category_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static com.github.yeriomin.playstore.message.CategoryContainer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstore.message.CategoryContainer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.message.CategoryContainer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstore.message.CategoryContainer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.message.CategoryContainer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.message.CategoryContainer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.message.CategoryContainer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.message.CategoryContainer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.message.CategoryContainer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.message.CategoryContainer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.yeriomin.playstore.message.CategoryContainer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code CategoryContainer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.github.yeriomin.playstore.message.CategoryContainer, Builder> implements
      // @@protoc_insertion_point(builder_implements:CategoryContainer)
      com.github.yeriomin.playstore.message.CategoryContainerOrBuilder {
    // Construct using com.github.yeriomin.playstoreapi.CategoryContainer.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .BrowseLink category = 4;</code>
     */
    public java.util.List<com.github.yeriomin.playstore.message.BrowseLink> getCategoryList() {
      return java.util.Collections.unmodifiableList(
          instance.getCategoryList());
    }
    /**
     * <code>repeated .BrowseLink category = 4;</code>
     */
    public int getCategoryCount() {
      return instance.getCategoryCount();
    }/**
     * <code>repeated .BrowseLink category = 4;</code>
     */
    public com.github.yeriomin.playstore.message.BrowseLink getCategory(int index) {
      return instance.getCategory(index);
    }
    /**
     * <code>repeated .BrowseLink category = 4;</code>
     */
    public Builder setCategory(
        int index, com.github.yeriomin.playstore.message.BrowseLink value) {
      copyOnWrite();
      instance.setCategory(index, value);
      return this;
    }
    /**
     * <code>repeated .BrowseLink category = 4;</code>
     */
    public Builder setCategory(
        int index, com.github.yeriomin.playstore.message.BrowseLink.Builder builderForValue) {
      copyOnWrite();
      instance.setCategory(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .BrowseLink category = 4;</code>
     */
    public Builder addCategory(com.github.yeriomin.playstore.message.BrowseLink value) {
      copyOnWrite();
      instance.addCategory(value);
      return this;
    }
    /**
     * <code>repeated .BrowseLink category = 4;</code>
     */
    public Builder addCategory(
        int index, com.github.yeriomin.playstore.message.BrowseLink value) {
      copyOnWrite();
      instance.addCategory(index, value);
      return this;
    }
    /**
     * <code>repeated .BrowseLink category = 4;</code>
     */
    public Builder addCategory(
        com.github.yeriomin.playstore.message.BrowseLink.Builder builderForValue) {
      copyOnWrite();
      instance.addCategory(builderForValue);
      return this;
    }
    /**
     * <code>repeated .BrowseLink category = 4;</code>
     */
    public Builder addCategory(
        int index, com.github.yeriomin.playstore.message.BrowseLink.Builder builderForValue) {
      copyOnWrite();
      instance.addCategory(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .BrowseLink category = 4;</code>
     */
    public Builder addAllCategory(
        java.lang.Iterable<? extends com.github.yeriomin.playstore.message.BrowseLink> values) {
      copyOnWrite();
      instance.addAllCategory(values);
      return this;
    }
    /**
     * <code>repeated .BrowseLink category = 4;</code>
     */
    public Builder clearCategory() {
      copyOnWrite();
      instance.clearCategory();
      return this;
    }
    /**
     * <code>repeated .BrowseLink category = 4;</code>
     */
    public Builder removeCategory(int index) {
      copyOnWrite();
      instance.removeCategory(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:CategoryContainer)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.github.yeriomin.playstore.message.CategoryContainer();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        category_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.github.yeriomin.playstore.message.CategoryContainer other = (com.github.yeriomin.playstore.message.CategoryContainer) arg1;
        category_= visitor.visitList(category_, other.category_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 34: {
                if (!category_.isModifiable()) {
                  category_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(category_);
                }
                category_.add(
                    input.readMessage(com.github.yeriomin.playstore.message.BrowseLink.parser(), extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.github.yeriomin.playstore.message.CategoryContainer.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:CategoryContainer)
  private static final com.github.yeriomin.playstore.message.CategoryContainer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CategoryContainer();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.github.yeriomin.playstore.message.CategoryContainer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CategoryContainer> PARSER;

  public static com.google.protobuf.Parser<CategoryContainer> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

