// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.message;

public interface DependenciesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Dependencies)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int32 unknown1 = 1;</code>
   */
  boolean hasUnknown1();
  /**
   * <code>optional int32 unknown1 = 1;</code>
   */
  int getUnknown1();

  /**
   * <code>optional int64 unknown2 = 2;</code>
   */
  boolean hasUnknown2();
  /**
   * <code>optional int64 unknown2 = 2;</code>
   */
  long getUnknown2();

  /**
   * <code>repeated .Dependency dependency = 3;</code>
   */
  java.util.List<com.github.yeriomin.playstore.message.Dependency> 
      getDependencyList();
  /**
   * <code>repeated .Dependency dependency = 3;</code>
   */
  com.github.yeriomin.playstore.message.Dependency getDependency(int index);
  /**
   * <code>repeated .Dependency dependency = 3;</code>
   */
  int getDependencyCount();

  /**
   * <code>optional int32 unknown3 = 4;</code>
   */
  boolean hasUnknown3();
  /**
   * <code>optional int32 unknown3 = 4;</code>
   */
  int getUnknown3();
}
