// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.message;

public interface PurchaseNotificationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PurchaseNotificationResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int32 status = 1;</code>
   */
  boolean hasStatus();
  /**
   * <code>optional int32 status = 1;</code>
   */
  int getStatus();

  /**
   * <code>optional .DebugInfo debugInfo = 2;</code>
   */
  boolean hasDebugInfo();
  /**
   * <code>optional .DebugInfo debugInfo = 2;</code>
   */
  com.github.yeriomin.playstore.message.DebugInfo getDebugInfo();

  /**
   * <code>optional string localizedErrorMessage = 3;</code>
   */
  boolean hasLocalizedErrorMessage();
  /**
   * <code>optional string localizedErrorMessage = 3;</code>
   */
  java.lang.String getLocalizedErrorMessage();
  /**
   * <code>optional string localizedErrorMessage = 3;</code>
   */
  com.google.protobuf.ByteString
      getLocalizedErrorMessageBytes();

  /**
   * <code>optional string purchaseId = 4;</code>
   */
  boolean hasPurchaseId();
  /**
   * <code>optional string purchaseId = 4;</code>
   */
  java.lang.String getPurchaseId();
  /**
   * <code>optional string purchaseId = 4;</code>
   */
  com.google.protobuf.ByteString
      getPurchaseIdBytes();
}
