// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.message;

public interface PurchaseStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PurchaseStatusResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int32 status = 1;</code>
   */
  boolean hasStatus();
  /**
   * <code>optional int32 status = 1;</code>
   */
  int getStatus();

  /**
   * <code>optional string statusMsg = 2;</code>
   */
  boolean hasStatusMsg();
  /**
   * <code>optional string statusMsg = 2;</code>
   */
  java.lang.String getStatusMsg();
  /**
   * <code>optional string statusMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusMsgBytes();

  /**
   * <code>optional string statusTitle = 3;</code>
   */
  boolean hasStatusTitle();
  /**
   * <code>optional string statusTitle = 3;</code>
   */
  java.lang.String getStatusTitle();
  /**
   * <code>optional string statusTitle = 3;</code>
   */
  com.google.protobuf.ByteString
      getStatusTitleBytes();

  /**
   * <code>optional string briefMessage = 4;</code>
   */
  boolean hasBriefMessage();
  /**
   * <code>optional string briefMessage = 4;</code>
   */
  java.lang.String getBriefMessage();
  /**
   * <code>optional string briefMessage = 4;</code>
   */
  com.google.protobuf.ByteString
      getBriefMessageBytes();

  /**
   * <code>optional string infoUrl = 5;</code>
   */
  boolean hasInfoUrl();
  /**
   * <code>optional string infoUrl = 5;</code>
   */
  java.lang.String getInfoUrl();
  /**
   * <code>optional string infoUrl = 5;</code>
   */
  com.google.protobuf.ByteString
      getInfoUrlBytes();

  /**
   * <code>optional .LibraryUpdate libraryUpdate = 6;</code>
   */
  boolean hasLibraryUpdate();
  /**
   * <code>optional .LibraryUpdate libraryUpdate = 6;</code>
   */
  com.github.yeriomin.playstore.message.LibraryUpdate getLibraryUpdate();

  /**
   * <code>optional .Instrument rejectedInstrument = 7;</code>
   */
  boolean hasRejectedInstrument();
  /**
   * <code>optional .Instrument rejectedInstrument = 7;</code>
   */
  com.github.yeriomin.playstore.message.Instrument getRejectedInstrument();

  /**
   * <code>optional .AndroidAppDeliveryData appDeliveryData = 8;</code>
   */
  boolean hasAppDeliveryData();
  /**
   * <code>optional .AndroidAppDeliveryData appDeliveryData = 8;</code>
   */
  com.github.yeriomin.playstore.message.AndroidAppDeliveryData getAppDeliveryData();
}
