// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.message;

/**
 * Protobuf type {@code PurchaseDeclinedData}
 */
public  final class PurchaseDeclinedData extends
    com.google.protobuf.GeneratedMessageLite<
        PurchaseDeclinedData, PurchaseDeclinedData.Builder> implements
    // @@protoc_insertion_point(message_implements:PurchaseDeclinedData)
    PurchaseDeclinedDataOrBuilder {
  private PurchaseDeclinedData() {
  }
  private int bitField0_;
  public static final int REASON_FIELD_NUMBER = 1;
  private int reason_;
  /**
   * <code>optional int32 reason = 1;</code>
   */
  public boolean hasReason() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional int32 reason = 1;</code>
   */
  public int getReason() {
    return reason_;
  }
  /**
   * <code>optional int32 reason = 1;</code>
   */
  private void setReason(int value) {
    bitField0_ |= 0x00000001;
    reason_ = value;
  }
  /**
   * <code>optional int32 reason = 1;</code>
   */
  private void clearReason() {
    bitField0_ = (bitField0_ & ~0x00000001);
    reason_ = 0;
  }

  public static final int SHOWNOTIFICATION_FIELD_NUMBER = 2;
  private boolean showNotification_;
  /**
   * <code>optional bool showNotification = 2;</code>
   */
  public boolean hasShowNotification() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional bool showNotification = 2;</code>
   */
  public boolean getShowNotification() {
    return showNotification_;
  }
  /**
   * <code>optional bool showNotification = 2;</code>
   */
  private void setShowNotification(boolean value) {
    bitField0_ |= 0x00000002;
    showNotification_ = value;
  }
  /**
   * <code>optional bool showNotification = 2;</code>
   */
  private void clearShowNotification() {
    bitField0_ = (bitField0_ & ~0x00000002);
    showNotification_ = false;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, reason_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBool(2, showNotification_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, reason_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, showNotification_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static com.github.yeriomin.playstore.message.PurchaseDeclinedData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstore.message.PurchaseDeclinedData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.message.PurchaseDeclinedData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.github.yeriomin.playstore.message.PurchaseDeclinedData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.message.PurchaseDeclinedData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.message.PurchaseDeclinedData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.message.PurchaseDeclinedData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.message.PurchaseDeclinedData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.github.yeriomin.playstore.message.PurchaseDeclinedData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.github.yeriomin.playstore.message.PurchaseDeclinedData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.yeriomin.playstore.message.PurchaseDeclinedData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code PurchaseDeclinedData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.github.yeriomin.playstore.message.PurchaseDeclinedData, Builder> implements
      // @@protoc_insertion_point(builder_implements:PurchaseDeclinedData)
      com.github.yeriomin.playstore.message.PurchaseDeclinedDataOrBuilder {
    // Construct using com.github.yeriomin.playstoreapi.PurchaseDeclinedData.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional int32 reason = 1;</code>
     */
    public boolean hasReason() {
      return instance.hasReason();
    }
    /**
     * <code>optional int32 reason = 1;</code>
     */
    public int getReason() {
      return instance.getReason();
    }
    /**
     * <code>optional int32 reason = 1;</code>
     */
    public Builder setReason(int value) {
      copyOnWrite();
      instance.setReason(value);
      return this;
    }
    /**
     * <code>optional int32 reason = 1;</code>
     */
    public Builder clearReason() {
      copyOnWrite();
      instance.clearReason();
      return this;
    }

    /**
     * <code>optional bool showNotification = 2;</code>
     */
    public boolean hasShowNotification() {
      return instance.hasShowNotification();
    }
    /**
     * <code>optional bool showNotification = 2;</code>
     */
    public boolean getShowNotification() {
      return instance.getShowNotification();
    }
    /**
     * <code>optional bool showNotification = 2;</code>
     */
    public Builder setShowNotification(boolean value) {
      copyOnWrite();
      instance.setShowNotification(value);
      return this;
    }
    /**
     * <code>optional bool showNotification = 2;</code>
     */
    public Builder clearShowNotification() {
      copyOnWrite();
      instance.clearShowNotification();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PurchaseDeclinedData)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.github.yeriomin.playstore.message.PurchaseDeclinedData();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.github.yeriomin.playstore.message.PurchaseDeclinedData other = (com.github.yeriomin.playstore.message.PurchaseDeclinedData) arg1;
        reason_ = visitor.visitInt(
            hasReason(), reason_,
            other.hasReason(), other.reason_);
        showNotification_ = visitor.visitBoolean(
            hasShowNotification(), showNotification_,
            other.hasShowNotification(), other.showNotification_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                reason_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                showNotification_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.github.yeriomin.playstore.message.PurchaseDeclinedData.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:PurchaseDeclinedData)
  private static final com.github.yeriomin.playstore.message.PurchaseDeclinedData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PurchaseDeclinedData();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.github.yeriomin.playstore.message.PurchaseDeclinedData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PurchaseDeclinedData> PARSER;

  public static com.google.protobuf.Parser<PurchaseDeclinedData> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

