// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.message;

public interface ResponseWrapperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResponseWrapper)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .Payload payload = 1;</code>
   */
  boolean hasPayload();
  /**
   * <code>optional .Payload payload = 1;</code>
   */
  com.github.yeriomin.playstore.message.Payload getPayload();

  /**
   * <code>optional .ServerCommands commands = 2;</code>
   */
  boolean hasCommands();
  /**
   * <code>optional .ServerCommands commands = 2;</code>
   */
  com.github.yeriomin.playstore.message.ServerCommands getCommands();

  /**
   * <code>repeated .PreFetch preFetch = 3;</code>
   */
  java.util.List<com.github.yeriomin.playstore.message.PreFetch> 
      getPreFetchList();
  /**
   * <code>repeated .PreFetch preFetch = 3;</code>
   */
  com.github.yeriomin.playstore.message.PreFetch getPreFetch(int index);
  /**
   * <code>repeated .PreFetch preFetch = 3;</code>
   */
  int getPreFetchCount();

  /**
   * <code>repeated .Notification notification = 4;</code>
   */
  java.util.List<com.github.yeriomin.playstore.message.Notification> 
      getNotificationList();
  /**
   * <code>repeated .Notification notification = 4;</code>
   */
  com.github.yeriomin.playstore.message.Notification getNotification(int index);
  /**
   * <code>repeated .Notification notification = 4;</code>
   */
  int getNotificationCount();

  /**
   * <code>optional .ServerMetadata serverMetadata = 5;</code>
   */
  boolean hasServerMetadata();
  /**
   * <code>optional .ServerMetadata serverMetadata = 5;</code>
   */
  com.github.yeriomin.playstore.message.ServerMetadata getServerMetadata();

  /**
   * <code>optional .Targets targets = 6;</code>
   */
  boolean hasTargets();
  /**
   * <code>optional .Targets targets = 6;</code>
   */
  com.github.yeriomin.playstore.message.Targets getTargets();

  /**
   * <code>optional .ServerCookies serverCookies = 7;</code>
   */
  boolean hasServerCookies();
  /**
   * <code>optional .ServerCookies serverCookies = 7;</code>
   */
  com.github.yeriomin.playstore.message.ServerCookies getServerCookies();

  /**
   * <code>optional bytes serverLogsCookie = 9;</code>
   */
  boolean hasServerLogsCookie();
  /**
   * <code>optional bytes serverLogsCookie = 9;</code>
   */
  com.google.protobuf.ByteString getServerLogsCookie();
}
