// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.message;

public interface ServerCookiesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServerCookies)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .ServerCookie serverCookie = 1;</code>
   */
  java.util.List<com.github.yeriomin.playstore.message.ServerCookie> 
      getServerCookieList();
  /**
   * <code>repeated .ServerCookie serverCookie = 1;</code>
   */
  com.github.yeriomin.playstore.message.ServerCookie getServerCookie(int index);
  /**
   * <code>repeated .ServerCookie serverCookie = 1;</code>
   */
  int getServerCookieCount();
}
