// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.message;

public interface TestingProgramResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TestingProgramResult)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .TestingProgramDetails details = 4;</code>
   */
  boolean hasDetails();
  /**
   * <code>optional .TestingProgramDetails details = 4;</code>
   */
  com.github.yeriomin.playstore.message.TestingProgramDetails getDetails();
}
