// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GooglePlay.proto

package com.github.yeriomin.playstore.message;

public interface UnknownCategoryContainerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UnknownCategoryContainer)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .CategoryIdContainer categoryIdContainer = 5;</code>
   */
  boolean hasCategoryIdContainer();
  /**
   * <code>optional .CategoryIdContainer categoryIdContainer = 5;</code>
   */
  com.github.yeriomin.playstore.message.CategoryIdContainer getCategoryIdContainer();
}
